/** Collect a stable, order-balanced exact-parent performance A/B artifact. */
import { checked, readText, removeTemporaryDirectory, run, sha256File, temporaryDirectory, writeText } from "./lib/home";
import { DEFAULT_SCHEMA, loadSchema, measured, unavailableMetrics, validateArtifact } from "./performance-attribution";
import { parseDarwinCounters, parseDarwinThermalState } from "./instrumentation-overhead";
// Inventory-visible module edges: tools/performance-attribution.ts and tools/instrumentation-overhead.ts.

declare const __dirname: string;
declare const __filename: string;
export const ROOT = __dirname === "tools" ? "." : __dirname.slice(0, __dirname.lastIndexOf("/tools"));
const REVISION_RE = /^[0-9a-f]{40}$/;
export type RunnerRow = { engine: string; mode: string; workload: string; lanes: number; jobs: number; elapsed_ns: number; checksum: number; process_cpu_user_ns: number; process_cpu_system_ns: number; peak_rss_bytes: number; retained_rss_bytes: number | null; allocations: number | null; allocated_bytes: number | null; instructions: number; cycles: number; energy_joules: number; thermal_state: string };
function requireValue(condition: boolean, message: string): void { if (!condition) throw new Error(message); }

export function commandOutput(arguments_: string[], defaultValue = "unknown"): string { const result = run(arguments_); return result.exitCode === 0 && result.stdout.trim() ? result.stdout.trim() : defaultValue; }
export function resolveRevision(revision: string, repository = ROOT): string { const resolved = commandOutput(["git", "-C", repository, "rev-parse", `${revision}^{commit}`], ""); requireValue(REVISION_RE.test(resolved), `cannot resolve commit: ${revision}`); return resolved; }
export function validateExactParent(parent: string, candidate: string, repository = ROOT): [string, string] { const parentRevision = resolveRevision(parent, repository), candidateRevision = resolveRevision(candidate, repository), candidateParent = resolveRevision(`${candidateRevision}^1`, repository); requireValue(candidateParent === parentRevision, `candidate first parent is ${candidateParent}, not requested exact parent ${parentRevision}`); return [parentRevision, candidateRevision]; }
export function repositoryRevision(path: string): string { const revision = commandOutput(["git", "-C", path, "rev-parse", "HEAD"], ""); requireValue(REVISION_RE.test(revision), `cannot resolve repository revision: ${path}`); return revision; }
export function requireClean(path: string): void { const result = run(["git", "-C", path, "status", "--porcelain", "--untracked-files=no"]); requireValue(result.exitCode === 0, `cannot verify tracked worktree cleanliness: ${path}`); requireValue(!result.stdout.trim(), `refusing exact-parent publication from dirty tracked worktree: ${path}`); }

export function parseBenchmark(stdout: string, expectedMode: string, expectedWorkload: string, lanes: number, jobs: number): [string, number, number] {
  const rows = stdout.split("\n").filter((line) => line.startsWith("zig-js\t")); requireValue(rows.length === 1, `expected one zig-js benchmark row, got ${rows.length}`);
  const fields = rows[0].split("\t"); requireValue(fields.length === 8, `benchmark row width is ${fields.length}, expected 8`);
  const [engine, mode, workload] = fields; requireValue(engine === "zig-js" && mode === expectedMode && workload === expectedWorkload, `benchmark row identity drift: ${JSON.stringify(fields.slice(0, 3))}`);
  requireValue(Number(fields[3]) === lanes && Number(fields[4]) === jobs && Number(fields[5]) === 0, "benchmark lane/jobs/sample identity drift");
  return [engine, Number(fields[6]), Number(fields[7])];
}
export function timeMetric(stderr: string, label: string): number { const match = new RegExp(`(?:^|\\s)([0-9.]+)\\s+${label}(?:\\s|$)`).exec(stderr); requireValue(Boolean(match), `missing ${label} from /usr/bin/time -l`); return Number(match![1]); }
export function parsePeakRss(stderr: string): number { return Math.round(timeMetric(stderr, "maximum resident set size")); }
export function runnerArguments(mode: string, workload: string, jobs: number, lanes: number): string[] { if (mode === "single" || mode === "single_observed") { requireValue(lanes === 1, `${mode} mode requires one lane`); return [mode, workload, String(jobs), "1", mode === "single_observed" ? "--native-observability-telemetry" : "--darwin-rusage"]; } requireValue(["independent_steady", "independent_cold", "shared", "module_cold"].includes(mode), `unsupported benchmark mode: ${mode}`); return [mode, workload, String(jobs), "1", String(lanes), "--darwin-rusage"]; }
export function parseRetainedRss(stdout: string, mode: string, workload: string, jobs: number): number {
  const rows = stdout.split("\n").filter((line) => line.startsWith("zig-js-native-observability\t")); requireValue(rows.length === 1, `expected one native-observability row, got ${rows.length}`);
  const fields = rows[0].split("\t"); requireValue(fields.length === 16 && fields[1] === mode && fields[2] === workload && Number(fields[3]) === jobs && Number(fields[4]) === 0, "native-observability identity drift");
  const retained = Number(fields[15]); requireValue(Number.isInteger(retained) && retained > 0, "native-observability retained RSS is invalid"); return retained;
}
export function parseFrontendAllocations(stdout: string, mode: string, workload: string, jobs: number): [number, number] | null {
  const rows = stdout.split("\n").filter((line) => line.startsWith("zig-js-frontend-allocations\t"));
  if (rows.length === 0) return null;
  requireValue(rows.length === 1, `expected at most one frontend-allocation row, got ${rows.length}`);
  const fields = rows[0].split("\t");
  requireValue(fields.length === 7 && fields[1] === mode && fields[2] === workload && Number(fields[3]) === jobs && Number(fields[4]) === 0, "frontend-allocation identity drift");
  const allocations = Number(fields[5]), allocatedBytes = Number(fields[6]);
  requireValue(Number.isInteger(allocations) && allocations > 0 && Number.isInteger(allocatedBytes) && allocatedBytes > 0, "frontend-allocation counters are invalid");
  return [allocations, allocatedBytes];
}
export function runOne(binary: string, mode: string, workload: string, jobs: number, lanes: number): RunnerRow {
  const command = ["env", "LC_ALL=C", "/usr/bin/time", "-l", binary, ...runnerArguments(mode, workload, jobs, lanes)]; console.error(`+ ${command.join(" ")}`);
  const completed = run(command); requireValue(completed.exitCode === 0, completed.stderr || `benchmark exited ${completed.exitCode}`);
  const [engine, elapsed_ns, checksum] = parseBenchmark(completed.stdout, mode, workload, lanes, jobs);
  const counters: any = parseDarwinCounters(completed.stdout, mode, workload, jobs), thermal: any = parseDarwinThermalState(completed.stdout, mode, workload, jobs);
  requireValue(counters.instructions.status === "measured" && counters.cycles.status === "measured" && counters.process_energy_nj.status === "measured", "exact-parent Darwin counters are unavailable");
  requireValue(thermal.status === "measured", "exact-parent thermal state is unavailable");
  const allocationCounters = parseFrontendAllocations(completed.stdout, mode, workload, jobs);
  return { engine, mode, workload, lanes, jobs, elapsed_ns, checksum, process_cpu_user_ns: Math.round(timeMetric(completed.stderr, "user") * 1e9), process_cpu_system_ns: Math.round(timeMetric(completed.stderr, "sys") * 1e9), peak_rss_bytes: parsePeakRss(completed.stderr), retained_rss_bytes: mode === "single_observed" ? parseRetainedRss(completed.stdout, mode, workload, jobs) : null, allocations: allocationCounters?.[0] ?? null, allocated_bytes: allocationCounters?.[1] ?? null, instructions: counters.instructions.value, cycles: counters.cycles.value, energy_joules: counters.process_energy_nj.value / 1e9, thermal_state: `${thermal.before}->${thermal.after}` };
}
export function sampleRecord(row: RunnerRow, variant: string, pairSample: number, order: number, schema: any): any {
  const metrics = unavailableMetrics(schema, "instrumentation is not yet connected for this metric; absence is explicit and is not a zero");
  measured(metrics, "wall_time_ns", row.elapsed_ns, "benchmark_runner.elapsed_ns");
  measured(metrics, "process_cpu_user_ns", row.process_cpu_user_ns, "/usr/bin/time -l user");
  measured(metrics, "process_cpu_system_ns", row.process_cpu_system_ns, "/usr/bin/time -l sys");
  measured(metrics, "peak_rss_bytes", row.peak_rss_bytes, "/usr/bin/time -l maximum resident set size");
  if (row.retained_rss_bytes !== null) measured(metrics, "retained_rss_bytes", row.retained_rss_bytes, "task_vm_info.resident_size at the post-invocation live snapshot");
  if (row.allocations !== null) measured(metrics, "allocations", row.allocations, "untimed exact-work parser allocator replay: alloc + resize/remap requests");
  if (row.allocated_bytes !== null) measured(metrics, "allocated_bytes", row.allocated_bytes, "untimed exact-work parser allocator replay: cumulative bytes");
  measured(metrics, "instructions", row.instructions, "proc_pid_rusage(RUSAGE_INFO_V6).ri_instructions delta");
  measured(metrics, "cycles", row.cycles, "proc_pid_rusage(RUSAGE_INFO_V6).ri_cycles delta");
  measured(metrics, "energy_joules", row.energy_joules, "proc_pid_rusage(RUSAGE_INFO_V6).ri_energy_nj delta / 1e9");
  metrics.thermal_state = { status: "measured", value: row.thermal_state, source: "NSProcessInfo.thermalState before->after", reason: "" };
  return { identity: { variant, pair_sample: pairSample, order, engine: row.engine, mode: row.mode, workload: row.workload, lanes: row.lanes, jobs: row.jobs, checksum: row.checksum }, metrics };
}
const mean = (values: number[]): number => values.reduce((sum, value) => sum + value, 0) / values.length;
const median = (values: number[]): number => { const sorted = values.slice().sort((a, b) => a - b), middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; };
export function relativeStddev(values: number[]): number { if (values.length <= 1) return 0; const average = mean(values), variance = values.reduce((sum, value) => sum + (value - average) ** 2, 0) / (values.length - 1); return Math.sqrt(variance) / average; }
function measuredMetricSummary(samples: any[], name: string): any | null { if (!samples.every((sample) => sample.metrics[name]?.status === "measured")) return null; const values: any = {}; for (const variant of ["parent", "candidate"]) values[variant] = samples.filter((sample) => sample.identity.variant === variant).map((sample) => Number(sample.metrics[name].value)); const parentMedian = median(values.parent), candidateMedian = median(values.candidate); return { parent_median: parentMedian, candidate_median: candidateMedian, candidate_over_parent: candidateMedian / parentMedian, parent_rsd: relativeStddev(values.parent), candidate_rsd: relativeStddev(values.candidate) }; }
const MATERIAL_CATEGORIES = ["cpu_work", "threads", "generated_code", "cache_traffic"];
export function summarize(samples: any[], schema: any, hostClass: string, materialCategories: string[] = ["cpu_work"]): any {
  requireValue(materialCategories.length > 0 && materialCategories.every((value) => MATERIAL_CATEGORIES.includes(value)), "invalid material-change category");
  const walls: any = {}; for (const variant of ["parent", "candidate"]) walls[variant] = samples.filter((sample) => sample.identity.variant === variant).map((sample) => Number(sample.metrics.wall_time_ns.value));
  const parentMedian = median(walls.parent), candidateMedian = median(walls.candidate), ratio = candidateMedian / parentMedian, parentRsd = relativeStddev(walls.parent), candidateRsd = relativeStddev(walls.candidate), policy = schema.regression_policy;
  const stable = parentRsd <= policy.maximum_rsd && candidateRsd <= policy.maximum_rsd, gatingHost = hostClass === policy.gate_host_class, regression = ratio > policy.wall_regression_ratio, blocks = gatingHost && stable && regression;
  const efficiency: any = {};
  for (const metric of ["instructions", "cycles", "energy_joules"]) {
    const values: any = {}; for (const variant of ["parent", "candidate"]) values[variant] = samples.filter((sample) => sample.identity.variant === variant).map((sample) => Number(sample.metrics[metric].value));
    efficiency[metric] = { parent_median: median(values.parent), candidate_median: median(values.candidate), candidate_over_parent: median(values.candidate) / median(values.parent), parent_rsd: relativeStddev(values.parent), candidate_rsd: relativeStddev(values.candidate), stable: relativeStddev(values.parent) <= policy.maximum_rsd && relativeStddev(values.candidate) <= policy.maximum_rsd };
  }
  const thermalStates = [...new Set(samples.map((sample) => sample.metrics.thermal_state.value))].sort(), thermalStableNominal = thermalStates.length === 1 && thermalStates[0] === "nominal->nominal";
  const categoryMetrics: Record<string, string[]> = { cpu_work: [], threads: [], generated_code: ["generated_code_bytes"], cache_traffic: ["cache_misses"] }, unmetMetrics: string[] = [];
  for (const name of [...new Set(materialCategories.flatMap((category) => categoryMetrics[category]))]) {
    const observations = samples.map((sample) => sample.metrics[name]);
    if (!observations.every((value) => value.status === "measured") || !["parent", "candidate"].every((variant) => relativeStddev(samples.filter((sample) => sample.identity.variant === variant).map((sample) => Number(sample.metrics[name].value))) <= policy.maximum_rsd)) unmetMetrics.push(name);
  }
  const efficiencyStable = Object.values(efficiency).every((metric: any) => metric.stable) && thermalStableNominal && unmetMetrics.length === 0;
  const efficiencyBlocks = gatingHost && !efficiencyStable, blocksPublication = blocks || efficiencyBlocks;
  const status = blocks ? "blocked_regression" : efficiencyBlocks ? "blocked_efficiency_evidence" : !gatingHost ? "diagnostic_only" : !stable ? "inconclusive_noise" : regression ? "visible_non_gating_regression" : "pass";
  return { parent_wall_median_ns: parentMedian, candidate_wall_median_ns: candidateMedian, candidate_over_parent: ratio, parent_wall_rsd: parentRsd, candidate_wall_rsd: candidateRsd, stable, gating_host: gatingHost, regression, efficiency: { metrics: efficiency, thermal_states: thermalStates, required_categories: materialCategories, unmet_metrics: unmetMetrics, stable: efficiencyStable, blocks_publication: efficiencyBlocks }, blocks_publication: blocksPublication, status };
}
export function collect(parentBinary: string, candidateBinary: string, mode: string, workload: string, jobs: number, lanes: number, expectedChecksum: number, samples: number, schema: any): any[] { const binaries: any = { parent: parentBinary, candidate: candidateBinary }, result: any[] = []; for (let pairSample = 0; pairSample < samples; pairSample += 1) { const order = pairSample % 2 === 0 ? ["parent", "candidate"] : ["candidate", "parent"]; order.forEach((variant, position) => { const row = runOne(binaries[variant], mode, workload, jobs, lanes); requireValue(row.checksum === expectedChecksum, `${variant} pair ${pairSample} checksum ${row.checksum} != frozen ${expectedChecksum}`); result.push(sampleRecord(row, variant, pairSample, position, schema)); }); } return result; }
export function render(artifact: any): string { const metadata = artifact.metadata, summary = artifact.summary, efficiency = summary.efficiency, memoryRows = ["peak_rss_bytes", "retained_rss_bytes", "allocations", "allocated_bytes"].map((metric) => [metric, measuredMetricSummary(artifact.samples, metric)] as const).filter((entry) => entry[1] !== null).map(([metric, value]) => `| \`${metric}\` | ${value.parent_median} | ${value.candidate_median} | ${value.candidate_over_parent.toFixed(4)}x | ${(value.parent_rsd * 100).toFixed(2)}% | ${(value.candidate_rsd * 100).toFixed(2)}% |`); return [`# Exact-parent performance A/B — ${metadata.workload} (${metadata.mode}, ${metadata.lanes} lane(s))`, "", `- parent: \`${metadata.parent_revision}\``, `- candidate: \`${metadata.candidate_revision}\``, `- zig-gc: \`${metadata.zig_gc_revision}\``, `- zig-regex: \`${metadata.zig_regex_revision}\``, `- host class: \`${metadata.host_class}\``, `- material-change categories: ${efficiency.required_categories.map((value: string) => `\`${value}\``).join(", ")}`, `- sampling: ${metadata.samples} order-balanced pairs; no discarded samples`, `- timed boundary: ${metadata.timed_boundary}`, "", "| parent median | candidate median | candidate / parent | parent RSD | candidate RSD | assessment |", "| ---: | ---: | ---: | ---: | ---: | --- |", `| ${(summary.parent_wall_median_ns / 1e6).toFixed(3)} ms | ${(summary.candidate_wall_median_ns / 1e6).toFixed(3)} ms | ${summary.candidate_over_parent.toFixed(3)}x | ${(summary.parent_wall_rsd * 100).toFixed(2)}% | ${(summary.candidate_wall_rsd * 100).toFixed(2)}% | \`${summary.status}\` |`, "", "| memory/allocation metric | parent median | candidate median | candidate / parent | parent RSD | candidate RSD |", "| --- | ---: | ---: | ---: | ---: | ---: |", ...memoryRows, "", "| efficiency metric | parent median | candidate median | candidate / parent | parent RSD | candidate RSD |", "| --- | ---: | ---: | ---: | ---: | ---: |", ...["instructions", "cycles", "energy_joules"].map((metric) => { const value = efficiency.metrics[metric]; return `| \`${metric}\` | ${value.parent_median} | ${value.candidate_median} | ${value.candidate_over_parent.toFixed(4)}x | ${(value.parent_rsd * 100).toFixed(2)}% | ${(value.candidate_rsd * 100).toFixed(2)}% |`; }), ``, `Thermal states: ${efficiency.thermal_states.map((value: string) => `\`${value}\``).join(", ")}. Unmet category metrics: ${efficiency.unmet_metrics.length ? efficiency.unmet_metrics.map((value: string) => `\`${value}\``).join(", ") : "none"}. Efficiency evidence: \`${efficiency.stable ? "stable" : "blocked_or_diagnostic"}\`.`, "", "All input identities and checksums matched. Missing attribution values are encoded as unavailable with a reason, never as zero.", ""].join("\n"); }

function syntheticSamples(parent: number[], candidate: number[], schema: any): any[] { const result: any[] = []; parent.forEach((parentWall, pairSample) => { const walls: any = { parent: parentWall, candidate: candidate[pairSample] }, order = pairSample % 2 === 0 ? ["parent", "candidate"] : ["candidate", "parent"]; order.forEach((variant, position) => result.push(sampleRecord({ engine: "zig-js", mode: "single", workload: "representative_json", lanes: 1, jobs: 2200, elapsed_ns: walls[variant], checksum: 324952086, process_cpu_user_ns: Math.max(0, walls[variant] - 100), process_cpu_system_ns: 100, peak_rss_bytes: 10000000, retained_rss_bytes: null, allocations: null, allocated_bytes: null, instructions: 1000 + pairSample, cycles: 500 + pairSample, energy_joules: 0.2 + pairSample / 1000, thermal_state: "nominal->nominal" }, variant, pairSample, position, schema))); }); return result; }
function expectFailure(action: () => void, pattern: string): void { try { action(); } catch (error) { requireValue(String(error).includes(pattern), `expected ${pattern}, got ${String(error)}`); return; } throw new Error(`expected failure containing ${pattern}`); }
export function selfTest(): void {
  const schema = loadSchema();
  const stdout = "zig-js\tsingle\trepresentative_json\t1\t2200\t0\t60000000\t324952086\n"; requireValue(JSON.stringify(parseBenchmark(stdout, "single", "representative_json", 1, 2200)) === JSON.stringify(["zig-js", 60000000, 324952086]), "runner row parse drift"); expectFailure(() => parseBenchmark(stdout, "single", "representative_regexp", 1, 2200), "identity drift");
  const native = "zig-js-native-observability\tsingle_observed\trepresentative_json\t2200\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t12000000\t11000000\n"; requireValue(parseRetainedRss(native, "single_observed", "representative_json", 2200) === 11000000, "retained RSS row parse drift"); expectFailure(() => parseRetainedRss(native, "single_observed", "representative_regexp", 2200), "identity drift");
  const frontend = "zig-js-frontend-allocations\tsingle\trepresentative_frontend_numeric_separators_1024\t10\t0\t123\t456\n"; requireValue(JSON.stringify(parseFrontendAllocations(frontend, "single", "representative_frontend_numeric_separators_1024", 10)) === "[123,456]", "frontend allocation parse drift"); expectFailure(() => parseFrontendAllocations(frontend, "single", "representative_frontend_numeric_separators_2048", 10), "identity drift");
  const observedArguments = runnerArguments("single_observed", "representative_json", 2200, 1); requireValue(observedArguments[observedArguments.length - 1] === "--native-observability-telemetry", "single_observed telemetry option drift");
  const timing = "        0.13 real         0.07 user         0.02 sys\n            91750400  maximum resident set size\n"; requireValue(timeMetric(timing, "user") === 0.07 && timeMetric(timing, "sys") === 0.02 && parsePeakRss(timing) === 91750400, "macOS time layout parse drift");
  const stable = syntheticSamples([100, 101, 99, 100], [112, 113, 111, 112], schema); requireValue(summarize(stable, schema, "quiet_reference").status === "blocked_regression", "stable regression must block"); requireValue(summarize(stable, schema, "diagnostic").status === "diagnostic_only", "diagnostic host must not block"); const noisy = syntheticSamples([100, 130, 70, 100], [150, 90, 130, 110], schema); requireValue(summarize(noisy, schema, "quiet_reference").status === "inconclusive_noise", "noisy reference must be inconclusive");
  const thermalDrift = syntheticSamples([100, 101], [99, 100], schema); thermalDrift[0].metrics.thermal_state.value = "nominal->fair"; requireValue(summarize(thermalDrift, schema, "quiet_reference").status === "blocked_efficiency_evidence", "thermal drift must block reference publication"); requireValue(summarize(thermalDrift, schema, "diagnostic").status === "diagnostic_only", "thermal drift must remain diagnostic off reference hosts");
  const cacheRequired = summarize(syntheticSamples([100, 101], [99, 100], schema), schema, "quiet_reference", ["cache_traffic"]); requireValue(cacheRequired.status === "blocked_efficiency_evidence" && JSON.stringify(cacheRequired.efficiency.unmet_metrics) === '["cache_misses"]', "unavailable cache evidence must block a cache-traffic publication");
  const samples = syntheticSamples([100, 101], [99, 100], schema), metadata: any = {}; for (const field of schema.required_metadata) metadata[field] = "test"; Object.assign(metadata, { parent_revision: "a".repeat(40), candidate_revision: "b".repeat(40), candidate_first_parent: "a".repeat(40), zig_gc_revision: "c".repeat(40), zig_regex_revision: "d".repeat(40), workload_source_sha256: "1".repeat(64), parent_binary_sha256: "2".repeat(64), candidate_binary_sha256: "3".repeat(64), host_class: "diagnostic", material_change_categories: ["cpu_work"], mode: "single", workload: "representative_json", lanes: 1, jobs: 2200, expected_checksum: 324952086, samples: 2, timed_boundary: "test boundary" }); validateArtifact({ schema_version: schema.schema_version, profile_id: schema.profile_id, kind: "exact_parent_ab", metadata, samples, summary: summarize(samples, schema, "diagnostic") }, schema);
  const directory = temporaryDirectory("zig-js-exact-parent"); try { checked(["git", "init", "-q", directory], "initialize clean-worktree fixture"); checked(["git", "-C", directory, "config", "user.name", "Test"], "configure fixture name"); checked(["git", "-C", directory, "config", "user.email", "test@example.com"], "configure fixture email"); const tracked = `${directory}/tracked.txt`; for (let commit = 0; commit < 3; commit += 1) { writeText(tracked, `fixture ${commit}\n`); checked(["git", "-C", directory, "add", "tracked.txt"], "stage fixture"); checked(["git", "-C", directory, "commit", "-qm", `fixture ${commit}`], "commit fixture"); } const head = resolveRevision("HEAD", directory), parent = resolveRevision("HEAD^1", directory); requireValue(JSON.stringify(validateExactParent(parent, head, directory)) === JSON.stringify([parent, head]), "fixture exact parent did not validate"); expectFailure(() => validateExactParent(resolveRevision("HEAD~2", directory), head, directory), "not requested exact parent"); requireClean(directory); writeText(tracked, "dirty\n"); expectFailure(() => requireClean(directory), "dirty tracked worktree"); } finally { removeTemporaryDirectory(directory); }
  console.log("OK exact-parent self-test: identity, pairing, regression, and cleanliness gates verified");
}

function main(): void {
  const raw = process.argv.slice(2); if (raw.length === 1 && raw[0] === "--self-test") { selfTest(); return; }
  const positional: string[] = [], options: any = { candidate_revision: "HEAD", lanes: 1, samples: 7, host_class: "diagnostic", schema: DEFAULT_SCHEMA };
  const names: any = { "--parent-revision": "parent_revision", "--candidate-revision": "candidate_revision", "--source": "source", "--mode": "mode", "--workload": "workload", "--jobs": "jobs", "--lanes": "lanes", "--expected-checksum": "expected_checksum", "--samples": "samples", "--host-class": "host_class", "--material-change": "material_change", "--timed-boundary": "timed_boundary", "--schema": "schema", "--raw-out": "raw_out", "--markdown-out": "markdown_out" };
  for (let index = 0; index < raw.length; index += 1) { if (!raw[index].startsWith("--")) positional.push(raw[index]); else { requireValue(names[raw[index]] && index + 1 < raw.length, `unknown or incomplete argument: ${raw[index]}`); const key = names[raw[index]], value = raw[++index]; options[key] = ["jobs", "lanes", "expected_checksum", "samples"].includes(key) ? Number(value) : value; } }
  requireValue(positional.length === 2, "usage: exact-parent-regression.ts PARENT_RUNNER CANDIDATE_RUNNER [options]"); for (const field of ["parent_revision", "source", "mode", "workload", "jobs", "expected_checksum", "timed_boundary", "raw_out", "markdown_out"]) requireValue(options[field] !== undefined, `missing required option: ${field}`);
  requireValue(options.samples >= 2 && options.jobs > 0 && options.lanes > 0 && options.expected_checksum >= 0, "samples must be >=2; jobs/lanes positive; checksum non-negative"); for (const path of [positional[0], positional[1], options.source]) requireValue(Home.fileExists(path), `input does not exist: ${path}`);
  const materialCategories = options.material_change ? String(options.material_change).split(",").filter(Boolean) : ["cpu_work", ...(["independent_steady", "independent_cold", "shared"].includes(options.mode) ? ["threads"] : [])];
  requireValue(materialCategories.length > 0 && materialCategories.every((value: string) => MATERIAL_CATEGORIES.includes(value)) && new Set(materialCategories).size === materialCategories.length, `material-change categories must be unique values from ${MATERIAL_CATEGORIES.join(",")}`);
  const schema = loadSchema(options.schema), [parentRevision, candidateRevision] = validateExactParent(options.parent_revision, options.candidate_revision); for (const repository of [ROOT, `${ROOT}/../zig-gc`, `${ROOT}/../zig-regex`]) requireClean(repository);
  const samples = collect(positional[0], positional[1], options.mode, options.workload, options.jobs, options.lanes, options.expected_checksum, options.samples, schema), metadata = { parent_revision: parentRevision, candidate_revision: candidateRevision, candidate_first_parent: resolveRevision(`${candidateRevision}^1`), zig_gc_revision: repositoryRevision(`${ROOT}/../zig-gc`), zig_regex_revision: repositoryRevision(`${ROOT}/../zig-regex`), zig_version: commandOutput(["zig", "version"]), os: commandOutput(["uname", "-a"]), hardware: `${commandOutput(["uname", "-m"])}; ${commandOutput(["sysctl", "-n", "machdep.cpu.brand_string"])}`, power: commandOutput(["pmset", "-g", "batt"], "unavailable").split(/\s+/).join(" "), host_class: options.host_class, material_change_categories: materialCategories, workload_source_sha256: sha256File(options.source), parent_binary_sha256: sha256File(positional[0]), candidate_binary_sha256: sha256File(positional[1]), samples: options.samples, timed_boundary: options.timed_boundary, mode: options.mode, workload: options.workload, lanes: options.lanes, jobs: options.jobs, expected_checksum: options.expected_checksum };
  const artifact = { schema_version: schema.schema_version, profile_id: schema.profile_id, kind: "exact_parent_ab", metadata, samples, summary: summarize(samples, schema, options.host_class, materialCategories) }; validateArtifact(artifact, schema); checked(["mkdir", "-p", options.raw_out.slice(0, options.raw_out.lastIndexOf("/")) || ".", options.markdown_out.slice(0, options.markdown_out.lastIndexOf("/")) || "."], "create exact-parent output directories"); writeText(options.raw_out, JSON.stringify(artifact, null, 2) + "\n"); writeText(options.markdown_out, render(artifact)); if (artifact.summary.blocks_publication) throw new Error(`reference-host publication blocked: ${artifact.summary.status}`);
}
if (process.argv[1] === __filename) main();
