// Generate src/cldr_tzalias.zig from CLDR's cldr-bcp47/bcp47/timezone.json.
// Maps a deprecated/alias `-u-tz-` keyword value (lowercased) to its canonical
// BCP-47 time-zone type, used by Intl locale canonicalization. Only alias
// tokens that are valid BCP-47 type subtags (lowercase alphanumerics, no "/")
// are kept; full IANA names can never appear as a -u-tz value.
//
//   node tools/gen_cldr_tzalias.mjs /tmp/tz.json > src/cldr_tzalias.zig
import { readFileSync } from "node:fs";

const tz = JSON.parse(readFileSync(process.argv[2] || "/tmp/tz.json", "utf8")).keyword.u.tz;

const map = new Map();
for (const [name, v] of Object.entries(tz)) {
  if (name.startsWith("_")) continue;
  const canon = (v._preferred || name).toLowerCase();
  if (name.toLowerCase() !== canon) map.set(name.toLowerCase(), canon);
  for (const al of (v._alias || "").split(/\s+/).filter(Boolean)) {
    const lc = al.toLowerCase();
    if (lc !== canon && /^[a-z0-9]{1,8}$/.test(lc)) map.set(lc, canon);
  }
}

const rows = [...map.entries()].sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));

let out = `// GENERATED by tools/gen_cldr_tzalias.mjs from CLDR bcp47/timezone.json.
// Deprecated/alias -u-tz- value (lowercased) -> canonical BCP-47 tz type.
const std = @import("std");

const Row = struct { k: []const u8, v: []const u8 };
const rows = [_]Row{
`;
for (const [k, v] of rows) out += `    .{ .k = "${k}", .v = "${v}" },\n`;
out += `};

/// The canonical BCP-47 time-zone type for a -u-tz- value (lowercased), or null.
pub fn canonical(value: []const u8) ?[]const u8 {
    var lo: usize = 0;
    var hi: usize = rows.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, rows[mid].k, value)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return rows[mid].v,
        }
    }
    return null;
}
`;
process.stdout.write(out);
