// Generate src/iana_offsets.zig — per-zone UTC-offset transition tables for
// Temporal / Intl time-zone math — from the system tzdata via `zdump -v`.
//
//   node tools/gen_iana_offsets.mjs /tmp/zones.txt > src/iana_offsets.zig
//
// Each `zdump -v <zone>` line gives an instant (in UT) and the offset in effect
// then (`gmtoff=<seconds>`). We sort those, keep only the points where the
// offset changes (the transitions), clamp to a [1900, 2101) window (all realistic
// test dates; the pre-window offset becomes the initial entry), and emit two flat
// parallel arrays (`trans_at` / `trans_off`) with a per-zone `[start, start+len)`
// window plus binary-search lookups. Flat integer arrays compile far faster than
// nested slice-of-struct literals for a table this size.
import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";

const zones = readFileSync(process.argv[2] || "/tmp/zones.txt", "utf8")
  .split("\n").map((s) => s.trim()).filter(Boolean);

const MON = { Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5, Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11 };
const WIN_LO = Date.UTC(1900, 0, 1) / 1000;
const WIN_HI = Date.UTC(2101, 0, 1) / 1000;

const emitted = [];
for (const z of zones) {
  let dump;
  try {
    dump = execSync(`zdump -v ${z}`, { encoding: "utf8", maxBuffer: 1 << 28 });
  } catch {
    continue;
  }
  const pts = [];
  for (const line of dump.split("\n")) {
    const g = line.match(/gmtoff=(-?\d+)/);
    const d = line.match(/\s\w{3}\s+(\w{3})\s+(\d+)\s+(\d+):(\d+):(\d+)\s+(-?\d+)\s+UT\b/);
    if (!g || !d) continue;
    const ep = Date.UTC(+d[6], MON[d[1]], +d[2], +d[3], +d[4], +d[5]) / 1000;
    if (!Number.isFinite(ep)) continue;
    pts.push([ep, +g[1]]);
  }
  pts.sort((a, b) => a[0] - b[0]);
  const trans = [];
  let last = null;
  for (const [ep, off] of pts) {
    if (off !== last) { trans.push([ep, off]); last = off; }
  }
  let init = null;
  const inside = [];
  for (const t of trans) {
    if (t[0] <= WIN_LO) init = [WIN_LO, t[1]];
    else if (t[0] < WIN_HI) inside.push(t);
  }
  const rows = [];
  if (init) rows.push(init);
  else if (trans.length) rows.push([WIN_LO, trans[0][1]]);
  rows.push(...inside);
  if (rows.length) emitted.push([z, rows]);
}

// Flatten into parallel integer arrays + a per-zone [start, len) index.
const flatAt = [];
const flatOff = [];
const idx = [];
for (const [name, rows] of emitted) {
  const start = flatAt.length;
  for (const [at, off] of rows) { flatAt.push(at); flatOff.push(off); }
  idx.push([name, start, rows.length]);
}

const chunk = (arr) => {
  let s = "";
  for (let i = 0; i < arr.length; i += 20) s += "    " + arr.slice(i, i + 20).join(", ") + ",\n";
  return s;
};

let out = `//! GENERATED by tools/gen_iana_offsets.mjs from the system tzdata (\`zdump -v\`).
//! Per-zone UTC-offset transitions (epoch seconds -> offset seconds), sorted,
//! clamped to [1900, 2101). Backs Temporal / Intl time-zone resolution.
//!
//! Stored as two flat parallel arrays with a per-zone [start, start+len) window
//! rather than nested slice literals, so the large table compiles quickly.
const std = @import("std");

pub const Zone = struct { name: []const u8, start: u32, len: u32 };

pub const zones = [_]Zone{
`;
for (const [name, start, len] of idx) out += `    .{ .name = "${name}", .start = ${start}, .len = ${len} },\n`;
out += `};

const trans_at = [_]i64{
${chunk(flatAt)}};

const trans_off = [_]i32{
${chunk(flatOff)}};

fn find(name: []const u8) ?Zone {
    for (zones) |z| {
        if (std.mem.eql(u8, z.name, name)) return z;
    }
    return null;
}

/// The UTC offset (seconds) for canonical zone \`name\` at \`epoch_s\`, or null if
/// the zone is not tabulated. Binary-searches the zone's window for the latest
/// transition at or before \`epoch_s\`.
pub fn offsetAt(name: []const u8, epoch_s: i64) ?i32 {
    const z = find(name) orelse return null;
    if (z.len == 0) return null;
    const at = trans_at[z.start .. z.start + z.len];
    var lo: usize = 0;
    var hi: usize = at.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (at[mid] <= epoch_s) lo = mid + 1 else hi = mid;
    }
    const off = if (lo == 0) 0 else lo - 1;
    return trans_off[z.start + off];
}

/// The next (\`next\`) or previous transition instant (epoch seconds) for canonical
/// zone \`name\` relative to \`epoch_s\`, or null. Index 0 is the synthetic
/// window-clamped initial entry (not a real transition) and is skipped.
pub fn transitionAt(name: []const u8, epoch_s: i64, next: bool) ?i64 {
    const z = find(name) orelse return null;
    if (z.len <= 1) return null;
    const at = trans_at[z.start .. z.start + z.len];
    if (next) {
        for (at[1..]) |t| {
            if (t > epoch_s) return t;
        }
        return null;
    }
    var i: usize = at.len;
    while (i > 1) {
        i -= 1;
        if (at[i] < epoch_s) return at[i];
    }
    return null;
}
`;
process.stdout.write(out);
