#!/usr/bin/env python3
"""Generate src/encoding_multibyte_data.zig — the WHATWG multi-byte decoder index
tables (jis0208, jis0212, big5, euc-kr, gb18030 pointer→code-point maps, plus the
gb18030 4-byte range pairs). Fetch first:
  curl -s https://encoding.spec.whatwg.org/indexes.json -o /tmp/enc-indexes.json
Validate the decoders against node afterward (node/ICU can deviate from these).
"""
import json

idx = json.load(open('/tmp/enc-indexes.json'))
OUT = 'src/encoding_multibyte_data.zig'

# 0 marks "no mapping" (no index entry maps to U+0000). Only gb18030 is used —
# node/ICU's big5/euc-kr/shift_jis(jis0208)/euc-jp(jis0212) deviate from these
# WHATWG tables by thousands of entries, so those encodings stay unsupported.
TABLES = ['gb18030']

def zigname(n):
    return n.replace('-', '_')

with open(OUT, 'w') as f:
    f.write('//! GENERATED by tools/gen_multibyte.py from the WHATWG Encoding indexes.\n')
    f.write('//! Multi-byte decoder pointer→code-point tables (0 = no mapping). Do not edit.\n\n')
    for name in TABLES:
        arr = idx[name]
        entries = [c if c is not None else 0 for c in arr]
        f.write(f'pub const {zigname(name)} = [{len(entries)}]u21{{\n')
        for i in range(0, len(entries), 16):
            f.write('    ' + ', '.join(f'0x{c:X}' for c in entries[i:i + 16]) + ',\n')
        f.write('};\n')
    # gb18030 4-byte ranges: sorted (pointer, code point) pairs.
    ranges = idx['gb18030-ranges']
    f.write('\npub const Gb18030Range = struct { ptr: u32, cp: u32 };\n')
    f.write(f'// {len(ranges)} range anchors for the gb18030 four-byte decoder.\n')
    f.write('pub const gb18030_ranges = [_]Gb18030Range{\n')
    for ptr, cp in ranges:
        f.write(f'    .{{ .ptr = {ptr}, .cp = 0x{cp:X} }},\n')
    f.write('};\n')

print(f'wrote {OUT}: ' + ', '.join(f'{n}={len(idx[n])}' for n in TABLES) +
      f', gb18030-ranges={len(idx["gb18030-ranges"])}')
