/** Generate UTS-46 IDNA and label-validity tables. */
import { readText, writeText } from "./lib/home";

type Entry = [number, number, string, number, number];
type Range = [number, number, string];
const args = process.argv.slice(2);
const mappingPath = args[0] || "/tmp/idnamap.txt", ucdPath = args[1] || "/tmp/ucd.txt", joiningPath = args[2] || "/tmp/jt.txt", bidiPath = args[3] || "/tmp/bidi.txt", output = args[4] || "src/unicode_idna_data.zig";
const entries: Entry[] = [], mapData: number[] = [], mapIndex: Record<string, number> = {};
function addMap(values: number[]): number { const key = values.join(","); if (mapIndex[key] != null) return mapIndex[key]; const offset = mapData.length; mapData.push(...values); mapIndex[key] = offset; return offset; }
for (const raw of readText(mappingPath).split("\n")) {
  const line = raw.split("#")[0].trim(); if (!line) continue;
  const parts = line.split(";").map(value => value.trim()), bounds = parts[0].split("..");
  const low = Number.parseInt(bounds[0], 16), high = Number.parseInt(bounds[1] || bounds[0], 16), status = parts[1] || "";
  if (["valid", "deviation", "disallowed_STD3_valid"].indexOf(status) >= 0) continue;
  if (status === "mapped" || status === "disallowed_STD3_mapped") {
    const target = parts[2] ? parts[2].split(/\s+/).map(value => Number.parseInt(value, 16)) : [];
    if (!target.length) continue;
    entries.push([low, high, "mapped", addMap(target), target.length]);
  } else if (status === "ignored" || status === "disallowed") entries.push([low, high, status, 0, 0]);
  else throw new Error(`unknown status: '${status}' on ${line}`);
}
entries.sort((a, b) => a[0] - b[0] || a[1] - b[1]);
const merged: Entry[] = [];
for (const entry of entries) { const prior = merged[merged.length - 1]; if (prior && prior[2] === entry[2] && (entry[2] === "ignored" || entry[2] === "disallowed") && entry[0] === prior[1] + 1) prior[1] = entry[1]; else merged.push(entry.slice() as Entry); }
const marks: number[] = [], virama: number[] = []; let pending: [number, string, string] | null = null;
for (const raw of readText(ucdPath).split("\n")) {
  const fields = raw.replace(/\r$/, "").split(";"); if (fields.length < 4) continue;
  const point = Number.parseInt(fields[0], 16), name = fields[1], category = fields[2], combining = fields[3];
  if (name.endsWith(", First>")) { pending = [point, category, combining]; continue; }
  if (name.endsWith(", Last>") && pending) { for (let value = pending[0]; value <= point; value += 1) { if (["Mn", "Mc", "Me"].indexOf(pending[1]) >= 0) marks.push(value); if (pending[2] === "9") virama.push(value); } pending = null; continue; }
  if (["Mn", "Mc", "Me"].indexOf(category) >= 0) marks.push(point); if (combining === "9") virama.push(point);
}
function coalesce(points: number[]): number[][] { const unique = Array.from(new Set(points)).sort((a, b) => a - b), rows: number[][] = []; for (const point of unique) { const prior = rows[rows.length - 1]; if (prior && point === prior[1] + 1) prior[1] = point; else rows.push([point, point]); } return rows; }
const bidiMap: Record<string, string> = { R: "r", AL: "al", AN: "an", EN: "en", ES: "es", CS: "cs", ET: "et", ON: "on", BN: "bn", NSM: "nsm" }, bidiRaw: Range[] = [];
for (const raw of readText(bidiPath).split("\n")) { const line = raw.split("#")[0].trim(); if (!line) continue; const parts = line.split(";").map(value => value.trim()); if (parts[1] === "L") continue; const bounds = parts[0].split(".."); bidiRaw.push([Number.parseInt(bounds[0], 16), Number.parseInt(bounds[1] || bounds[0], 16), bidiMap[parts[1]] || "other"]); }
bidiRaw.sort((a, b) => a[0] - b[0]); const bidi: Range[] = [];
for (const row of bidiRaw) { const prior = bidi[bidi.length - 1]; if (prior && prior[2] === row[2] && row[0] === prior[1] + 1) prior[1] = row[1]; else bidi.push(row.slice() as Range); }
const joiningMap: Record<string, string> = { L: "l", R: "r", D: "d", T: "t" }, joining: Range[] = [];
for (const raw of readText(joiningPath).split("\n")) { const line = raw.split("#")[0].trim(); if (!line) continue; const parts = line.split(";").map(value => value.trim()); if (!joiningMap[parts[1]]) continue; const bounds = parts[0].split(".."); joining.push([Number.parseInt(bounds[0], 16), Number.parseInt(bounds[1] || bounds[0], 16), joiningMap[parts[1]]]); }
joining.sort((a, b) => a[0] - b[0]); const markRanges = coalesce(marks), viramaValues = Array.from(new Set(virama)).sort((a, b) => a - b), hex = (value: number) => value.toString(16).toUpperCase();
const out = ["//! GENERATED by tools/gen_idna.ts from the UTS-46 IdnaMappingTable.", "//! Non-transitional, UseSTD3ASCIIRules=false. Do not edit by hand.", "", "pub const Action = enum(u8) { mapped, disallowed, ignored };", "", "pub const Entry = struct { lo: u21, hi: u21, action: Action, off: u32, len: u16 };", "", `// ${merged.length} ranges; any code point not covered is \"valid\" (kept as-is).`, "pub const entries = [_]Entry{"];
for (const row of merged) out.push(`    .{ .lo = 0x${hex(row[0])}, .hi = 0x${hex(row[1])}, .action = .${row[2]}, .off = ${row[3]}, .len = ${row[4]} },`);
out.push("};", "", `// ${mapData.length} target code points, referenced by mapped entries.`, "pub const map_data = [_]u21{");
for (let index = 0; index < mapData.length; index += 16) out.push("    " + mapData.slice(index, index + 16).map(value => "0x" + hex(value)).join(", ") + ",");
out.push("};", "", "pub const Range = struct { lo: u21, hi: u21 };", "", `// ${markRanges.length} GC=Mark ranges (Mn/Mc/Me): a label may not begin with one.`, "pub const mark_ranges = [_]Range{");
for (const row of markRanges) out.push(`    .{ .lo = 0x${hex(row[0])}, .hi = 0x${hex(row[1])} },`);
out.push("};", "", "pub const JoinType = enum(u8) { l, r, d, t };", "pub const JoinRange = struct { lo: u21, hi: u21, jt: JoinType };", "", `// ${joining.length} Joining_Type ranges (L/R/D/T) for CheckJoiners.`, "pub const join_ranges = [_]JoinRange{");
for (const row of joining) out.push(`    .{ .lo = 0x${hex(row[0])}, .hi = 0x${hex(row[1])}, .jt = .${row[2]} },`);
out.push("};", "", `// ${viramaValues.length} virama (CCC==9) code points for CheckJoiners.`, "pub const virama = [_]u21{");
for (let index = 0; index < viramaValues.length; index += 12) out.push("    " + viramaValues.slice(index, index + 12).map(value => "0x" + hex(value)).join(", ") + ",");
out.push("};", "", "pub const BidiClass = enum(u8) { l, r, al, an, en, es, cs, et, on, bn, nsm, other };", "pub const BidiRange = struct { lo: u21, hi: u21, bc: BidiClass };", "", `// ${bidi.length} Bidi_Class ranges (non-L; unlisted defaults to .l) for CheckBidi.`, "pub const bidi_ranges = [_]BidiRange{");
for (const row of bidi) out.push(`    .{ .lo = 0x${hex(row[0])}, .hi = 0x${hex(row[1])}, .bc = .${row[2]} },`); out.push("};", "");
writeText(output, out.join("\n"));
console.log(`wrote ${output}: ${merged.length} entries, ${mapData.length} map cps, ${markRanges.length} mark ranges, ${joining.length} join ranges, ${viramaValues.length} virama, ${bidi.length} bidi ranges`);
