// Generate src/numbering_systems.zig from test262's numberingSystemDigits table
// (harness/testIntl.js) — the authoritative digit set the tests use, so our
// output bytes match theirs exactly. Run: node tools/gen_numbering.mjs
import { readFileSync } from "node:fs";
const src = readFileSync(process.argv[2] || "test262/harness/testIntl.js", "utf8");
const m = src.match(/var numberingSystemDigits = \{([\s\S]*?)\n\};/);
if (!m) throw new Error("numberingSystemDigits not found");
// Evaluate the object literal body safely.
const obj = Function(`"use strict"; return {${m[1]}};`)();

function zstr(s) {
  const bytes = Buffer.from(s, "utf8");
  let out = '"';
  for (const b of bytes) {
    if (b === 0x22) out += '\\"';
    else if (b === 0x5c) out += "\\\\";
    else if (b >= 0x20 && b < 0x7f) out += String.fromCharCode(b);
    else out += "\\x" + b.toString(16).padStart(2, "0");
  }
  return out + '"';
}

let out = `// GENERATED by tools/gen_numbering.mjs from test262 harness/testIntl.js.
// Each value is the system's ten digits (0-9) concatenated; within a system all
// digits have the same byte width, so the i-th digit is a fixed-width slice.
const std = @import("std");

const Row = struct { name: []const u8, digits: []const u8 };
const table = [_]Row{
`;
for (const [name, digits] of Object.entries(obj)) {
  // sanity: exactly 10 code points
  const cps = [...digits];
  if (cps.length !== 10) { process.stderr.write(`skip ${name}: ${cps.length} cps\\n`); continue; }
  out += `    .{ .name = ${zstr(name)}, .digits = ${zstr(digits)} },\n`;
}
out += `};

/// The ten-digit string for a numbering system, or null if unknown/unsupported.
pub fn digits(name: []const u8) ?[]const u8 {
    for (table) |row| if (std.mem.eql(u8, row.name, name)) return row.digits;
    return null;
}

/// The UTF-8 bytes of digit \`d\` (0-9) in \`ds\` (a value returned by digits()).
pub fn nth(ds: []const u8, d: u8) []const u8 {
    const w = ds.len / 10;
    return ds[d * w .. (d + 1) * w];
}
`;
process.stdout.write(out);
