/** Generate WHATWG multi-byte decoder tables. */
import { readText, writeText } from "./lib/home";

const input = process.argv[2] || "/tmp/enc-indexes.json";
const output = process.argv[3] || "src/encoding_multibyte_data.zig";
const indexes = JSON.parse(readText(input));
const tables = ["gb18030"];
const lines = [
  "//! GENERATED by tools/gen_multibyte.ts from the WHATWG Encoding indexes.",
  "//! Multi-byte decoder pointer→code-point tables (0 = no mapping). Do not edit.", "",
];
for (const name of tables) {
  const entries = indexes[name].map((value: number | null) => value == null ? 0 : value);
  lines.push(`pub const ${name.replace(/-/g, "_")} = [${entries.length}]u21{`);
  for (let index = 0; index < entries.length; index += 16) {
    lines.push("    " + entries.slice(index, index + 16).map((value: number) => "0x" + value.toString(16).toUpperCase()).join(", ") + ",");
  }
  lines.push("};");
}
const ranges = indexes["gb18030-ranges"];
lines.push("", "pub const Gb18030Range = struct { ptr: u32, cp: u32 };", `// ${ranges.length} range anchors for the gb18030 four-byte decoder.`, "pub const gb18030_ranges = [_]Gb18030Range{");
for (const pair of ranges) lines.push(`    .{ .ptr = ${pair[0]}, .cp = 0x${pair[1].toString(16).toUpperCase()} },`);
lines.push("};", "");
writeText(output, lines.join("\n"));
console.log(`wrote ${output}: ${tables.map(name => `${name}=${indexes[name].length}`).join(", ")}, gb18030-ranges=${ranges.length}`);
