// Generate src/cldr_plurals.zig from CLDR plurals.json (cardinal) and
// ordinals.json. Each locale maps to an ordered list of (category, condition)
// rules (the rule string with its @integer/@decimal samples stripped). Rulesets
// are deduped; locales are looked up by language subtag via binary search.
//
//   node tools/gen_cldr_plurals.mjs /tmp/plurals.json /tmp/ordinals.json > src/cldr_plurals.zig
import { readFileSync } from "node:fs";

const cardinal = JSON.parse(readFileSync(process.argv[2] || "/tmp/plurals.json", "utf8")).supplemental["plurals-type-cardinal"];
const ordinal = JSON.parse(readFileSync(process.argv[3] || "/tmp/ordinals.json", "utf8")).supplemental["plurals-type-ordinal"];

const CATS = ["zero", "one", "two", "few", "many", "other"];

function zstr(s) {
  let out = '"';
  for (const b of Buffer.from(s, "utf8")) {
    if (b === 0x22) out += '\\"';
    else if (b === 0x5c) out += "\\\\";
    else if (b >= 0x20 && b < 0x7f) out += String.fromCharCode(b);
    else out += "\\x" + b.toString(16).padStart(2, "0");
  }
  return out + '"';
}

// Per-locale ordered rules: [ {cat, cond}, ... ]. cond is "" for "other".
function rulesOf(entry) {
  const rules = [];
  for (const cat of CATS) {
    const key = "pluralRule-count-" + cat;
    if (!(key in entry)) continue;
    const cond = entry[key].split("@")[0].trim();
    rules.push({ cat, cond });
  }
  return rules;
}

// Dedupe rulesets into a pool; return {pool: [zigArrayName...], indexOf(rules)}.
function buildPool(name, data) {
  const pool = [];
  const seen = new Map();
  const locIdx = []; // [lang, idx]
  for (const [lang, entry] of Object.entries(data)) {
    if (lang === "root") continue;
    const rules = rulesOf(entry);
    const sig = JSON.stringify(rules);
    let idx = seen.get(sig);
    if (idx === undefined) {
      idx = pool.length;
      pool.push(rules);
      seen.set(sig, idx);
    }
    locIdx.push([lang.toLowerCase(), idx]);
  }
  locIdx.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  let out = "";
  pool.forEach((rules, i) => {
    out += `const ${name}_rs${i} = [_]Rule{`;
    out += rules.map((r) => ` .{ .cat = ${zstr(r.cat)}, .cond = ${zstr(r.cond)} }`).join(",");
    out += ` };\n`;
  });
  out += `const ${name}_sets = [_][]const Rule{`;
  out += pool.map((_, i) => ` &${name}_rs${i}`).join(",");
  out += ` };\n`;
  out += `const ${name}_loc = [_]Loc{\n`;
  for (const [lang, idx] of locIdx) out += `    .{ .k = ${zstr(lang)}, .i = ${idx} },\n`;
  out += `};\n`;
  return out;
}

let out = `// GENERATED by tools/gen_cldr_plurals.mjs from CLDR plurals.json +
// ordinals.json. Per-language ordered (category, condition) plural rules; the
// condition is the LDML plural-rule expression with samples stripped.
const std = @import("std");

pub const Rule = struct { cat: []const u8, cond: []const u8 };
const Loc = struct { k: []const u8, i: u16 };

fn find(loc: []const Loc, sets: []const []const Rule, lang: []const u8) ?[]const Rule {
    var lo: usize = 0;
    var hi: usize = loc.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, loc[mid].k, lang)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return sets[loc[mid].i],
        }
    }
    return null;
}

`;
out += buildPool("card", cardinal);
out += buildPool("ord", ordinal);
out += `
/// Cardinal plural rules for a language subtag (lowercased), or null.
pub fn cardinal(lang: []const u8) ?[]const Rule {
    return find(&card_loc, &card_sets, lang);
}
/// Ordinal plural rules for a language subtag (lowercased), or null.
pub fn ordinal(lang: []const u8) ?[]const Rule {
    return find(&ord_loc, &ord_sets, lang);
}
`;
process.stdout.write(out);
