#!/usr/bin/env python3
"""Generate src/encoding_singlebyte_data.zig — TextDecoder single-byte decoder
tables + the label->name map, sourced FROM node (the differential oracle) so the
result is byte-identical to node's ICU, which deviates from the WHATWG indexes
on ~12 bytes (koi8-u, windows-874 PUA, windows-1253/1255) and doesn't support
iso-8859-16. windows-1252 (+ its latin1/iso-8859-1/ascii aliases) is decoded as
latin1 to match V8, so it gets no table.

Needs node on PATH and:
  curl -s https://encoding.spec.whatwg.org/indexes.json  -o /tmp/enc-indexes.json
  curl -s https://encoding.spec.whatwg.org/encodings.json -o /tmp/encodings.json
"""
import json, subprocess

NODE = '/opt/homebrew/bin/node'
OUT = 'src/encoding_singlebyte_data.zig'

indexes = json.load(open('/tmp/enc-indexes.json'))
encs = json.load(open('/tmp/encodings.json'))

# Candidate single-byte names (128-entry WHATWG index), minus windows-1252 (latin1).
candidates = [k for k in indexes if isinstance(indexes[k], list) and len(indexes[k]) == 128 and k != 'windows-1252']
candidates.append('iso-8859-8-i')  # shares iso-8859-8 layout; node treats it as its own encoding
all_labels = sorted({lab for g in encs for e in g['encodings'] for lab in e['labels']})
# Decoded elsewhere (no single-byte table): utf variants + windows-1252 (latin1),
# plus gb18030 (encoding_multibyte.zig). big5/euc-kr/shift_jis/euc-jp/gbk are NOT
# listed — node/ICU's tables for them deviate from WHATWG, so they stay
# unsupported (RangeError) rather than subtly wrong.
SPECIAL = {'utf-8', 'utf-16le', 'utf-16be', 'windows-1252', 'gb18030'}

node_js = '''
const labels = %s, names = %s;
const out = { labels: {}, tables: {} };
for (const lab of labels) { try { out.labels[lab] = new TextDecoder(lab).encoding.toLowerCase(); } catch (e) {} }
for (const n of names) {
  let d; try { d = new TextDecoder(n); } catch (e) { continue; }
  const t = [];
  for (let b = 0x80; b <= 0xff; b++) t.push(d.decode(Uint8Array.from([b])).codePointAt(0));
  out.tables[d.encoding.toLowerCase()] = t;
}
process.stdout.write(JSON.stringify(out));
''' % (json.dumps(all_labels), json.dumps(candidates))

data = json.loads(subprocess.run([NODE, '-e', node_js], capture_output=True, text=True, check=True).stdout)
tables = data['tables']          # canonical name -> 128 code points (node's actual output)
supported = set(tables) | SPECIAL
# Keep only labels node accepts whose target we actually decode.
labels = {lab: name for lab, name in data['labels'].items() if name in supported}

def zigname(n):
    return n.replace('-', '_')

with open(OUT, 'w') as f:
    f.write('//! GENERATED by tools/gen_encodings.py — single-byte TextDecoder tables\n')
    f.write('//! and label map, sourced from node (byte-identical to its ICU). Do not edit.\n\n')
    f.write('const std = @import("std");\n\n')
    for name in sorted(tables):
        f.write(f'pub const {zigname(name)} = [128]u21{{\n')
        for i in range(0, 128, 12):
            f.write('    ' + ', '.join(f'0x{c:X}' for c in tables[name][i:i + 12]) + ',\n')
        f.write('};\n')
    f.write('\n/// Canonical name → its 128-entry high-byte (0x80..0xFF) table, or null.\n')
    f.write('pub fn singleByteTable(name: []const u8) ?*const [128]u21 {\n')
    for name in sorted(tables):
        f.write(f'    if (std.mem.eql(u8, name, "{name}")) return &{zigname(name)};\n')
    f.write('    return null;\n}\n')
    f.write('\n/// TextDecoder label (trimmed) → canonical encoding name, or null.\n')
    f.write('pub fn labelToName(label: []const u8) ?[]const u8 {\n')
    for lab in sorted(labels):
        f.write(f'    if (std.ascii.eqlIgnoreCase(label, "{lab}")) return "{labels[lab]}";\n')
    f.write('    return null;\n}\n')

print(f'wrote {OUT}: {len(tables)} tables, {len(labels)} labels (from node)')
