// Generate src/cldr_numbers.zig: per-locale decimal/grouping separators (and
// currency-symbol placement) from CLDR-JSON. Fetches only the locales the
// test262 intl402 corpus exercises. Run: node tools/gen_cldr_numbers.mjs
const BASE = "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-numbers-full/main";

// Common languages used by the test corpus (region variants inherit symbols).
const LOCALES = [
  "en", "en-GB", "en-CA", "de", "de-CH", "fr", "fr-CA", "fr-CH", "es", "es-419",
  "it", "pt", "pt-BR", "nl", "ru", "ja", "ko", "zh", "zh-Hant", "ar",
  "hi", "th", "tr", "pl", "cs", "sv", "da", "fi", "nb", "hu",
  "ro", "el", "he", "id", "vi", "uk", "ca", "hr", "sk", "sl",
  "bg", "et", "lv", "lt", "fa", "sr", "is", "ga", "mt", "cy",
];

async function fetchJSON(url) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r.json();
}

function zstr(s) {
  // Zig string literal with \xHH for non-ASCII bytes.
  const bytes = Buffer.from(s, "utf8");
  let out = '"';
  for (const b of bytes) {
    if (b === 0x22) out += '\\"';
    else if (b === 0x5c) out += "\\\\";
    else if (b >= 0x20 && b < 0x7f) out += String.fromCharCode(b);
    else out += "\\x" + b.toString(16).padStart(2, "0");
  }
  return out + '"';
}

const rows = [];
for (const loc of LOCALES) {
  try {
    const j = await fetchJSON(`${BASE}/${loc}/numbers.json`);
    const nums = j.main[loc].numbers;
    const sys = nums.defaultNumberingSystem || "latn";
    const sym = nums[`symbols-numberSystem-${sys}`] || nums["symbols-numberSystem-latn"];
    const curFmts = nums[`currencyFormats-numberSystem-${sys}`] || nums["currencyFormats-numberSystem-latn"] || {};
    const curFmt = curFmts.standard || "¤#,##0.00";
    // Symbol placement: does ¤ come before the number?
    const symBefore = curFmt.indexOf("¤") < curFmt.indexOf("#");
    // Accounting negatives: some locales wrap in parentheses (en "(¤#,##0.00)"),
    // others just use the minus sign (de "-#,##0.00 ¤").
    const acctFmt = curFmts.accounting || "";
    const acctParens = acctFmt.includes("(");
    rows.push({
      loc,
      decimal: sym.decimal, group: sym.group, percent: sym.percentSign, minus: sym.minusSign,
      nan: sym.nan || "NaN", infinity: sym.infinity || "∞",
      symBefore, acctParens,
    });
    process.stderr.write(`ok ${loc}\n`);
  } catch (e) {
    process.stderr.write(`skip ${loc}: ${e.message}\n`);
  }
}
// Region→script aliases the simple "xx-YY"→"xx" fallback can't derive
// (Traditional Chinese regions inherit from zh-Hant, not zh).
const ALIASES = { "zh-TW": "zh-Hant", "zh-HK": "zh-Hant", "zh-MO": "zh-Hant" };
for (const [alias, src] of Object.entries(ALIASES)) {
  const base = rows.find((r) => r.loc === src);
  if (base && !rows.find((r) => r.loc === alias)) rows.push({ ...base, loc: alias });
}
rows.sort((a, b) => (a.loc < b.loc ? -1 : 1));

let out = `// GENERATED by tools/gen_cldr_numbers.mjs from CLDR-JSON — do not edit.
const std = @import("std");

pub const NumSym = struct {
    decimal: []const u8,
    group: []const u8,
    percent: []const u8,
    minus: []const u8,
    nan: []const u8,
    infinity: []const u8,
    symbol_before: bool,
    /// Whether the locale's accounting currency format wraps negatives in
    /// parentheses ("(¤#,##0.00)") rather than using a minus sign.
    accounting_parens: bool,
};

const Row = struct { loc: []const u8, sym: NumSym };
const table = [_]Row{
`;
for (const r of rows) {
  out += `    .{ .loc = ${zstr(r.loc)}, .sym = .{ .decimal = ${zstr(r.decimal)}, .group = ${zstr(r.group)}, .percent = ${zstr(r.percent)}, .minus = ${zstr(r.minus)}, .nan = ${zstr(r.nan)}, .infinity = ${zstr(r.infinity)}, .symbol_before = ${r.symBefore}, .accounting_parens = ${r.acctParens} } },\n`;
}
out += `};

const default_sym = NumSym{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true };

/// Look up a locale's number symbols, falling back from "xx-YY" to "xx", then
/// to the en-style default.
pub fn lookup(locale: []const u8) NumSym {
    var probe = locale;
    while (true) {
        for (table) |row| if (std.mem.eql(u8, row.loc, probe)) return row.sym;
        if (std.mem.lastIndexOfScalar(u8, probe, '-')) |i| {
            probe = probe[0..i];
        } else break;
    }
    return default_sym;
}
`;
process.stdout.write(out);
