// Generate src/numbering_systems.zig from test262's numberingSystemDigits table
// (harness/testIntl.js) — the authoritative digit set the tests use, so our
// output bytes match theirs exactly. Run: node tools/gen_numbering.mjs
import { readFileSync } from "node:fs";
const src = readFileSync(process.argv[2] || "test262/harness/testIntl.js", "utf8");
const m = src.match(/var numberingSystemDigits = \{([\s\S]*?)\n\};/);
if (!m) throw new Error("numberingSystemDigits not found");

function decodeJsString(raw) {
  let out = "";
  for (let i = 0; i < raw.length; i++) {
    const ch = raw[i];
    if (ch !== "\\") {
      out += ch;
      continue;
    }
    if (++i >= raw.length) throw new Error("trailing escape in numberingSystemDigits");
    const esc = raw[i];
    switch (esc) {
      case '"':
      case "\\":
      case "/":
        out += esc;
        break;
      case "b":
        out += "\b";
        break;
      case "f":
        out += "\f";
        break;
      case "n":
        out += "\n";
        break;
      case "r":
        out += "\r";
        break;
      case "t":
        out += "\t";
        break;
      case "u": {
        if (raw[i + 1] === "{") {
          const end = raw.indexOf("}", i + 2);
          if (end === -1) throw new Error("unterminated code point escape");
          const hex = raw.slice(i + 2, end);
          if (!/^[0-9a-fA-F]{1,6}$/.test(hex)) throw new Error(`bad code point escape: ${hex}`);
          const cp = Number.parseInt(hex, 16);
          if (cp > 0x10ffff) throw new Error(`code point out of range: ${hex}`);
          out += String.fromCodePoint(cp);
          i = end;
        } else {
          const hex = raw.slice(i + 1, i + 5);
          if (!/^[0-9a-fA-F]{4}$/.test(hex)) throw new Error(`bad unicode escape: ${hex}`);
          out += String.fromCharCode(Number.parseInt(hex, 16));
          i += 4;
        }
        break;
      }
      default:
        throw new Error(`unsupported escape in numberingSystemDigits: \\${esc}`);
    }
  }
  return out;
}

function parseNumberingSystemDigits(body) {
  const obj = {};
  for (const line of body.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.length === 0) continue;
    const entry = trimmed.match(/^([A-Za-z0-9_-]+):\s*"((?:[^"\\]|\\.)*)",?$/);
    if (!entry) throw new Error(`unsupported numberingSystemDigits entry: ${trimmed}`);
    obj[entry[1]] = decodeJsString(entry[2]);
  }
  return obj;
}

const obj = parseNumberingSystemDigits(m[1]);

function zstr(s) {
  const bytes = Buffer.from(s, "utf8");
  let out = '"';
  for (const b of bytes) {
    if (b === 0x22) out += '\\"';
    else if (b === 0x5c) out += "\\\\";
    else if (b >= 0x20 && b < 0x7f) out += String.fromCharCode(b);
    else out += "\\x" + b.toString(16).padStart(2, "0");
  }
  return out + '"';
}

let out = `// GENERATED by tools/gen_numbering.mjs from test262 harness/testIntl.js.
// Each value is the system's ten digits (0-9) concatenated; within a system all
// digits have the same byte width, so the i-th digit is a fixed-width slice.
const std = @import("std");

const Row = struct { name: []const u8, digits: []const u8 };
const table = [_]Row{
`;
for (const [name, digits] of Object.entries(obj)) {
  // sanity: exactly 10 code points
  const cps = [...digits];
  if (cps.length !== 10) { process.stderr.write(`skip ${name}: ${cps.length} cps\\n`); continue; }
  out += `    .{ .name = ${zstr(name)}, .digits = ${zstr(digits)} },\n`;
}
out += `};

/// All supported numbering-system names (those with simple digit mappings), in
/// the table's sorted order. Used by Intl.supportedValuesOf("numberingSystem").
pub const names = blk: {
    var arr: [table.len][]const u8 = undefined;
    for (table, 0..) |row, i| arr[i] = row.name;
    break :blk arr;
};

/// The ten-digit string for a numbering system, or null if unknown/unsupported.
pub fn digits(name: []const u8) ?[]const u8 {
    for (table) |row| if (std.mem.eql(u8, row.name, name)) return row.digits;
    return null;
}

/// The UTF-8 bytes of digit \`d\` (0-9) in \`ds\` (a value returned by digits()).
pub fn nth(ds: []const u8, d: u8) []const u8 {
    const w = ds.len / 10;
    return ds[d * w .. (d + 1) * w];
}
`;
process.stdout.write(out);
