#!/usr/bin/env python3
"""Generate src/unicode_idna_data.zig from the UTS-46 IdnaMappingTable.

Fetch the table first:
  curl -s https://www.unicode.org/Public/idna/latest/IdnaMappingTable.txt -o /tmp/idnamap.txt

We resolve every status for WHATWG "domain to ASCII" parameters — non-transitional
processing, UseSTD3ASCIIRules=false — which collapses the statuses to three we must
store, defaulting anything absent to "valid" (kept as-is):
  - mapped / disallowed_STD3_mapped  -> store the target sequence
  - disallowed                       -> reject the whole domain
  - ignored                          -> drop the code point
  - valid / deviation / disallowed_STD3_valid -> omitted (kept as-is)
"""
import sys

SRC = '/tmp/idnamap.txt'
OUT = 'src/unicode_idna_data.zig'

entries = []          # (lo, hi, action, map_tuple)
mapdata = []          # flat list of target code points
mapindex = {}         # dedupe identical target tuples -> offset

def add_map(tup):
    if tup in mapindex:
        return mapindex[tup]
    off = len(mapdata)
    mapdata.extend(tup)
    mapindex[tup] = off
    return off

for line in open(SRC):
    line = line.split('#')[0].strip()
    if not line:
        continue
    parts = [p.strip() for p in line.split(';')]
    rng = parts[0]
    status = parts[1] if len(parts) > 1 else ''
    lo, hi = (rng.split('..') if '..' in rng else (rng, rng))
    lo, hi = int(lo, 16), int(hi, 16)

    if status in ('valid', 'deviation', 'disallowed_STD3_valid'):
        continue  # kept as-is → default
    elif status in ('mapped', 'disallowed_STD3_mapped'):
        target = tuple(int(x, 16) for x in parts[2].split()) if len(parts) > 2 and parts[2] else ()
        if not target:
            continue  # maps to nothing → treat as ignored
        off = add_map(target)
        entries.append((lo, hi, 'mapped', off, len(target)))
    elif status == 'ignored':
        entries.append((lo, hi, 'ignored', 0, 0))
    elif status == 'disallowed':
        entries.append((lo, hi, 'disallowed', 0, 0))
    else:
        print(f'unknown status: {status!r} on {line}', file=sys.stderr)
        sys.exit(1)

entries.sort()

# Coalesce adjacent ignored/disallowed ranges (mapped ones keep their offsets).
merged = []
for e in entries:
    if merged:
        p = merged[-1]
        if p[2] == e[2] and e[2] in ('ignored', 'disallowed') and e[0] == p[1] + 1:
            merged[-1] = (p[0], e[1], p[2], 0, 0)
            continue
    merged.append(e)
entries = merged

# ---- Label-validity auxiliary tables (from UnicodeData.txt + DerivedJoiningType) ----
# GC=Mark ranges (Mn/Mc/Me) for the leading-combining-mark check, and virama
# (Canonical_Combining_Class == 9) for CheckJoiners.
UCD = '/tmp/ucd.txt'
JT = '/tmp/jt.txt'

def coalesce(points):
    points = sorted(set(points))
    ranges = []
    for p in points:
        if ranges and p == ranges[-1][1] + 1:
            ranges[-1][1] = p
        else:
            ranges.append([p, p])
    return [(lo, hi) for lo, hi in ranges]

marks = []
virama = []
_pending_first = None
for line in open(UCD):
    fields = line.rstrip('\n').split(';')
    if len(fields) < 4:
        continue
    cp = int(fields[0], 16)
    name, gc, ccc = fields[1], fields[2], fields[3]
    if name.endswith(', First>'):
        _pending_first = (cp, gc, ccc)
        continue
    if name.endswith(', Last>') and _pending_first:
        lo, fgc, fccc = _pending_first
        _pending_first = None
        if fgc in ('Mn', 'Mc', 'Me'):
            marks.extend(range(lo, cp + 1))
        if fccc == '9':
            virama.extend(range(lo, cp + 1))
        continue
    if gc in ('Mn', 'Mc', 'Me'):
        marks.append(cp)
    if ccc == '9':
        virama.append(cp)
mark_ranges = coalesce(marks)

# Joining_Type ranges (L/R/D/T; U=default omitted, C not used by the ZWNJ rule).
JMAP = {'L': 'l', 'R': 'r', 'D': 'd', 'T': 't'}
join = []
for line in open(JT):
    line = line.split('#')[0].strip()
    if not line:
        continue
    rng, jt = [p.strip() for p in line.split(';')]
    if jt not in JMAP:
        continue
    lo, hi = (rng.split('..') if '..' in rng else (rng, rng))
    join.append((int(lo, 16), int(hi, 16), JMAP[jt]))
join.sort()

with open(OUT, 'w') as f:
    f.write('//! GENERATED by tools/gen_idna.py from the UTS-46 IdnaMappingTable.\n')
    f.write('//! Non-transitional, UseSTD3ASCIIRules=false. Do not edit by hand.\n\n')
    f.write('pub const Action = enum(u8) { mapped, disallowed, ignored };\n\n')
    f.write('pub const Entry = struct { lo: u21, hi: u21, action: Action, off: u32, len: u16 };\n\n')
    f.write(f'// {len(entries)} ranges; any code point not covered is "valid" (kept as-is).\n')
    f.write('pub const entries = [_]Entry{\n')
    for lo, hi, act, off, ln in entries:
        f.write(f'    .{{ .lo = 0x{lo:X}, .hi = 0x{hi:X}, .action = .{act}, .off = {off}, .len = {ln} }},\n')
    f.write('};\n\n')
    f.write(f'// {len(mapdata)} target code points, referenced by mapped entries.\n')
    f.write('pub const map_data = [_]u21{\n')
    for i in range(0, len(mapdata), 16):
        chunk = ', '.join(f'0x{c:X}' for c in mapdata[i:i+16])
        f.write(f'    {chunk},\n')
    f.write('};\n\n')

    f.write('pub const Range = struct { lo: u21, hi: u21 };\n\n')
    f.write(f'// {len(mark_ranges)} GC=Mark ranges (Mn/Mc/Me): a label may not begin with one.\n')
    f.write('pub const mark_ranges = [_]Range{\n')
    for lo, hi in mark_ranges:
        f.write(f'    .{{ .lo = 0x{lo:X}, .hi = 0x{hi:X} }},\n')
    f.write('};\n\n')

    f.write('pub const JoinType = enum(u8) { l, r, d, t };\n')
    f.write('pub const JoinRange = struct { lo: u21, hi: u21, jt: JoinType };\n\n')
    f.write(f'// {len(join)} Joining_Type ranges (L/R/D/T) for CheckJoiners.\n')
    f.write('pub const join_ranges = [_]JoinRange{\n')
    for lo, hi, jt in join:
        f.write(f'    .{{ .lo = 0x{lo:X}, .hi = 0x{hi:X}, .jt = .{jt} }},\n')
    f.write('};\n\n')

    f.write(f'// {len(sorted(set(virama)))} virama (CCC==9) code points for CheckJoiners.\n')
    f.write('pub const virama = [_]u21{\n')
    vs = sorted(set(virama))
    for i in range(0, len(vs), 12):
        f.write('    ' + ', '.join(f'0x{c:X}' for c in vs[i:i+12]) + ',\n')
    f.write('};\n')

print(f'wrote {OUT}: {len(entries)} entries, {len(mapdata)} map cps, '
      f'{len(mark_ranges)} mark ranges, {len(join)} join ranges, {len(set(virama))} virama')
