/** Generate the frozen single-byte TextDecoder tables and label map. */
import { readText, writeText } from "./lib/home";

type Oracle = {
  schema_version: number;
  kind: string;
  tables: Record<string, number[]>;
  labels: Record<string, string>;
};

const oraclePath = process.argv[2] || "docs/.data/encoding-singlebyte-oracle-v1.json";
const outputPath = process.argv[3] || "src/encoding_singlebyte_data.zig";
const oracle = JSON.parse(readText(oraclePath)) as Oracle;
if (oracle.schema_version !== 1 || oracle.kind !== "zig_js_single_byte_decoder_oracle") {
  throw new Error(`${oraclePath}: unsupported single-byte oracle schema`);
}

const names = Object.keys(oracle.tables).sort();
const labels = Object.keys(oracle.labels).sort();
if (names.length !== 26 || labels.length !== 183) {
  throw new Error(`${oraclePath}: expected 26 tables and 183 labels, found ${names.length} and ${labels.length}`);
}
const zigName = (name: string): string => name.replace(/-/g, "_");
const lines = [
  "//! GENERATED by tools/gen_encodings.ts — single-byte TextDecoder tables",
  "//! and label map, sourced from the checked v1 decoder oracle. Do not edit.",
  "",
  'const std = @import("std");',
  "",
];

for (const name of names) {
  const table = oracle.tables[name];
  if (!Array.isArray(table) || table.length !== 128 || table.some((point) => !Number.isInteger(point) || point < 0 || point > 0x10ffff)) {
    throw new Error(`${oraclePath}: ${name} must contain exactly 128 Unicode scalar values`);
  }
  lines.push(`pub const ${zigName(name)} = [128]u21{`);
  for (let index = 0; index < table.length; index += 12) {
    lines.push("    " + table.slice(index, index + 12).map((point) => `0x${point.toString(16).toUpperCase()}`).join(", ") + ",");
  }
  lines.push("};");
}

lines.push("", "/// Canonical name → its 128-entry high-byte (0x80..0xFF) table, or null.", "pub fn singleByteTable(name: []const u8) ?*const [128]u21 {");
for (const name of names) lines.push(`    if (std.mem.eql(u8, name, "${name}")) return &${zigName(name)};`);
lines.push("    return null;", "}", "", "/// TextDecoder label (trimmed) → canonical encoding name, or null.", "pub fn labelToName(label: []const u8) ?[]const u8 {");
for (const label of labels) {
  const name = oracle.labels[label];
  if (typeof name !== "string" || !name) throw new Error(`${oraclePath}: invalid target for label ${label}`);
  lines.push(`    if (std.ascii.eqlIgnoreCase(label, ${JSON.stringify(label)})) return ${JSON.stringify(name)};`);
}
lines.push("    return null;", "}", "");
writeText(outputPath, lines.join("\n"));
console.log(`wrote ${outputPath}: ${names.length} tables, ${labels.length} labels (checked oracle)`);
