// Generate src/cldr_locale.zig from CLDR's supplemental aliases.json and
// likelySubtags.json (cldr-json). Emits sorted key/value tables (binary
// searched at runtime) for language/script/territory/variant aliases and the
// likely-subtags map, used by Intl.Locale canonicalization and maximize/minimize.
//
//   node tools/gen_cldr_locale.mjs /tmp/aliases.json /tmp/likelySubtags.json > src/cldr_locale.zig
import { readFileSync } from "node:fs";

const aliases = JSON.parse(readFileSync(process.argv[2] || "/tmp/aliases.json", "utf8")).supplemental.metadata.alias;
const likely = JSON.parse(readFileSync(process.argv[3] || "/tmp/likelySubtags.json", "utf8")).supplemental.likelySubtags;

function zstr(s) {
  let out = '"';
  for (const b of Buffer.from(s, "utf8")) {
    if (b === 0x22) out += '\\"';
    else if (b === 0x5c) out += "\\\\";
    else if (b >= 0x20 && b < 0x7f) out += String.fromCharCode(b);
    else out += "\\x" + b.toString(16).padStart(2, "0");
  }
  return out + '"';
}

// CLDR keys use "_" between subtags; BCP-47 tags use "-". Normalize to "-" and
// lowercase (lookups are done on the lowercased canonical form).
const norm = (s) => s.replace(/_/g, "-").toLowerCase();

function table(name, entries) {
  // entries: array of [key, value]; dedupe + sort by key for binary search.
  const map = new Map();
  for (const [k, v] of entries) if (!map.has(k)) map.set(k, v);
  const rows = [...map.entries()].sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  let out = `const ${name} = [_]Row{\n`;
  for (const [k, v] of rows) out += `    .{ .k = ${zstr(k)}, .v = ${zstr(v)} },\n`;
  out += `};\n`;
  return out;
}

let out = `// GENERATED by tools/gen_cldr_locale.mjs from CLDR aliases.json +
// likelySubtags.json. Sorted key/value tables, binary searched at runtime.
const std = @import("std");

const Row = struct { k: []const u8, v: []const u8 };

fn lookup(tbl: []const Row, key: []const u8) ?[]const u8 {
    var lo: usize = 0;
    var hi: usize = tbl.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, tbl[mid].k, key)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return tbl[mid].v,
        }
    }
    return null;
}

`;

// languageAlias: keys may be multi-subtag grandfathered/redundant tags.
out += table("language_alias", Object.entries(aliases.languageAlias).map(([k, v]) => [norm(k), norm(v._replacement)]));
// scriptAlias: 4-letter script → replacement (Titlecase preserved as lowercased here).
out += table("script_alias", Object.entries(aliases.scriptAlias).map(([k, v]) => [norm(k), norm(v._replacement)]));
// territoryAlias: region → one or more replacements (space separated).
out += table("territory_alias", Object.entries(aliases.territoryAlias).map(([k, v]) => [norm(k), norm(v._replacement)]));
// variantAlias.
out += table("variant_alias", Object.entries(aliases.variantAlias).map(([k, v]) => [norm(k), norm(v._replacement)]));
// subdivisionAlias: deprecated subdivision id → one or more replacements (used
// by the `-u-rg-`/`-u-sd-` keyword value canonicalization; caller picks first).
out += table("subdivision_alias", Object.entries(aliases.subdivisionAlias).map(([k, v]) => [norm(k), norm(v._replacement)]));
// likelySubtags: partial language-id → maximal language-id.
out += table("likely_subtags", Object.entries(likely).map(([k, v]) => [norm(k), norm(v)]));

out += `
pub fn languageAlias(key: []const u8) ?[]const u8 {
    return lookup(&language_alias, key);
}
pub fn scriptAlias(key: []const u8) ?[]const u8 {
    return lookup(&script_alias, key);
}
/// The territory replacement (may be a space-separated list; caller picks).
pub fn territoryAlias(key: []const u8) ?[]const u8 {
    return lookup(&territory_alias, key);
}
pub fn variantAlias(key: []const u8) ?[]const u8 {
    return lookup(&variant_alias, key);
}
/// The subdivision replacement (may be a space-separated list; caller picks).
pub fn subdivisionAlias(key: []const u8) ?[]const u8 {
    return lookup(&subdivision_alias, key);
}
pub fn likely(key: []const u8) ?[]const u8 {
    return lookup(&likely_subtags, key);
}
`;

process.stdout.write(out);
