// Generate src/cldr_timedata.zig from CLDR supplemental timeData.json. Each
// region maps to its default hour cycle (_preferred) plus the 12-hour and
// 24-hour variants drawn from _allowed, used by Intl.DateTimeFormat hour-cycle
// resolution. Regions are looked up (by the maximized locale's territory) via
// binary search; "001" is the world fallback.
//
//   node tools/gen_cldr_timedata.mjs /tmp/timeData.json > src/cldr_timedata.zig
import { readFileSync } from "node:fs";

const data = JSON.parse(readFileSync(process.argv[2] || "/tmp/timeData.json", "utf8")).supplemental.timeData;

// CLDR pattern symbols → ECMA-402 hour cycle.
const SYM = { H: "h23", h: "h12", K: "h11", k: "h24" };

function rowOf(entry) {
  const pref = SYM[entry._preferred] || "h23";
  let h12 = "h12";
  let h24 = "h23";
  for (const s of (entry._allowed || "").split(/\s+/)) {
    const hc = SYM[s];
    if (hc === "h12" || hc === "h11") { h12 = hc; break; }
  }
  for (const s of (entry._allowed || "").split(/\s+/)) {
    const hc = SYM[s];
    if (hc === "h23" || hc === "h24") { h24 = hc; break; }
  }
  return { def: pref, h12, h24 };
}

const rows = Object.entries(data)
  .map(([region, entry]) => [region.toLowerCase(), rowOf(entry)])
  .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));

function zstr(s) {
  return '"' + s + '"';
}

let out = `// GENERATED by tools/gen_cldr_timedata.mjs from CLDR timeData.json.
// Region -> default/12-hour/24-hour hour cycle, binary searched at runtime.
const std = @import("std");

pub const HourCycles = struct { def: []const u8, h12: []const u8, h24: []const u8 };
const Row = struct { k: []const u8, v: HourCycles };

const rows = [_]Row{
`;
for (const [region, r] of rows) {
  out += `    .{ .k = ${zstr(region)}, .v = .{ .def = ${zstr(r.def)}, .h12 = ${zstr(r.h12)}, .h24 = ${zstr(r.h24)} } },\n`;
}
out += `};

/// Hour-cycle data for a territory (lowercased), or the "001" world default.
pub fn forRegion(region: []const u8) HourCycles {
    var lo: usize = 0;
    var hi: usize = rows.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, rows[mid].k, region)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return rows[mid].v,
        }
    }
    return .{ .def = "h23", .h12 = "h12", .h24 = "h23" };
}
`;
process.stdout.write(out);
