// Generate src/cldr_plurals.zig from CLDR plurals.json (cardinal),
// ordinals.json, and pluralRanges.json. Each locale maps to ordered cardinal
// and ordinal (category, condition) rules plus plural-range category mappings.
// Rule samples are stripped, rulesets are deduped, and locales are looked up by
// language subtag via binary search.
//
//   home-tool run tools/gen_cldr_plurals.ts /tmp/plurals.json /tmp/ordinals.json /tmp/pluralRanges.json > src/cldr_plurals.zig
import { readText, utf8Bytes } from "./lib/home";

const cardinal = JSON.parse(readText(process.argv[2] || "/tmp/plurals.json")).supplemental["plurals-type-cardinal"];
const ordinal = JSON.parse(readText(process.argv[3] || "/tmp/ordinals.json")).supplemental["plurals-type-ordinal"];
const ranges = JSON.parse(readText(process.argv[4] || "/tmp/pluralRanges.json")).supplemental.plurals;

const CATS = ["zero", "one", "two", "few", "many", "other"];

function zstr(s) {
  let out = '"';
  for (const b of utf8Bytes(s)) {
    if (b === 0x22) out += '\\"';
    else if (b === 0x5c) out += "\\\\";
    else if (b >= 0x20 && b < 0x7f) out += String.fromCharCode(b);
    else out += "\\x" + b.toString(16).padStart(2, "0");
  }
  return out + '"';
}

// Per-locale ordered rules: [ {cat, cond}, ... ]. cond is "" for "other".
function rulesOf(entry) {
  const rules = [];
  for (const cat of CATS) {
    const key = "pluralRule-count-" + cat;
    if (!(key in entry)) continue;
    const cond = entry[key].split("@")[0].trim();
    rules.push({ cat, cond });
  }
  return rules;
}

// Dedupe rulesets into a pool; return {pool: [zigArrayName...], indexOf(rules)}.
function buildPool(name, data) {
  const pool = [];
  const seen = new Map();
  const locIdx = []; // [lang, idx]
  for (const [lang, entry] of Object.entries(data)) {
    if (lang === "root") continue;
    const rules = rulesOf(entry);
    const sig = JSON.stringify(rules);
    let idx = seen.get(sig);
    if (idx === undefined) {
      idx = pool.length;
      pool.push(rules);
      seen.set(sig, idx);
    }
    locIdx.push([lang.toLowerCase(), idx]);
  }
  locIdx.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  let out = "";
  pool.forEach((rules, i) => {
    out += `const ${name}_rs${i} = [_]Rule{`;
    out += rules.map((r) => ` .{ .cat = ${zstr(r.cat)}, .cond = ${zstr(r.cond)} }`).join(",");
    out += ` };\n`;
  });
  out += `const ${name}_sets = [_][]const Rule{`;
  out += pool.map((_, i) => ` &${name}_rs${i}`).join(",");
  out += ` };\n`;
  out += `const ${name}_loc = [_]Loc{\n`;
  for (const [lang, idx] of locIdx) out += `    .{ .k = ${zstr(lang)}, .i = ${idx} },\n`;
  out += `};\n`;
  return out;
}

function rangeRulesOf(entry) {
  const rules = [];
  for (const [key, result] of Object.entries(entry)) {
    const match = key.match(/^pluralRange-start-(.+)-end-(.+)$/);
    if (!match) throw new Error(`invalid plural range key: ${key}`);
    rules.push({ start: match[1], end: match[2], result });
  }
  rules.sort((a, b) => a.start < b.start ? -1 : a.start > b.start ? 1 : a.end < b.end ? -1 : a.end > b.end ? 1 : 0);
  return rules;
}

function buildRangePool(data) {
  const pool = [], seen = new Map(), locIdx = [];
  for (const [lang, entry] of Object.entries(data)) {
    const rules = rangeRulesOf(entry);
    const signature = JSON.stringify(rules);
    let index = seen.get(signature);
    if (index === undefined) {
      index = pool.length;
      pool.push(rules);
      seen.set(signature, index);
    }
    locIdx.push([lang.toLowerCase(), index]);
  }
  locIdx.sort((a, b) => a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0);
  let out = "";
  pool.forEach((rules, index) => {
    out += `const range_rs${index} = [_]RangeRule{`;
    out += rules.map((rule) => ` .{ .start = ${zstr(rule.start)}, .end = ${zstr(rule.end)}, .result = ${zstr(rule.result)} }`).join(",");
    out += ` };\n`;
  });
  out += `const range_sets = [_][]const RangeRule{${pool.map((_, index) => ` &range_rs${index}`).join(",")} };\n`;
  out += `const range_loc = [_]Loc{\n`;
  for (const [lang, index] of locIdx) out += `    .{ .k = ${zstr(lang)}, .i = ${index} },\n`;
  out += `};\n`;
  return out;
}

let out = `// GENERATED by tools/gen_cldr_plurals.ts from CLDR plurals.json,
// ordinals.json, and pluralRanges.json. Per-language ordered plural rules and
// range-category mappings; rule samples are stripped.
const std = @import("std");

pub const Rule = struct { cat: []const u8, cond: []const u8 };
pub const RangeRule = struct { start: []const u8, end: []const u8, result: []const u8 };
const Loc = struct { k: []const u8, i: u16 };

fn find(loc: []const Loc, sets: []const []const Rule, lang: []const u8) ?[]const Rule {
    var lo: usize = 0;
    var hi: usize = loc.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, loc[mid].k, lang)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return sets[loc[mid].i],
        }
    }
    return null;
}

fn findRange(lang: []const u8) ?[]const RangeRule {
    var lo: usize = 0;
    var hi: usize = range_loc.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, range_loc[mid].k, lang)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return range_sets[range_loc[mid].i],
        }
    }
    return null;
}

`;
out += buildPool("card", cardinal);
out += buildPool("ord", ordinal);
out += buildRangePool(ranges);
out += `
/// Cardinal plural rules for a language subtag (lowercased), or null.
pub fn cardinal(lang: []const u8) ?[]const Rule {
    return find(&card_loc, &card_sets, lang);
}
/// Ordinal plural rules for a language subtag (lowercased), or null.
pub fn ordinal(lang: []const u8) ?[]const Rule {
    return find(&ord_loc, &ord_sets, lang);
}

/// CLDR plural-range category for two already-resolved cardinal categories.
/// An unlisted pair uses the LDML default category "other".
pub fn range(lang: []const u8, start: []const u8, end: []const u8) []const u8 {
    const rules = findRange(lang) orelse return "other";
    for (rules) |rule| if (std.mem.eql(u8, rule.start, start) and std.mem.eql(u8, rule.end, end)) return rule.result;
    return "other";
}
`;
process.stdout.write(out);
