// GENERATED by tools/gen_cldr_collation.ts from CLDR 48.2 — do not edit.
// Compact primary tailorings for selected Latin-script standard collations.
const std = @import("std");

pub const Token = struct { bytes: []const u8, weight: u16 };
pub const Profile = struct { ascii: *const [26]u16, tokens: []const Token };

const ascii_cs = [26]u16{ 1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 25, 26, 27, 28, 29, 30 };
const tokens_cs = [_]Token{
    .{ .bytes = "ch", .weight = 10 },
    .{ .bytes = "č", .weight = 4 },
    .{ .bytes = "ř", .weight = 21 },
    .{ .bytes = "š", .weight = 23 },
    .{ .bytes = "ž", .weight = 31 },
};

const ascii_cy = [26]u16{ 1, 2, 3, 5, 7, 8, 10, 12, 13, 14, 15, 16, 18, 19, 20, 21, 23, 24, 26, 27, 29, 30, 31, 32, 33, 34 };
const tokens_cy = [_]Token{
    .{ .bytes = "ch", .weight = 4 },
    .{ .bytes = "dd", .weight = 6 },
    .{ .bytes = "ff", .weight = 9 },
    .{ .bytes = "ll", .weight = 17 },
    .{ .bytes = "ng", .weight = 11 },
    .{ .bytes = "ph", .weight = 22 },
    .{ .bytes = "rh", .weight = 25 },
    .{ .bytes = "th", .weight = 28 },
};

const ascii_da = [26]u16{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 };
const tokens_da = [_]Token{
    .{ .bytes = "aa", .weight = 29 },
    .{ .bytes = "ä", .weight = 27 },
    .{ .bytes = "å", .weight = 29 },
    .{ .bytes = "ö", .weight = 28 },
    .{ .bytes = "ő", .weight = 28 },
    .{ .bytes = "ü", .weight = 25 },
    .{ .bytes = "ű", .weight = 25 },
    .{ .bytes = "æ", .weight = 27 },
    .{ .bytes = "ð", .weight = 4 },
    .{ .bytes = "ø", .weight = 28 },
    .{ .bytes = "đ", .weight = 4 },
};

const ascii_eo = [26]u16{ 1, 2, 3, 5, 6, 7, 8, 10, 12, 13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 28, 29, 30, 31, 32 };
const tokens_eo = [_]Token{
    .{ .bytes = "ĉ", .weight = 4 },
    .{ .bytes = "ĝ", .weight = 9 },
    .{ .bytes = "ĥ", .weight = 11 },
    .{ .bytes = "ĵ", .weight = 14 },
    .{ .bytes = "ŝ", .weight = 24 },
    .{ .bytes = "ŭ", .weight = 27 },
};

const ascii_es = [26]u16{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27 };
const tokens_es = [_]Token{
    .{ .bytes = "ñ", .weight = 15 },
};

const ascii_et = [26]u16{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 23, 24, 25, 26, 31, 32, 21 };
const tokens_et = [_]Token{
    .{ .bytes = "ä", .weight = 28 },
    .{ .bytes = "õ", .weight = 27 },
    .{ .bytes = "ö", .weight = 29 },
    .{ .bytes = "š", .weight = 20 },
    .{ .bytes = "ü", .weight = 30 },
    .{ .bytes = "ž", .weight = 22 },
};

const ascii_fi = [26]u16{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 };
const tokens_fi = [_]Token{
    .{ .bytes = "ä", .weight = 28 },
    .{ .bytes = "å", .weight = 27 },
    .{ .bytes = "ö", .weight = 29 },
    .{ .bytes = "ü", .weight = 25 },
    .{ .bytes = "æ", .weight = 28 },
    .{ .bytes = "ø", .weight = 29 },
};

const ascii_fo = [26]u16{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 };
const tokens_fo = [_]Token{
    .{ .bytes = "aa", .weight = 29 },
    .{ .bytes = "ä", .weight = 27 },
    .{ .bytes = "å", .weight = 29 },
    .{ .bytes = "ę", .weight = 27 },
    .{ .bytes = "ö", .weight = 28 },
    .{ .bytes = "ő", .weight = 28 },
    .{ .bytes = "ü", .weight = 25 },
    .{ .bytes = "ű", .weight = 25 },
    .{ .bytes = "æ", .weight = 27 },
    .{ .bytes = "ð", .weight = 4 },
    .{ .bytes = "ø", .weight = 28 },
    .{ .bytes = "đ", .weight = 4 },
    .{ .bytes = "œ", .weight = 28 },
};

const ascii_hr = [26]u16{ 1, 2, 3, 6, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33 };
const tokens_hr = [_]Token{
    .{ .bytes = "dž", .weight = 7 },
    .{ .bytes = "ć", .weight = 5 },
    .{ .bytes = "č", .weight = 4 },
    .{ .bytes = "lj", .weight = 17 },
    .{ .bytes = "nj", .weight = 20 },
    .{ .bytes = "š", .weight = 26 },
    .{ .bytes = "ž", .weight = 34 },
    .{ .bytes = "đ", .weight = 8 },
    .{ .bytes = "ǆ", .weight = 7 },
    .{ .bytes = "ǉ", .weight = 17 },
    .{ .bytes = "ǌ", .weight = 20 },
};

const ascii_hu = [26]u16{ 1, 2, 3, 5, 8, 9, 10, 12, 13, 14, 15, 16, 18, 19, 21, 23, 24, 25, 26, 28, 30, 32, 33, 34, 35, 36 };
const tokens_hu = [_]Token{
    .{ .bytes = "dzs", .weight = 7 },
    .{ .bytes = "cs", .weight = 4 },
    .{ .bytes = "dz", .weight = 6 },
    .{ .bytes = "gy", .weight = 11 },
    .{ .bytes = "ly", .weight = 17 },
    .{ .bytes = "ny", .weight = 20 },
    .{ .bytes = "ö", .weight = 22 },
    .{ .bytes = "ő", .weight = 22 },
    .{ .bytes = "sz", .weight = 27 },
    .{ .bytes = "ty", .weight = 29 },
    .{ .bytes = "ü", .weight = 31 },
    .{ .bytes = "ű", .weight = 31 },
    .{ .bytes = "zs", .weight = 37 },
};

const ascii_is = [26]u16{ 1, 3, 4, 5, 7, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 33 };
const tokens_is = [_]Token{
    .{ .bytes = "á", .weight = 2 },
    .{ .bytes = "ä", .weight = 34 },
    .{ .bytes = "å", .weight = 36 },
    .{ .bytes = "é", .weight = 8 },
    .{ .bytes = "í", .weight = 13 },
    .{ .bytes = "ó", .weight = 20 },
    .{ .bytes = "ö", .weight = 35 },
    .{ .bytes = "ú", .weight = 27 },
    .{ .bytes = "ý", .weight = 32 },
    .{ .bytes = "æ", .weight = 34 },
    .{ .bytes = "ð", .weight = 6 },
    .{ .bytes = "ø", .weight = 35 },
    .{ .bytes = "đ", .weight = 5 },
};

const ascii_lt = [26]u16{ 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 23, 24, 25, 26, 10, 28 };
const tokens_lt = [_]Token{
    .{ .bytes = "ą", .weight = 1 },
    .{ .bytes = "č", .weight = 4 },
    .{ .bytes = "ė", .weight = 6 },
    .{ .bytes = "ę", .weight = 6 },
    .{ .bytes = "į", .weight = 10 },
    .{ .bytes = "š", .weight = 21 },
    .{ .bytes = "ū", .weight = 23 },
    .{ .bytes = "ų", .weight = 23 },
    .{ .bytes = "ž", .weight = 29 },
};

const ascii_lv = [26]u16{ 1, 3, 4, 6, 7, 9, 10, 12, 13, 16, 17, 19, 21, 22, 24, 26, 27, 28, 30, 32, 33, 35, 36, 37, 14, 38 };
const tokens_lv = [_]Token{
    .{ .bytes = "ā", .weight = 2 },
    .{ .bytes = "č", .weight = 5 },
    .{ .bytes = "ē", .weight = 8 },
    .{ .bytes = "ģ", .weight = 11 },
    .{ .bytes = "ī", .weight = 15 },
    .{ .bytes = "ķ", .weight = 18 },
    .{ .bytes = "ļ", .weight = 20 },
    .{ .bytes = "ņ", .weight = 23 },
    .{ .bytes = "ō", .weight = 25 },
    .{ .bytes = "ŗ", .weight = 29 },
    .{ .bytes = "š", .weight = 31 },
    .{ .bytes = "ū", .weight = 34 },
    .{ .bytes = "ž", .weight = 39 },
};

const ascii_no = [26]u16{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 };
const tokens_no = [_]Token{
    .{ .bytes = "aa", .weight = 29 },
    .{ .bytes = "ä", .weight = 27 },
    .{ .bytes = "å", .weight = 29 },
    .{ .bytes = "ę", .weight = 27 },
    .{ .bytes = "ö", .weight = 28 },
    .{ .bytes = "ő", .weight = 28 },
    .{ .bytes = "ü", .weight = 25 },
    .{ .bytes = "ű", .weight = 25 },
    .{ .bytes = "æ", .weight = 27 },
    .{ .bytes = "ð", .weight = 4 },
    .{ .bytes = "ø", .weight = 28 },
    .{ .bytes = "đ", .weight = 4 },
    .{ .bytes = "œ", .weight = 28 },
};

const ascii_pl = [26]u16{ 1, 3, 4, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17, 18, 20, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33 };
const tokens_pl = [_]Token{
    .{ .bytes = "ą", .weight = 2 },
    .{ .bytes = "ć", .weight = 5 },
    .{ .bytes = "ę", .weight = 8 },
    .{ .bytes = "ń", .weight = 19 },
    .{ .bytes = "ó", .weight = 21 },
    .{ .bytes = "ś", .weight = 26 },
    .{ .bytes = "ź", .weight = 34 },
    .{ .bytes = "ż", .weight = 35 },
    .{ .bytes = "ł", .weight = 16 },
};

const ascii_ro = [26]u16{ 1, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 26, 27, 28, 29, 30, 31 };
const tokens_ro = [_]Token{
    .{ .bytes = "â", .weight = 3 },
    .{ .bytes = "ă", .weight = 2 },
    .{ .bytes = "î", .weight = 12 },
    .{ .bytes = "ș", .weight = 23 },
    .{ .bytes = "ş", .weight = 23 },
    .{ .bytes = "ț", .weight = 25 },
    .{ .bytes = "ţ", .weight = 25 },
};

const ascii_sk = [26]u16{ 1, 3, 4, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, 24, 26, 27, 28, 29, 30, 31, 32 };
const tokens_sk = [_]Token{
    .{ .bytes = "ä", .weight = 2 },
    .{ .bytes = "ch", .weight = 11 },
    .{ .bytes = "č", .weight = 5 },
    .{ .bytes = "ô", .weight = 19 },
    .{ .bytes = "ř", .weight = 23 },
    .{ .bytes = "š", .weight = 25 },
    .{ .bytes = "ž", .weight = 33 },
};

const ascii_sl = [26]u16{ 1, 2, 3, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30 };
const tokens_sl = [_]Token{
    .{ .bytes = "ć", .weight = 5 },
    .{ .bytes = "č", .weight = 4 },
    .{ .bytes = "š", .weight = 23 },
    .{ .bytes = "ž", .weight = 31 },
    .{ .bytes = "đ", .weight = 7 },
};

const ascii_sq = [26]u16{ 1, 2, 3, 5, 7, 9, 10, 12, 13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 26, 28, 30, 31, 32, 33, 35, 36 };
const tokens_sq = [_]Token{
    .{ .bytes = "ç", .weight = 4 },
    .{ .bytes = "dh", .weight = 6 },
    .{ .bytes = "ë", .weight = 8 },
    .{ .bytes = "gj", .weight = 11 },
    .{ .bytes = "ll", .weight = 17 },
    .{ .bytes = "nj", .weight = 20 },
    .{ .bytes = "rr", .weight = 25 },
    .{ .bytes = "sh", .weight = 27 },
    .{ .bytes = "th", .weight = 29 },
    .{ .bytes = "xh", .weight = 34 },
    .{ .bytes = "zh", .weight = 37 },
};

const ascii_sv = [26]u16{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 };
const tokens_sv = [_]Token{
    .{ .bytes = "ä", .weight = 28 },
    .{ .bytes = "å", .weight = 27 },
    .{ .bytes = "ę", .weight = 28 },
    .{ .bytes = "ô", .weight = 29 },
    .{ .bytes = "ö", .weight = 29 },
    .{ .bytes = "ő", .weight = 29 },
    .{ .bytes = "ü", .weight = 25 },
    .{ .bytes = "ű", .weight = 25 },
    .{ .bytes = "æ", .weight = 28 },
    .{ .bytes = "ð", .weight = 4 },
    .{ .bytes = "ø", .weight = 29 },
    .{ .bytes = "đ", .weight = 4 },
    .{ .bytes = "œ", .weight = 29 },
};

const ascii_vi = [26]u16{ 1, 4, 5, 6, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33 };
const tokens_vi = [_]Token{
    .{ .bytes = "â", .weight = 3 },
    .{ .bytes = "ă", .weight = 2 },
    .{ .bytes = "ê", .weight = 9 },
    .{ .bytes = "ô", .weight = 20 },
    .{ .bytes = "ơ", .weight = 21 },
    .{ .bytes = "ư", .weight = 28 },
    .{ .bytes = "đ", .weight = 7 },
};

const Row = struct { locale: []const u8, profile: Profile };
const rows = [_]Row{
    .{ .locale = "cs", .profile = .{ .ascii = &ascii_cs, .tokens = &tokens_cs } },
    .{ .locale = "cy", .profile = .{ .ascii = &ascii_cy, .tokens = &tokens_cy } },
    .{ .locale = "da", .profile = .{ .ascii = &ascii_da, .tokens = &tokens_da } },
    .{ .locale = "eo", .profile = .{ .ascii = &ascii_eo, .tokens = &tokens_eo } },
    .{ .locale = "es", .profile = .{ .ascii = &ascii_es, .tokens = &tokens_es } },
    .{ .locale = "et", .profile = .{ .ascii = &ascii_et, .tokens = &tokens_et } },
    .{ .locale = "fi", .profile = .{ .ascii = &ascii_fi, .tokens = &tokens_fi } },
    .{ .locale = "fo", .profile = .{ .ascii = &ascii_fo, .tokens = &tokens_fo } },
    .{ .locale = "hr", .profile = .{ .ascii = &ascii_hr, .tokens = &tokens_hr } },
    .{ .locale = "hu", .profile = .{ .ascii = &ascii_hu, .tokens = &tokens_hu } },
    .{ .locale = "is", .profile = .{ .ascii = &ascii_is, .tokens = &tokens_is } },
    .{ .locale = "lt", .profile = .{ .ascii = &ascii_lt, .tokens = &tokens_lt } },
    .{ .locale = "lv", .profile = .{ .ascii = &ascii_lv, .tokens = &tokens_lv } },
    .{ .locale = "no", .profile = .{ .ascii = &ascii_no, .tokens = &tokens_no } },
    .{ .locale = "pl", .profile = .{ .ascii = &ascii_pl, .tokens = &tokens_pl } },
    .{ .locale = "ro", .profile = .{ .ascii = &ascii_ro, .tokens = &tokens_ro } },
    .{ .locale = "sk", .profile = .{ .ascii = &ascii_sk, .tokens = &tokens_sk } },
    .{ .locale = "sl", .profile = .{ .ascii = &ascii_sl, .tokens = &tokens_sl } },
    .{ .locale = "sq", .profile = .{ .ascii = &ascii_sq, .tokens = &tokens_sq } },
    .{ .locale = "sv", .profile = .{ .ascii = &ascii_sv, .tokens = &tokens_sv } },
    .{ .locale = "vi", .profile = .{ .ascii = &ascii_vi, .tokens = &tokens_vi } },
};

fn asciiLower(byte: u8) u8 {
    return if (byte >= 'A' and byte <= 'Z') byte + ('a' - 'A') else byte;
}

fn language(locale: []const u8) []const u8 {
    const end = std.mem.indexOfScalar(u8, locale, '-') orelse locale.len;
    return locale[0..end];
}

fn orderFolded(a: []const u8, b: []const u8) std.math.Order {
    const n = @min(a.len, b.len);
    for (a[0..n], b[0..n]) |ac, bc| {
        const al = asciiLower(ac);
        const bl = asciiLower(bc);
        if (al < bl) return .lt;
        if (al > bl) return .gt;
    }
    return std.math.order(a.len, b.len);
}

/// Return the standard primary tailoring for a locale's language subtag.
pub fn forLocale(locale: []const u8) ?Profile {
    const lang = language(locale);
    var lo: usize = 0;
    var hi: usize = rows.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (orderFolded(rows[mid].locale, lang)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return rows[mid].profile,
        }
    }
    return null;
}
