// GENERATED by tools/gen_cldr_plurals.mjs from CLDR plurals.json +
// ordinals.json. Per-language ordered (category, condition) plural rules; the
// condition is the LDML plural-rule expression with samples stripped.
const std = @import("std");

pub const Rule = struct { cat: []const u8, cond: []const u8 };
const Loc = struct { k: []const u8, i: u16 };

fn find(loc: []const Loc, sets: []const []const Rule, lang: []const u8) ?[]const Rule {
    var lo: usize = 0;
    var hi: usize = loc.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, loc[mid].k, lang)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return sets[loc[mid].i],
        }
    }
    return null;
}

const card_rs0 = [_]Rule{ .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "other", .cond = "" } };
const card_rs1 = [_]Rule{ .{ .cat = "one", .cond = "n = 0..1" }, .{ .cat = "other", .cond = "" } };
const card_rs2 = [_]Rule{ .{ .cat = "one", .cond = "i = 0 or n = 1" }, .{ .cat = "other", .cond = "" } };
const card_rs3 = [_]Rule{ .{ .cat = "zero", .cond = "n = 0" }, .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "two", .cond = "n = 2" }, .{ .cat = "few", .cond = "n % 100 = 3..10" }, .{ .cat = "many", .cond = "n % 100 = 11..99" }, .{ .cat = "other", .cond = "" } };
const card_rs4 = [_]Rule{ .{ .cat = "one", .cond = "i = 1 and v = 0" }, .{ .cat = "other", .cond = "" } };
const card_rs5 = [_]Rule{ .{ .cat = "one", .cond = "n % 10 = 1 and n % 100 != 11" }, .{ .cat = "few", .cond = "n % 10 = 2..4 and n % 100 != 12..14" }, .{ .cat = "many", .cond = "n % 10 = 0 or n % 10 = 5..9 or n % 100 = 11..14" }, .{ .cat = "other", .cond = "" } };
const card_rs6 = [_]Rule{ .{ .cat = "zero", .cond = "n = 0" }, .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "other", .cond = "" } };
const card_rs7 = [_]Rule{ .{ .cat = "other", .cond = "" } };
const card_rs8 = [_]Rule{ .{ .cat = "one", .cond = "n % 10 = 1 and n % 100 != 11,71,91" }, .{ .cat = "two", .cond = "n % 10 = 2 and n % 100 != 12,72,92" }, .{ .cat = "few", .cond = "n % 10 = 3..4,9 and n % 100 != 10..19,70..79,90..99" }, .{ .cat = "many", .cond = "n != 0 and n % 1000000 = 0" }, .{ .cat = "other", .cond = "" } };
const card_rs9 = [_]Rule{ .{ .cat = "one", .cond = "v = 0 and i % 10 = 1 and i % 100 != 11 or f % 10 = 1 and f % 100 != 11" }, .{ .cat = "few", .cond = "v = 0 and i % 10 = 2..4 and i % 100 != 12..14 or f % 10 = 2..4 and f % 100 != 12..14" }, .{ .cat = "other", .cond = "" } };
const card_rs10 = [_]Rule{ .{ .cat = "one", .cond = "i = 1 and v = 0" }, .{ .cat = "many", .cond = "e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5" }, .{ .cat = "other", .cond = "" } };
const card_rs11 = [_]Rule{ .{ .cat = "one", .cond = "v = 0 and i = 1,2,3 or v = 0 and i % 10 != 4,6,9 or v != 0 and f % 10 != 4,6,9" }, .{ .cat = "other", .cond = "" } };
const card_rs12 = [_]Rule{ .{ .cat = "one", .cond = "i = 1 and v = 0" }, .{ .cat = "few", .cond = "i = 2..4 and v = 0" }, .{ .cat = "many", .cond = "v != 0" }, .{ .cat = "other", .cond = "" } };
const card_rs13 = [_]Rule{ .{ .cat = "zero", .cond = "n = 0" }, .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "two", .cond = "n = 2" }, .{ .cat = "few", .cond = "n = 3" }, .{ .cat = "many", .cond = "n = 6" }, .{ .cat = "other", .cond = "" } };
const card_rs14 = [_]Rule{ .{ .cat = "one", .cond = "n = 1 or t != 0 and i = 0,1" }, .{ .cat = "other", .cond = "" } };
const card_rs15 = [_]Rule{ .{ .cat = "one", .cond = "v = 0 and i % 100 = 1 or f % 100 = 1" }, .{ .cat = "two", .cond = "v = 0 and i % 100 = 2 or f % 100 = 2" }, .{ .cat = "few", .cond = "v = 0 and i % 100 = 3..4 or f % 100 = 3..4" }, .{ .cat = "other", .cond = "" } };
const card_rs16 = [_]Rule{ .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "many", .cond = "e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5" }, .{ .cat = "other", .cond = "" } };
const card_rs17 = [_]Rule{ .{ .cat = "one", .cond = "i = 0,1" }, .{ .cat = "other", .cond = "" } };
const card_rs18 = [_]Rule{ .{ .cat = "one", .cond = "i = 0,1" }, .{ .cat = "many", .cond = "e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5" }, .{ .cat = "other", .cond = "" } };
const card_rs19 = [_]Rule{ .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "two", .cond = "n = 2" }, .{ .cat = "few", .cond = "n = 3..6" }, .{ .cat = "many", .cond = "n = 7..10" }, .{ .cat = "other", .cond = "" } };
const card_rs20 = [_]Rule{ .{ .cat = "one", .cond = "n = 1,11" }, .{ .cat = "two", .cond = "n = 2,12" }, .{ .cat = "few", .cond = "n = 3..10,13..19" }, .{ .cat = "other", .cond = "" } };
const card_rs21 = [_]Rule{ .{ .cat = "one", .cond = "v = 0 and i % 10 = 1" }, .{ .cat = "two", .cond = "v = 0 and i % 10 = 2" }, .{ .cat = "few", .cond = "v = 0 and i % 100 = 0,20,40,60,80" }, .{ .cat = "many", .cond = "v != 0" }, .{ .cat = "other", .cond = "" } };
const card_rs22 = [_]Rule{ .{ .cat = "one", .cond = "i = 1 and v = 0 or i = 0 and v != 0" }, .{ .cat = "two", .cond = "i = 2 and v = 0" }, .{ .cat = "other", .cond = "" } };
const card_rs23 = [_]Rule{ .{ .cat = "one", .cond = "t = 0 and i % 10 = 1 and i % 100 != 11 or t % 10 = 1 and t % 100 != 11" }, .{ .cat = "other", .cond = "" } };
const card_rs24 = [_]Rule{ .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "two", .cond = "n = 2" }, .{ .cat = "other", .cond = "" } };
const card_rs25 = [_]Rule{ .{ .cat = "zero", .cond = "n = 0" }, .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "two", .cond = "n % 100 = 2,22,42,62,82 or n % 1000 = 0 and n % 100000 = 1000..20000,40000,60000,80000 or n != 0 and n % 1000000 = 100000" }, .{ .cat = "few", .cond = "n % 100 = 3,23,43,63,83" }, .{ .cat = "many", .cond = "n != 1 and n % 100 = 1,21,41,61,81" }, .{ .cat = "other", .cond = "" } };
const card_rs26 = [_]Rule{ .{ .cat = "zero", .cond = "n = 0" }, .{ .cat = "one", .cond = "i = 0,1 and n != 0" }, .{ .cat = "other", .cond = "" } };
const card_rs27 = [_]Rule{ .{ .cat = "one", .cond = "n % 10 = 1 and n % 100 != 11..19" }, .{ .cat = "few", .cond = "n % 10 = 2..9 and n % 100 != 11..19" }, .{ .cat = "many", .cond = "f != 0" }, .{ .cat = "other", .cond = "" } };
const card_rs28 = [_]Rule{ .{ .cat = "zero", .cond = "n % 10 = 0 or n % 100 = 11..19 or v = 2 and f % 100 = 11..19" }, .{ .cat = "one", .cond = "n % 10 = 1 and n % 100 != 11 or v = 2 and f % 10 = 1 and f % 100 != 11 or v != 2 and f % 10 = 1" }, .{ .cat = "other", .cond = "" } };
const card_rs29 = [_]Rule{ .{ .cat = "one", .cond = "v = 0 and i % 10 = 1 and i % 100 != 11 or f % 10 = 1 and f % 100 != 11" }, .{ .cat = "other", .cond = "" } };
const card_rs30 = [_]Rule{ .{ .cat = "one", .cond = "i = 1 and v = 0" }, .{ .cat = "few", .cond = "v != 0 or n = 0 or n != 1 and n % 100 = 1..19" }, .{ .cat = "other", .cond = "" } };
const card_rs31 = [_]Rule{ .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "two", .cond = "n = 2" }, .{ .cat = "few", .cond = "n = 0 or n % 100 = 3..10" }, .{ .cat = "many", .cond = "n % 100 = 11..19" }, .{ .cat = "other", .cond = "" } };
const card_rs32 = [_]Rule{ .{ .cat = "one", .cond = "i = 1 and v = 0" }, .{ .cat = "few", .cond = "v = 0 and i % 10 = 2..4 and i % 100 != 12..14" }, .{ .cat = "many", .cond = "v = 0 and i != 1 and i % 10 = 0..1 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 12..14" }, .{ .cat = "other", .cond = "" } };
const card_rs33 = [_]Rule{ .{ .cat = "one", .cond = "i = 0..1" }, .{ .cat = "many", .cond = "e = 0 and i != 0 and i % 1000000 = 0 and v = 0 or e != 0..5" }, .{ .cat = "other", .cond = "" } };
const card_rs34 = [_]Rule{ .{ .cat = "one", .cond = "v = 0 and i % 10 = 1 and i % 100 != 11" }, .{ .cat = "few", .cond = "v = 0 and i % 10 = 2..4 and i % 100 != 12..14" }, .{ .cat = "many", .cond = "v = 0 and i % 10 = 0 or v = 0 and i % 10 = 5..9 or v = 0 and i % 100 = 11..14" }, .{ .cat = "other", .cond = "" } };
const card_rs35 = [_]Rule{ .{ .cat = "one", .cond = "n % 10 = 1 and n % 100 != 11" }, .{ .cat = "two", .cond = "n = 2" }, .{ .cat = "few", .cond = "n != 2 and n % 10 = 2..9 and n % 100 != 11..19" }, .{ .cat = "many", .cond = "f != 0" }, .{ .cat = "other", .cond = "" } };
const card_rs36 = [_]Rule{ .{ .cat = "one", .cond = "i = 0 or n = 1" }, .{ .cat = "few", .cond = "n = 2..10" }, .{ .cat = "other", .cond = "" } };
const card_rs37 = [_]Rule{ .{ .cat = "one", .cond = "n = 0,1 or i = 0 and f = 1" }, .{ .cat = "other", .cond = "" } };
const card_rs38 = [_]Rule{ .{ .cat = "one", .cond = "v = 0 and i % 100 = 1" }, .{ .cat = "two", .cond = "v = 0 and i % 100 = 2" }, .{ .cat = "few", .cond = "v = 0 and i % 100 = 3..4 or v != 0" }, .{ .cat = "other", .cond = "" } };
const card_rs39 = [_]Rule{ .{ .cat = "one", .cond = "n = 0..1 or n = 11..99" }, .{ .cat = "other", .cond = "" } };
const card_sets = [_][]const Rule{ &card_rs0, &card_rs1, &card_rs2, &card_rs3, &card_rs4, &card_rs5, &card_rs6, &card_rs7, &card_rs8, &card_rs9, &card_rs10, &card_rs11, &card_rs12, &card_rs13, &card_rs14, &card_rs15, &card_rs16, &card_rs17, &card_rs18, &card_rs19, &card_rs20, &card_rs21, &card_rs22, &card_rs23, &card_rs24, &card_rs25, &card_rs26, &card_rs27, &card_rs28, &card_rs29, &card_rs30, &card_rs31, &card_rs32, &card_rs33, &card_rs34, &card_rs35, &card_rs36, &card_rs37, &card_rs38, &card_rs39 };
const card_loc = [_]Loc{
    .{ .k = "af", .i = 0 },
    .{ .k = "ak", .i = 1 },
    .{ .k = "am", .i = 2 },
    .{ .k = "an", .i = 0 },
    .{ .k = "ar", .i = 3 },
    .{ .k = "ars", .i = 3 },
    .{ .k = "as", .i = 2 },
    .{ .k = "asa", .i = 0 },
    .{ .k = "ast", .i = 4 },
    .{ .k = "az", .i = 0 },
    .{ .k = "bal", .i = 0 },
    .{ .k = "be", .i = 5 },
    .{ .k = "bem", .i = 0 },
    .{ .k = "bez", .i = 0 },
    .{ .k = "bg", .i = 0 },
    .{ .k = "bho", .i = 1 },
    .{ .k = "blo", .i = 6 },
    .{ .k = "bm", .i = 7 },
    .{ .k = "bn", .i = 2 },
    .{ .k = "bo", .i = 7 },
    .{ .k = "br", .i = 8 },
    .{ .k = "brx", .i = 0 },
    .{ .k = "bs", .i = 9 },
    .{ .k = "ca", .i = 10 },
    .{ .k = "ce", .i = 0 },
    .{ .k = "ceb", .i = 11 },
    .{ .k = "cgg", .i = 0 },
    .{ .k = "chr", .i = 0 },
    .{ .k = "ckb", .i = 0 },
    .{ .k = "cs", .i = 12 },
    .{ .k = "csw", .i = 1 },
    .{ .k = "cv", .i = 6 },
    .{ .k = "cy", .i = 13 },
    .{ .k = "da", .i = 14 },
    .{ .k = "de", .i = 4 },
    .{ .k = "doi", .i = 2 },
    .{ .k = "dsb", .i = 15 },
    .{ .k = "dv", .i = 0 },
    .{ .k = "dz", .i = 7 },
    .{ .k = "ee", .i = 0 },
    .{ .k = "el", .i = 0 },
    .{ .k = "en", .i = 4 },
    .{ .k = "eo", .i = 0 },
    .{ .k = "es", .i = 16 },
    .{ .k = "et", .i = 4 },
    .{ .k = "eu", .i = 0 },
    .{ .k = "fa", .i = 2 },
    .{ .k = "ff", .i = 17 },
    .{ .k = "fi", .i = 4 },
    .{ .k = "fil", .i = 11 },
    .{ .k = "fo", .i = 0 },
    .{ .k = "fr", .i = 18 },
    .{ .k = "fur", .i = 0 },
    .{ .k = "fy", .i = 4 },
    .{ .k = "ga", .i = 19 },
    .{ .k = "gd", .i = 20 },
    .{ .k = "gl", .i = 4 },
    .{ .k = "gsw", .i = 0 },
    .{ .k = "gu", .i = 2 },
    .{ .k = "guw", .i = 1 },
    .{ .k = "gv", .i = 21 },
    .{ .k = "ha", .i = 0 },
    .{ .k = "haw", .i = 0 },
    .{ .k = "he", .i = 22 },
    .{ .k = "hi", .i = 2 },
    .{ .k = "hnj", .i = 7 },
    .{ .k = "hr", .i = 9 },
    .{ .k = "hsb", .i = 15 },
    .{ .k = "hu", .i = 0 },
    .{ .k = "hy", .i = 17 },
    .{ .k = "ia", .i = 4 },
    .{ .k = "id", .i = 7 },
    .{ .k = "ie", .i = 4 },
    .{ .k = "ig", .i = 7 },
    .{ .k = "ii", .i = 7 },
    .{ .k = "io", .i = 4 },
    .{ .k = "is", .i = 23 },
    .{ .k = "it", .i = 10 },
    .{ .k = "iu", .i = 24 },
    .{ .k = "ja", .i = 7 },
    .{ .k = "jbo", .i = 7 },
    .{ .k = "jgo", .i = 0 },
    .{ .k = "jmc", .i = 0 },
    .{ .k = "jv", .i = 7 },
    .{ .k = "jw", .i = 7 },
    .{ .k = "ka", .i = 0 },
    .{ .k = "kab", .i = 17 },
    .{ .k = "kaj", .i = 0 },
    .{ .k = "kcg", .i = 0 },
    .{ .k = "kde", .i = 7 },
    .{ .k = "kea", .i = 7 },
    .{ .k = "kk", .i = 0 },
    .{ .k = "kkj", .i = 0 },
    .{ .k = "kl", .i = 0 },
    .{ .k = "km", .i = 7 },
    .{ .k = "kn", .i = 2 },
    .{ .k = "ko", .i = 7 },
    .{ .k = "kok", .i = 2 },
    .{ .k = "kok-latn", .i = 2 },
    .{ .k = "ks", .i = 0 },
    .{ .k = "ksb", .i = 0 },
    .{ .k = "ksh", .i = 6 },
    .{ .k = "ku", .i = 0 },
    .{ .k = "kw", .i = 25 },
    .{ .k = "ky", .i = 0 },
    .{ .k = "lag", .i = 26 },
    .{ .k = "lb", .i = 0 },
    .{ .k = "lg", .i = 0 },
    .{ .k = "lij", .i = 4 },
    .{ .k = "lkt", .i = 7 },
    .{ .k = "lld", .i = 10 },
    .{ .k = "ln", .i = 1 },
    .{ .k = "lo", .i = 7 },
    .{ .k = "lt", .i = 27 },
    .{ .k = "lv", .i = 28 },
    .{ .k = "mas", .i = 0 },
    .{ .k = "mg", .i = 1 },
    .{ .k = "mgo", .i = 0 },
    .{ .k = "mk", .i = 29 },
    .{ .k = "ml", .i = 0 },
    .{ .k = "mn", .i = 0 },
    .{ .k = "mo", .i = 30 },
    .{ .k = "mr", .i = 0 },
    .{ .k = "ms", .i = 7 },
    .{ .k = "mt", .i = 31 },
    .{ .k = "my", .i = 7 },
    .{ .k = "nah", .i = 0 },
    .{ .k = "naq", .i = 24 },
    .{ .k = "nb", .i = 0 },
    .{ .k = "nd", .i = 0 },
    .{ .k = "ne", .i = 0 },
    .{ .k = "nl", .i = 4 },
    .{ .k = "nn", .i = 0 },
    .{ .k = "nnh", .i = 0 },
    .{ .k = "no", .i = 0 },
    .{ .k = "nqo", .i = 7 },
    .{ .k = "nr", .i = 0 },
    .{ .k = "nso", .i = 1 },
    .{ .k = "ny", .i = 0 },
    .{ .k = "nyn", .i = 0 },
    .{ .k = "om", .i = 0 },
    .{ .k = "or", .i = 0 },
    .{ .k = "os", .i = 0 },
    .{ .k = "osa", .i = 7 },
    .{ .k = "pa", .i = 1 },
    .{ .k = "pap", .i = 0 },
    .{ .k = "pcm", .i = 2 },
    .{ .k = "pl", .i = 32 },
    .{ .k = "prg", .i = 28 },
    .{ .k = "ps", .i = 0 },
    .{ .k = "pt", .i = 33 },
    .{ .k = "pt-pt", .i = 10 },
    .{ .k = "rm", .i = 0 },
    .{ .k = "ro", .i = 30 },
    .{ .k = "rof", .i = 0 },
    .{ .k = "ru", .i = 34 },
    .{ .k = "rwk", .i = 0 },
    .{ .k = "sah", .i = 7 },
    .{ .k = "saq", .i = 0 },
    .{ .k = "sat", .i = 24 },
    .{ .k = "sc", .i = 4 },
    .{ .k = "scn", .i = 10 },
    .{ .k = "sd", .i = 0 },
    .{ .k = "sdh", .i = 0 },
    .{ .k = "se", .i = 24 },
    .{ .k = "seh", .i = 0 },
    .{ .k = "ses", .i = 7 },
    .{ .k = "sg", .i = 7 },
    .{ .k = "sgs", .i = 35 },
    .{ .k = "sh", .i = 9 },
    .{ .k = "shi", .i = 36 },
    .{ .k = "si", .i = 37 },
    .{ .k = "sk", .i = 12 },
    .{ .k = "sl", .i = 38 },
    .{ .k = "sma", .i = 24 },
    .{ .k = "smi", .i = 24 },
    .{ .k = "smj", .i = 24 },
    .{ .k = "smn", .i = 24 },
    .{ .k = "sms", .i = 24 },
    .{ .k = "sn", .i = 0 },
    .{ .k = "so", .i = 0 },
    .{ .k = "sq", .i = 0 },
    .{ .k = "sr", .i = 9 },
    .{ .k = "ss", .i = 0 },
    .{ .k = "ssy", .i = 0 },
    .{ .k = "st", .i = 0 },
    .{ .k = "su", .i = 7 },
    .{ .k = "sv", .i = 4 },
    .{ .k = "sw", .i = 4 },
    .{ .k = "syr", .i = 0 },
    .{ .k = "ta", .i = 0 },
    .{ .k = "te", .i = 0 },
    .{ .k = "teo", .i = 0 },
    .{ .k = "th", .i = 7 },
    .{ .k = "ti", .i = 1 },
    .{ .k = "tig", .i = 0 },
    .{ .k = "tk", .i = 0 },
    .{ .k = "tl", .i = 11 },
    .{ .k = "tn", .i = 0 },
    .{ .k = "to", .i = 7 },
    .{ .k = "tpi", .i = 7 },
    .{ .k = "tr", .i = 0 },
    .{ .k = "ts", .i = 0 },
    .{ .k = "tzm", .i = 39 },
    .{ .k = "ug", .i = 0 },
    .{ .k = "uk", .i = 34 },
    .{ .k = "und", .i = 7 },
    .{ .k = "ur", .i = 4 },
    .{ .k = "uz", .i = 0 },
    .{ .k = "ve", .i = 0 },
    .{ .k = "vec", .i = 10 },
    .{ .k = "vi", .i = 7 },
    .{ .k = "vo", .i = 0 },
    .{ .k = "vun", .i = 0 },
    .{ .k = "wa", .i = 1 },
    .{ .k = "wae", .i = 0 },
    .{ .k = "wo", .i = 7 },
    .{ .k = "xh", .i = 0 },
    .{ .k = "xog", .i = 0 },
    .{ .k = "yi", .i = 4 },
    .{ .k = "yo", .i = 7 },
    .{ .k = "yue", .i = 7 },
    .{ .k = "zh", .i = 7 },
    .{ .k = "zu", .i = 2 },
};
const ord_rs0 = [_]Rule{ .{ .cat = "other", .cond = "" } };
const ord_rs1 = [_]Rule{ .{ .cat = "one", .cond = "n = 1,5,7,8,9,10" }, .{ .cat = "two", .cond = "n = 2,3" }, .{ .cat = "few", .cond = "n = 4" }, .{ .cat = "many", .cond = "n = 6" }, .{ .cat = "other", .cond = "" } };
const ord_rs2 = [_]Rule{ .{ .cat = "one", .cond = "i % 10 = 1,2,5,7,8 or i % 100 = 20,50,70,80" }, .{ .cat = "few", .cond = "i % 10 = 3,4 or i % 1000 = 100,200,300,400,500,600,700,800,900" }, .{ .cat = "many", .cond = "i = 0 or i % 10 = 6 or i % 100 = 40,60,90" }, .{ .cat = "other", .cond = "" } };
const ord_rs3 = [_]Rule{ .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "other", .cond = "" } };
const ord_rs4 = [_]Rule{ .{ .cat = "few", .cond = "n % 10 = 2,3 and n % 100 != 12,13" }, .{ .cat = "other", .cond = "" } };
const ord_rs5 = [_]Rule{ .{ .cat = "zero", .cond = "i = 0" }, .{ .cat = "one", .cond = "i = 1" }, .{ .cat = "few", .cond = "i = 2,3,4,5,6" }, .{ .cat = "other", .cond = "" } };
const ord_rs6 = [_]Rule{ .{ .cat = "one", .cond = "n = 1,3" }, .{ .cat = "two", .cond = "n = 2" }, .{ .cat = "few", .cond = "n = 4" }, .{ .cat = "other", .cond = "" } };
const ord_rs7 = [_]Rule{ .{ .cat = "zero", .cond = "n = 0,7,8,9" }, .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "two", .cond = "n = 2" }, .{ .cat = "few", .cond = "n = 3,4" }, .{ .cat = "many", .cond = "n = 5,6" }, .{ .cat = "other", .cond = "" } };
const ord_rs8 = [_]Rule{ .{ .cat = "one", .cond = "n % 10 = 1 and n % 100 != 11" }, .{ .cat = "two", .cond = "n % 10 = 2 and n % 100 != 12" }, .{ .cat = "few", .cond = "n % 10 = 3 and n % 100 != 13" }, .{ .cat = "other", .cond = "" } };
const ord_rs9 = [_]Rule{ .{ .cat = "one", .cond = "n = 1,11" }, .{ .cat = "two", .cond = "n = 2,12" }, .{ .cat = "few", .cond = "n = 3,13" }, .{ .cat = "other", .cond = "" } };
const ord_rs10 = [_]Rule{ .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "two", .cond = "n = 2,3" }, .{ .cat = "few", .cond = "n = 4" }, .{ .cat = "many", .cond = "n = 6" }, .{ .cat = "other", .cond = "" } };
const ord_rs11 = [_]Rule{ .{ .cat = "one", .cond = "n = 1,5" }, .{ .cat = "other", .cond = "" } };
const ord_rs12 = [_]Rule{ .{ .cat = "many", .cond = "n = 11,8,80,800" }, .{ .cat = "other", .cond = "" } };
const ord_rs13 = [_]Rule{ .{ .cat = "one", .cond = "i = 1" }, .{ .cat = "many", .cond = "i = 0 or i % 100 = 2..20,40,60,80" }, .{ .cat = "other", .cond = "" } };
const ord_rs14 = [_]Rule{ .{ .cat = "many", .cond = "n % 10 = 6 or n % 10 = 9 or n % 10 = 0 and n != 0" }, .{ .cat = "other", .cond = "" } };
const ord_rs15 = [_]Rule{ .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "two", .cond = "n = 2,3" }, .{ .cat = "few", .cond = "n = 4" }, .{ .cat = "other", .cond = "" } };
const ord_rs16 = [_]Rule{ .{ .cat = "one", .cond = "n = 1..4 or n % 100 = 1..4,21..24,41..44,61..64,81..84" }, .{ .cat = "many", .cond = "n = 5 or n % 100 = 5" }, .{ .cat = "other", .cond = "" } };
const ord_rs17 = [_]Rule{ .{ .cat = "many", .cond = "n = 11,8,80..89,800..899" }, .{ .cat = "other", .cond = "" } };
const ord_rs18 = [_]Rule{ .{ .cat = "one", .cond = "i % 10 = 1 and i % 100 != 11" }, .{ .cat = "two", .cond = "i % 10 = 2 and i % 100 != 12" }, .{ .cat = "many", .cond = "i % 10 = 7,8 and i % 100 != 17,18" }, .{ .cat = "other", .cond = "" } };
const ord_rs19 = [_]Rule{ .{ .cat = "one", .cond = "n = 1..4" }, .{ .cat = "other", .cond = "" } };
const ord_rs20 = [_]Rule{ .{ .cat = "one", .cond = "n = 1,5,7..9" }, .{ .cat = "two", .cond = "n = 2,3" }, .{ .cat = "few", .cond = "n = 4" }, .{ .cat = "many", .cond = "n = 6" }, .{ .cat = "other", .cond = "" } };
const ord_rs21 = [_]Rule{ .{ .cat = "one", .cond = "n = 1" }, .{ .cat = "many", .cond = "n % 10 = 4 and n % 100 != 14" }, .{ .cat = "other", .cond = "" } };
const ord_rs22 = [_]Rule{ .{ .cat = "one", .cond = "n % 10 = 1,2 and n % 100 != 11,12" }, .{ .cat = "other", .cond = "" } };
const ord_rs23 = [_]Rule{ .{ .cat = "few", .cond = "n % 10 = 6,9 or n = 10" }, .{ .cat = "other", .cond = "" } };
const ord_rs24 = [_]Rule{ .{ .cat = "few", .cond = "n % 10 = 3 and n % 100 != 13" }, .{ .cat = "other", .cond = "" } };
const ord_sets = [_][]const Rule{ &ord_rs0, &ord_rs1, &ord_rs2, &ord_rs3, &ord_rs4, &ord_rs5, &ord_rs6, &ord_rs7, &ord_rs8, &ord_rs9, &ord_rs10, &ord_rs11, &ord_rs12, &ord_rs13, &ord_rs14, &ord_rs15, &ord_rs16, &ord_rs17, &ord_rs18, &ord_rs19, &ord_rs20, &ord_rs21, &ord_rs22, &ord_rs23, &ord_rs24 };
const ord_loc = [_]Loc{
    .{ .k = "af", .i = 0 },
    .{ .k = "am", .i = 0 },
    .{ .k = "an", .i = 0 },
    .{ .k = "ar", .i = 0 },
    .{ .k = "as", .i = 1 },
    .{ .k = "ast", .i = 0 },
    .{ .k = "az", .i = 2 },
    .{ .k = "bal", .i = 3 },
    .{ .k = "be", .i = 4 },
    .{ .k = "bg", .i = 0 },
    .{ .k = "blo", .i = 5 },
    .{ .k = "bn", .i = 1 },
    .{ .k = "bs", .i = 0 },
    .{ .k = "ca", .i = 6 },
    .{ .k = "ce", .i = 0 },
    .{ .k = "cs", .i = 0 },
    .{ .k = "cv", .i = 0 },
    .{ .k = "cy", .i = 7 },
    .{ .k = "da", .i = 0 },
    .{ .k = "de", .i = 0 },
    .{ .k = "dsb", .i = 0 },
    .{ .k = "el", .i = 0 },
    .{ .k = "en", .i = 8 },
    .{ .k = "es", .i = 0 },
    .{ .k = "et", .i = 0 },
    .{ .k = "eu", .i = 0 },
    .{ .k = "fa", .i = 0 },
    .{ .k = "fi", .i = 0 },
    .{ .k = "fil", .i = 3 },
    .{ .k = "fr", .i = 3 },
    .{ .k = "fy", .i = 0 },
    .{ .k = "ga", .i = 3 },
    .{ .k = "gd", .i = 9 },
    .{ .k = "gl", .i = 0 },
    .{ .k = "gsw", .i = 0 },
    .{ .k = "gu", .i = 10 },
    .{ .k = "he", .i = 0 },
    .{ .k = "hi", .i = 10 },
    .{ .k = "hr", .i = 0 },
    .{ .k = "hsb", .i = 0 },
    .{ .k = "hu", .i = 11 },
    .{ .k = "hy", .i = 3 },
    .{ .k = "ia", .i = 0 },
    .{ .k = "id", .i = 0 },
    .{ .k = "ie", .i = 0 },
    .{ .k = "is", .i = 0 },
    .{ .k = "it", .i = 12 },
    .{ .k = "ja", .i = 0 },
    .{ .k = "ka", .i = 13 },
    .{ .k = "kk", .i = 14 },
    .{ .k = "km", .i = 0 },
    .{ .k = "kn", .i = 0 },
    .{ .k = "ko", .i = 0 },
    .{ .k = "kok", .i = 15 },
    .{ .k = "kok-latn", .i = 15 },
    .{ .k = "kw", .i = 16 },
    .{ .k = "ky", .i = 0 },
    .{ .k = "lij", .i = 17 },
    .{ .k = "lld", .i = 12 },
    .{ .k = "lo", .i = 3 },
    .{ .k = "lt", .i = 0 },
    .{ .k = "lv", .i = 0 },
    .{ .k = "mk", .i = 18 },
    .{ .k = "ml", .i = 0 },
    .{ .k = "mn", .i = 0 },
    .{ .k = "mo", .i = 3 },
    .{ .k = "mr", .i = 15 },
    .{ .k = "ms", .i = 3 },
    .{ .k = "my", .i = 0 },
    .{ .k = "nb", .i = 0 },
    .{ .k = "ne", .i = 19 },
    .{ .k = "nl", .i = 0 },
    .{ .k = "no", .i = 0 },
    .{ .k = "or", .i = 20 },
    .{ .k = "pa", .i = 0 },
    .{ .k = "pl", .i = 0 },
    .{ .k = "prg", .i = 0 },
    .{ .k = "ps", .i = 0 },
    .{ .k = "pt", .i = 0 },
    .{ .k = "ro", .i = 3 },
    .{ .k = "ru", .i = 0 },
    .{ .k = "sc", .i = 12 },
    .{ .k = "scn", .i = 17 },
    .{ .k = "sd", .i = 0 },
    .{ .k = "sh", .i = 0 },
    .{ .k = "si", .i = 0 },
    .{ .k = "sk", .i = 0 },
    .{ .k = "sl", .i = 0 },
    .{ .k = "sq", .i = 21 },
    .{ .k = "sr", .i = 0 },
    .{ .k = "sv", .i = 22 },
    .{ .k = "sw", .i = 0 },
    .{ .k = "ta", .i = 0 },
    .{ .k = "te", .i = 0 },
    .{ .k = "th", .i = 0 },
    .{ .k = "tk", .i = 23 },
    .{ .k = "tl", .i = 3 },
    .{ .k = "tpi", .i = 0 },
    .{ .k = "tr", .i = 0 },
    .{ .k = "uk", .i = 24 },
    .{ .k = "und", .i = 0 },
    .{ .k = "ur", .i = 0 },
    .{ .k = "uz", .i = 0 },
    .{ .k = "vec", .i = 12 },
    .{ .k = "vi", .i = 3 },
    .{ .k = "yue", .i = 0 },
    .{ .k = "zh", .i = 0 },
    .{ .k = "zu", .i = 0 },
};

/// Cardinal plural rules for a language subtag (lowercased), or null.
pub fn cardinal(lang: []const u8) ?[]const Rule {
    return find(&card_loc, &card_sets, lang);
}
/// Ordinal plural rules for a language subtag (lowercased), or null.
pub fn ordinal(lang: []const u8) ?[]const Rule {
    return find(&ord_loc, &ord_sets, lang);
}
