// GENERATED by tools/gen_cldr_tzalias.mjs from CLDR bcp47/timezone.json.
// Deprecated/alias -u-tz- value (lowercased) -> canonical BCP-47 tz type.
const std = @import("std");

const Row = struct { k: []const u8, v: []const u8 };
const rows = [_]Row{
    .{ .k = "aqams", .v = "aqmcm" },
    .{ .k = "aukns", .v = "auhba" },
    .{ .k = "caffs", .v = "cawnp" },
    .{ .k = "camtr", .v = "cator" },
    .{ .k = "canpg", .v = "cator" },
    .{ .k = "capnt", .v = "caiql" },
    .{ .k = "cathu", .v = "cator" },
    .{ .k = "cayzf", .v = "caedm" },
    .{ .k = "cet", .v = "bebru" },
    .{ .k = "cnckg", .v = "cnsha" },
    .{ .k = "cnhrb", .v = "cnsha" },
    .{ .k = "cnkhg", .v = "cnurc" },
    .{ .k = "cst6cdt", .v = "uschi" },
    .{ .k = "cuba", .v = "cuhav" },
    .{ .k = "eet", .v = "grath" },
    .{ .k = "egypt", .v = "egcai" },
    .{ .k = "eire", .v = "iedub" },
    .{ .k = "est", .v = "papty" },
    .{ .k = "est5edt", .v = "usnyc" },
    .{ .k = "factory", .v = "unk" },
    .{ .k = "gaza", .v = "gazastrp" },
    .{ .k = "gb", .v = "gblon" },
    .{ .k = "gmt0", .v = "gmt" },
    .{ .k = "hongkong", .v = "hkhkg" },
    .{ .k = "hst", .v = "ushnl" },
    .{ .k = "iceland", .v = "isrey" },
    .{ .k = "iran", .v = "irthr" },
    .{ .k = "israel", .v = "jeruslm" },
    .{ .k = "jamaica", .v = "jmkin" },
    .{ .k = "japan", .v = "jptyo" },
    .{ .k = "libya", .v = "lytip" },
    .{ .k = "met", .v = "bebru" },
    .{ .k = "mncoq", .v = "mnuln" },
    .{ .k = "mst", .v = "usphx" },
    .{ .k = "mst7mdt", .v = "usden" },
    .{ .k = "mxstis", .v = "mxtij" },
    .{ .k = "navajo", .v = "usden" },
    .{ .k = "nz", .v = "nzakl" },
    .{ .k = "poland", .v = "plwaw" },
    .{ .k = "portugal", .v = "ptlis" },
    .{ .k = "prc", .v = "cnsha" },
    .{ .k = "pst8pdt", .v = "uslax" },
    .{ .k = "roc", .v = "twtpe" },
    .{ .k = "rok", .v = "krsel" },
    .{ .k = "turkey", .v = "trist" },
    .{ .k = "uaozh", .v = "uaiev" },
    .{ .k = "uauzh", .v = "uaiev" },
    .{ .k = "uct", .v = "utc" },
    .{ .k = "umjon", .v = "ushnl" },
    .{ .k = "usnavajo", .v = "usden" },
    .{ .k = "wet", .v = "ptlis" },
    .{ .k = "zulu", .v = "utc" },
};

/// The canonical BCP-47 time-zone type for a -u-tz- value (lowercased), or null.
pub fn canonical(value: []const u8) ?[]const u8 {
    var lo: usize = 0;
    var hi: usize = rows.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, rows[mid].k, value)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return rows[mid].v,
        }
    }
    return null;
}
