// GENERATED by tools/gen_cldr_numbers.mjs from CLDR-JSON — do not edit.
const std = @import("std");

pub const NumSym = struct {
    decimal: []const u8,
    group: []const u8,
    percent: []const u8,
    minus: []const u8,
    nan: []const u8,
    infinity: []const u8,
    symbol_before: bool,
    /// Whether the locale's accounting currency format wraps negatives in
    /// parentheses ("(¤#,##0.00)") rather than using a minus sign.
    accounting_parens: bool,
};

const Row = struct { loc: []const u8, sym: NumSym };
const table = [_]Row{
    .{ .loc = "ar", .sym = .{ .decimal = ".", .group = ",", .percent = "\xe2\x80\x8e%\xe2\x80\x8e", .minus = "\xe2\x80\x8e-", .nan = "\xd9\x84\xd9\x8a\xd8\xb3\xc2\xa0\xd8\xb1\xd9\x82\xd9\x85\xd9\x8b\xd8\xa7", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "bg", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "ca", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "cs", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "cy", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "da", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "de", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "de-CH", .sym = .{ .decimal = ".", .group = "'", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = false } },
    .{ .loc = "el", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "en", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "en-CA", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "en-GB", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "es", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "es-419", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = false } },
    .{ .loc = "et", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "\xe2\x88\x92", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "fa", .sym = .{ .decimal = "\xd9\xab", .group = "\xd9\xac", .percent = "\xd9\xaa", .minus = "\xe2\x80\x8e\xe2\x88\x92", .nan = "\xd9\x86\xd8\xa7\xd8\xb9\xd8\xaf\xd8\xaf", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "fi", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "\xe2\x88\x92", .nan = "ep\xc3\xa4luku", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "fr", .sym = .{ .decimal = ",", .group = "\xe2\x80\xaf", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "fr-CA", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "fr-CH", .sym = .{ .decimal = ",", .group = "'", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "ga", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "Nuimh", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "he", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "\xe2\x80\x8e-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "hi", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = false } },
    .{ .loc = "hr", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "\xe2\x88\x92", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "hu", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "id", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = false } },
    .{ .loc = "is", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "it", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "ja", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "ko", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "lt", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "\xe2\x88\x92", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "lv", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "-", .nan = "NS", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "mt", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = false } },
    .{ .loc = "nb", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "\xe2\x88\x92", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "nl", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "pl", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "pt", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = false } },
    .{ .loc = "ro", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "ru", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "-", .nan = "\xd0\xbd\xd0\xb5\xc2\xa0\xd1\x87\xd0\xb8\xd1\x81\xd0\xbb\xd0\xbe", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "sk", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "sl", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "\xe2\x88\x92", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "sr", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = true } },
    .{ .loc = "sv", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "\xe2\x88\x92", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "th", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "tr", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "uk", .sym = .{ .decimal = ",", .group = "\xc2\xa0", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "vi", .sym = .{ .decimal = ",", .group = ".", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = false, .accounting_parens = false } },
    .{ .loc = "zh", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "zh-HK", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "\xe9\x9d\x9e\xe6\x95\xb8\xe5\x80\xbc", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "zh-Hant", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "\xe9\x9d\x9e\xe6\x95\xb8\xe5\x80\xbc", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "zh-MO", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "\xe9\x9d\x9e\xe6\x95\xb8\xe5\x80\xbc", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
    .{ .loc = "zh-TW", .sym = .{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "\xe9\x9d\x9e\xe6\x95\xb8\xe5\x80\xbc", .infinity = "\xe2\x88\x9e", .symbol_before = true, .accounting_parens = true } },
};

const default_sym = NumSym{ .decimal = ".", .group = ",", .percent = "%", .minus = "-", .nan = "NaN", .infinity = "â", .symbol_before = true, .accounting_parens = true };

/// Look up a locale's number symbols, falling back from "xx-YY" to "xx", then
/// to the en-style default.
pub fn lookup(locale: []const u8) NumSym {
    var probe = locale;
    while (true) {
        for (table) |row| if (std.mem.eql(u8, row.loc, probe)) return row.sym;
        if (std.mem.lastIndexOfScalar(u8, probe, '-')) |i| {
            probe = probe[0..i];
        } else break;
    }
    return default_sym;
}
