//! GENERATED from CLDR en units.json (see tools/gen_units.py). English
//! unit patterns for Intl.NumberFormat style:"unit": the text that follows
//! the number, per width (long/short/narrow) and plural (one/other), plus
//! the per-unit denominator suffix for compound X-per-Y composition.

pub const Unit = struct {
    id: []const u8,
    l1: []const u8, lo: []const u8, // long one/other
    s1: []const u8, so: []const u8, // short one/other
    n1: []const u8, no: []const u8, // narrow one/other
    pl: []const u8, ps: []const u8, pn: []const u8, // per-suffix long/short/narrow (denominator)
};

pub const units = [_]Unit{
    .{ .id = "acre", .l1 = " acre", .lo = " acres", .s1 = " ac", .so = " ac", .n1 = "ac", .no = "ac", .pl = "", .ps = "", .pn = "" },
    .{ .id = "acre-foot", .l1 = " acre-foot", .lo = " acre-feet", .s1 = " ac ft", .so = " ac ft", .n1 = "ac ft", .no = "ac ft", .pl = "", .ps = "", .pn = "" },
    .{ .id = "ampere", .l1 = " ampere", .lo = " amperes", .s1 = " A", .so = " A", .n1 = "A", .no = "A", .pl = "", .ps = "", .pn = "" },
    .{ .id = "arc-minute", .l1 = " arcminute", .lo = " arcminutes", .s1 = " arcmin", .so = " arcmins", .n1 = "′", .no = "′", .pl = "", .ps = "", .pn = "" },
    .{ .id = "arc-second", .l1 = " arcsecond", .lo = " arcseconds", .s1 = " arcsec", .so = " arcsecs", .n1 = "″", .no = "″", .pl = "", .ps = "", .pn = "" },
    .{ .id = "astronomical-unit", .l1 = " astronomical unit", .lo = " astronomical units", .s1 = " au", .so = " au", .n1 = "au", .no = "au", .pl = "", .ps = "", .pn = "" },
    .{ .id = "atmosphere", .l1 = " atmosphere", .lo = " atmospheres", .s1 = " atm", .so = " atm", .n1 = "atm", .no = "atm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "bar", .l1 = " bar", .lo = " bars", .s1 = " bar", .so = " bar", .n1 = "bar", .no = "bar", .pl = "", .ps = "", .pn = "" },
    .{ .id = "barrel", .l1 = " barrel", .lo = " barrels", .s1 = " bbl", .so = " bbl", .n1 = "bbl", .no = "bbl", .pl = "", .ps = "", .pn = "" },
    .{ .id = "beaufort", .l1 = "", .lo = "", .s1 = "", .so = "", .n1 = "", .no = "", .pl = "", .ps = "", .pn = "" },
    .{ .id = "becquerel", .l1 = " becquerel", .lo = " becquerels", .s1 = " Bq", .so = " Bq", .n1 = " Bq", .no = " Bq", .pl = "", .ps = "", .pn = "" },
    .{ .id = "bit", .l1 = " bit", .lo = " bits", .s1 = " bit", .so = " bit", .n1 = "bit", .no = "bit", .pl = "", .ps = "", .pn = "" },
    .{ .id = "british-thermal-unit", .l1 = " British thermal unit", .lo = " British thermal units", .s1 = " Btu", .so = " Btu", .n1 = "Btu", .no = "Btu", .pl = "", .ps = "", .pn = "" },
    .{ .id = "british-thermal-unit-it", .l1 = " British thermal unit [IT]", .lo = " British thermal units [IT]", .s1 = " BTU-IT", .so = " BT-IT", .n1 = " BTU-IT", .no = " BT-IT", .pl = "", .ps = "", .pn = "" },
    .{ .id = "bu-jp", .l1 = " bu [JP]", .lo = " bu [JP]", .s1 = " bu [JP]", .so = " bu [JP]", .n1 = " bu [JP]", .no = " bu [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "bushel", .l1 = " bushel", .lo = " bushels", .s1 = " bu", .so = " bu", .n1 = "bu", .no = "bu", .pl = "", .ps = "", .pn = "" },
    .{ .id = "byte", .l1 = " byte", .lo = " bytes", .s1 = " byte", .so = " byte", .n1 = "B", .no = "B", .pl = "", .ps = "", .pn = "" },
    .{ .id = "calorie", .l1 = " calorie", .lo = " calories", .s1 = " cal", .so = " cal", .n1 = "cal", .no = "cal", .pl = "", .ps = "", .pn = "" },
    .{ .id = "calorie-it", .l1 = " calorie [IT]", .lo = " calories [IT]", .s1 = " cal-IT", .so = " cal-IT", .n1 = " cal-IT", .no = " cal-IT", .pl = "", .ps = "", .pn = "" },
    .{ .id = "candela", .l1 = " candela", .lo = " candela", .s1 = " cd", .so = " cd", .n1 = "cd", .no = "cd", .pl = "", .ps = "", .pn = "" },
    .{ .id = "carat", .l1 = " carat", .lo = " carats", .s1 = " CD", .so = " CD", .n1 = "CD", .no = "CD", .pl = "", .ps = "", .pn = "" },
    .{ .id = "celsius", .l1 = " degree Celsius", .lo = " degrees Celsius", .s1 = "°C", .so = "°C", .n1 = "°C", .no = "°C", .pl = "", .ps = "", .pn = "" },
    .{ .id = "centiliter", .l1 = " centiliter", .lo = " centiliters", .s1 = " cL", .so = " cL", .n1 = "cL", .no = "cL", .pl = "", .ps = "", .pn = "" },
    .{ .id = "centimeter", .l1 = " centimeter", .lo = " centimeters", .s1 = " cm", .so = " cm", .n1 = "cm", .no = "cm", .pl = " per centimeter", .ps = "/cm", .pn = "/cm" },
    .{ .id = "century", .l1 = " century", .lo = " centuries", .s1 = " c", .so = " c", .n1 = "c", .no = "c", .pl = "", .ps = "", .pn = "" },
    .{ .id = "chain", .l1 = " chain", .lo = " chains", .s1 = " ch", .so = " ch", .n1 = " ch", .no = " ch", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cho", .l1 = " cho [JP]", .lo = " cho [JP]", .s1 = " cho [JP]", .so = " cho [JP]", .n1 = " cho [JP]", .no = " cho [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "coulomb", .l1 = " coulomb", .lo = " coulombs", .s1 = " C", .so = " C", .n1 = " C", .no = " C", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cubic-centimeter", .l1 = " cubic centimeter", .lo = " cubic centimeters", .s1 = " cm³", .so = " cm³", .n1 = "cm³", .no = "cm³", .pl = " per cubic centimeter", .ps = "/cm³", .pn = "/cm³" },
    .{ .id = "cubic-foot", .l1 = " cubic foot", .lo = " cubic feet", .s1 = " ft³", .so = " ft³", .n1 = "ft³", .no = "ft³", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cubic-inch", .l1 = " cubic inch", .lo = " cubic inches", .s1 = " in³", .so = " in³", .n1 = "in³", .no = "in³", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cubic-kilometer", .l1 = " cubic kilometer", .lo = " cubic kilometers", .s1 = " km³", .so = " km³", .n1 = "km³", .no = "km³", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cubic-meter", .l1 = " cubic meter", .lo = " cubic meters", .s1 = " m³", .so = " m³", .n1 = "m³", .no = "m³", .pl = " per cubic meter", .ps = "/m³", .pn = "/m³" },
    .{ .id = "cubic-mile", .l1 = " cubic mile", .lo = " cubic miles", .s1 = " mi³", .so = " mi³", .n1 = "mi³", .no = "mi³", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cubic-yard", .l1 = " cubic yard", .lo = " cubic yards", .s1 = " yd³", .so = " yd³", .n1 = "yd³", .no = "yd³", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cup", .l1 = " cup", .lo = " cups", .s1 = " c", .so = " c", .n1 = "c", .no = "c", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cup-imperial", .l1 = " cup Imperial", .lo = " cups Imperial", .s1 = " cup Imp.", .so = " cup Imp.", .n1 = " cup Imp.", .no = " cup Imp.", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cup-jp", .l1 = " cup [JP]", .lo = " cup [JP]", .s1 = " cup [JP]", .so = " cup [JP]", .n1 = " cup [JP]", .no = " cup [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "cup-metric", .l1 = " metric cup", .lo = " metric cups", .s1 = " mc", .so = " mc", .n1 = "mc", .no = "mc", .pl = "", .ps = "", .pn = "" },
    .{ .id = "dalton", .l1 = " dalton", .lo = " daltons", .s1 = " Da", .so = " Da", .n1 = "Da", .no = "Da", .pl = "", .ps = "", .pn = "" },
    .{ .id = "day", .l1 = " day", .lo = " days", .s1 = " day", .so = " days", .n1 = "d", .no = "d", .pl = " per day", .ps = "/d", .pn = "/d" },
    .{ .id = "decade", .l1 = " decade", .lo = " decades", .s1 = " dec", .so = " dec", .n1 = "dec", .no = "dec", .pl = "", .ps = "", .pn = "" },
    .{ .id = "deciliter", .l1 = " deciliter", .lo = " deciliters", .s1 = " dL", .so = " dL", .n1 = "dL", .no = "dL", .pl = "", .ps = "", .pn = "" },
    .{ .id = "decimeter", .l1 = " decimeter", .lo = " decimeters", .s1 = " dm", .so = " dm", .n1 = "dm", .no = "dm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "degree", .l1 = " degree", .lo = " degrees", .s1 = " deg", .so = " deg", .n1 = "°", .no = "°", .pl = "", .ps = "", .pn = "" },
    .{ .id = "dessert-spoon", .l1 = " dessert spoon", .lo = " dessert spoons", .s1 = " dsp", .so = " dsp", .n1 = "dsp", .no = "dsp", .pl = "", .ps = "", .pn = "" },
    .{ .id = "dessert-spoon-imperial", .l1 = " Imp. dessert spoon", .lo = " Imp. dessert spoons", .s1 = " dsp-Imp.", .so = " dsp-Imp.", .n1 = "dsp-Imp", .no = "dsp-Imp", .pl = "", .ps = "", .pn = "" },
    .{ .id = "dot", .l1 = " dot", .lo = " dots", .s1 = " dot", .so = " dots", .n1 = "dot", .no = "dot", .pl = "", .ps = "", .pn = "" },
    .{ .id = "dot-per-centimeter", .l1 = " dot per centimeter", .lo = " dots per centimeter", .s1 = " dpcm", .so = " dpcm", .n1 = "dpcm", .no = "dpcm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "dot-per-inch", .l1 = " dot per inch", .lo = " dots per inch", .s1 = " dpi", .so = " dpi", .n1 = "dpi", .no = "dpi", .pl = "", .ps = "", .pn = "" },
    .{ .id = "dram", .l1 = " dram", .lo = " drams", .s1 = " dram", .so = " drams", .n1 = "fl.dr.", .no = "fl.dr.", .pl = "", .ps = "", .pn = "" },
    .{ .id = "drop", .l1 = " drop", .lo = " drops", .s1 = " dr", .so = " drdrops", .n1 = "dr", .no = "dr", .pl = "", .ps = "", .pn = "" },
    .{ .id = "dunam", .l1 = " dunam", .lo = " dunams", .s1 = " dunam", .so = " dunam", .n1 = "dunam", .no = "dunam", .pl = "", .ps = "", .pn = "" },
    .{ .id = "earth-mass", .l1 = " Earth mass", .lo = " Earth masses", .s1 = " M⊕", .so = " M⊕", .n1 = "M⊕", .no = "M⊕", .pl = "", .ps = "", .pn = "" },
    .{ .id = "earth-radius", .l1 = " earth radius", .lo = " earth radius", .s1 = " R⊕", .so = " R⊕", .n1 = "R⊕", .no = "R⊕", .pl = "", .ps = "", .pn = "" },
    .{ .id = "electronvolt", .l1 = " electronvolt", .lo = " electronvolts", .s1 = " eV", .so = " eV", .n1 = "eV", .no = "eV", .pl = "", .ps = "", .pn = "" },
    .{ .id = "em", .l1 = " em", .lo = " ems", .s1 = " em", .so = " em", .n1 = "em", .no = "em", .pl = "", .ps = "", .pn = "" },
    .{ .id = "fahrenheit", .l1 = " degree Fahrenheit", .lo = " degrees Fahrenheit", .s1 = "°F", .so = "°F", .n1 = "°", .no = "°", .pl = "", .ps = "", .pn = "" },
    .{ .id = "farad", .l1 = " farad", .lo = " farads", .s1 = " F", .so = " F", .n1 = " F", .no = " F", .pl = "", .ps = "", .pn = "" },
    .{ .id = "fathom", .l1 = " fathom", .lo = " fathoms", .s1 = " fth", .so = " fth", .n1 = "fth", .no = "fth", .pl = "", .ps = "", .pn = "" },
    .{ .id = "fluid-ounce", .l1 = " fluid ounce", .lo = " fluid ounces", .s1 = " fl oz", .so = " fl oz", .n1 = "fl oz", .no = "fl oz", .pl = "", .ps = "", .pn = "" },
    .{ .id = "fluid-ounce-imperial", .l1 = " Imp. fluid ounce", .lo = " Imp. fluid ounces", .s1 = " fl oz Imp.", .so = " fl oz Imp.", .n1 = "fl oz Im", .no = "fl oz Im", .pl = "", .ps = "", .pn = "" },
    .{ .id = "fluid-ounce-metric", .l1 = " metric fluid ounce", .lo = " metric fluid ounces", .s1 = " fl oz m.", .so = " fl oz m.", .n1 = " fl oz m.", .no = " fl oz m.", .pl = "", .ps = "", .pn = "" },
    .{ .id = "foodcalorie", .l1 = " Calorie", .lo = " Calories", .s1 = " Cal", .so = " Cal", .n1 = "Cal", .no = "Cal", .pl = "", .ps = "", .pn = "" },
    .{ .id = "foot", .l1 = " foot", .lo = " feet", .s1 = " ft", .so = " ft", .n1 = "′", .no = "′", .pl = " per foot", .ps = "/ft", .pn = "/ft" },
    .{ .id = "fortnight", .l1 = " fortnight", .lo = " fortnights", .s1 = " fw", .so = " fw", .n1 = " fw", .no = " fw", .pl = "", .ps = "", .pn = "" },
    .{ .id = "fun", .l1 = " fun [JP]", .lo = " fun [JP]", .s1 = " fun [JP]", .so = " fun [JP]", .n1 = " fun [JP]", .no = " fun [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "furlong", .l1 = " furlong", .lo = " furlongs", .s1 = " fur", .so = " fur", .n1 = "fur", .no = "fur", .pl = "", .ps = "", .pn = "" },
    .{ .id = "g-force", .l1 = " g-force", .lo = " g-force", .s1 = " G", .so = " G", .n1 = "G", .no = "Gs", .pl = "", .ps = "", .pn = "" },
    .{ .id = "gallon", .l1 = " gallon", .lo = " gallons", .s1 = " gal", .so = " gal", .n1 = "gal", .no = "gal", .pl = " per gallon", .ps = "/gal US", .pn = "/gal" },
    .{ .id = "gallon-imperial", .l1 = " Imp. gallon", .lo = " Imp. gallons", .s1 = " gal Imp.", .so = " gal Imp.", .n1 = "gal-Im", .no = "gal-Im", .pl = " per Imp. gallon", .ps = "/galImp", .pn = "/galIm" },
    .{ .id = "gasoline-energy-density", .l1 = " of gasoline equivalent", .lo = " of gasoline equivalent", .s1 = " gas-equiv", .so = " gas-equiv", .n1 = "gas-equiv", .no = "gas-equiv", .pl = "", .ps = "", .pn = "" },
    .{ .id = "generic", .l1 = " degree temperature", .lo = " degrees temperature", .s1 = "°", .so = "°", .n1 = "°", .no = "°", .pl = "", .ps = "", .pn = "" },
    .{ .id = "gigabit", .l1 = " gigabit", .lo = " gigabits", .s1 = " Gb", .so = " Gb", .n1 = "Gb", .no = "Gb", .pl = "", .ps = "", .pn = "" },
    .{ .id = "gigabyte", .l1 = " gigabyte", .lo = " gigabytes", .s1 = " GB", .so = " GB", .n1 = "GB", .no = "GB", .pl = "", .ps = "", .pn = "" },
    .{ .id = "gigahertz", .l1 = " gigahertz", .lo = " gigahertz", .s1 = " GHz", .so = " GHz", .n1 = "GHz", .no = "GHz", .pl = "", .ps = "", .pn = "" },
    .{ .id = "gigawatt", .l1 = " gigawatt", .lo = " gigawatts", .s1 = " GW", .so = " GW", .n1 = "GW", .no = "GW", .pl = "", .ps = "", .pn = "" },
    .{ .id = "grain", .l1 = " grain", .lo = " grains", .s1 = " gr", .so = " gr", .n1 = "gr", .no = "gr", .pl = "", .ps = "", .pn = "" },
    .{ .id = "gram", .l1 = " gram", .lo = " grams", .s1 = " g", .so = " g", .n1 = "g", .no = "g", .pl = " per gram", .ps = "/g", .pn = "/g" },
    .{ .id = "gray", .l1 = " gray", .lo = " grays", .s1 = " Gy", .so = " Gy", .n1 = " Gy", .no = " Gy", .pl = "", .ps = "", .pn = "" },
    .{ .id = "hectare", .l1 = " hectare", .lo = " hectares", .s1 = " ha", .so = " ha", .n1 = "ha", .no = "ha", .pl = "", .ps = "", .pn = "" },
    .{ .id = "hectoliter", .l1 = " hectoliter", .lo = " hectoliters", .s1 = " hL", .so = " hL", .n1 = "hL", .no = "hL", .pl = "", .ps = "", .pn = "" },
    .{ .id = "hectopascal", .l1 = " hectopascal", .lo = " hectopascals", .s1 = " hPa", .so = " hPa", .n1 = "hPa", .no = "hPa", .pl = "", .ps = "", .pn = "" },
    .{ .id = "henry", .l1 = " henry", .lo = " henrys", .s1 = " H", .so = " H", .n1 = " H", .no = " H", .pl = "", .ps = "", .pn = "" },
    .{ .id = "hertz", .l1 = " hertz", .lo = " hertz", .s1 = " Hz", .so = " Hz", .n1 = "Hz", .no = "Hz", .pl = "", .ps = "", .pn = "" },
    .{ .id = "horsepower", .l1 = " horsepower", .lo = " horsepower", .s1 = " hp", .so = " hp", .n1 = "hp", .no = "hp", .pl = "", .ps = "", .pn = "" },
    .{ .id = "hour", .l1 = " hour", .lo = " hours", .s1 = " hr", .so = " hr", .n1 = "h", .no = "h", .pl = " per hour", .ps = "/h", .pn = "/h" },
    .{ .id = "inch", .l1 = " inch", .lo = " inches", .s1 = " in", .so = " in", .n1 = "″", .no = "″", .pl = " per inch", .ps = "/in", .pn = "/in" },
    .{ .id = "inch-ofhg", .l1 = " inch of mercury", .lo = " inches of mercury", .s1 = " inHg", .so = " inHg", .n1 = "″ Hg", .no = "″ Hg", .pl = "", .ps = "", .pn = "" },
    .{ .id = "item", .l1 = " item", .lo = " items", .s1 = " item", .so = " items", .n1 = "item", .no = "items", .pl = "", .ps = "", .pn = "" },
    .{ .id = "jigger", .l1 = " jigger", .lo = " jiggers", .s1 = " jigger", .so = " jiggers", .n1 = "jigger", .no = "jigger", .pl = "", .ps = "", .pn = "" },
    .{ .id = "jo-jp", .l1 = " jo [JP]", .lo = " jo [JP]", .s1 = " jo [JP]", .so = " jo [JP]", .n1 = " jo [JP]", .no = " jo [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "joule", .l1 = " joule", .lo = " joules", .s1 = " J", .so = " J", .n1 = "J", .no = "J", .pl = "", .ps = "", .pn = "" },
    .{ .id = "karat", .l1 = " karat", .lo = " karats", .s1 = " kt", .so = " kt", .n1 = "kt", .no = "kt", .pl = "", .ps = "", .pn = "" },
    .{ .id = "katal", .l1 = " katal", .lo = " katals", .s1 = " kat", .so = " kat", .n1 = " kat", .no = " kat", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kelvin", .l1 = " kelvin", .lo = " kelvins", .s1 = " K", .so = " K", .n1 = "K", .no = "K", .pl = "", .ps = "", .pn = "" },
    .{ .id = "ken", .l1 = " ken [JP]", .lo = " ken [JP]", .s1 = " ken [JP]", .so = " ken [JP]", .n1 = " ken [JP]", .no = " ken [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilobit", .l1 = " kilobit", .lo = " kilobits", .s1 = " kb", .so = " kb", .n1 = "kb", .no = "kb", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilobyte", .l1 = " kilobyte", .lo = " kilobytes", .s1 = " kB", .so = " kB", .n1 = "kB", .no = "kB", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilocalorie", .l1 = " kilocalorie", .lo = " kilocalories", .s1 = " kcal", .so = " kcal", .n1 = "kcal", .no = "kcal", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilogram", .l1 = " kilogram", .lo = " kilograms", .s1 = " kg", .so = " kg", .n1 = "kg", .no = "kg", .pl = " per kilogram", .ps = "/kg", .pn = "/kg" },
    .{ .id = "kilogram-force", .l1 = " kilogram-force", .lo = " kilograms-force", .s1 = " kgf", .so = " kgf", .n1 = " kgf", .no = " kgf", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilohertz", .l1 = " kilohertz", .lo = " kilohertz", .s1 = " kHz", .so = " kHz", .n1 = "kHz", .no = "kHz", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilojoule", .l1 = " kilojoule", .lo = " kilojoules", .s1 = " kJ", .so = " kJ", .n1 = "kJ", .no = "kJ", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilometer", .l1 = " kilometer", .lo = " kilometers", .s1 = " km", .so = " km", .n1 = "km", .no = "km", .pl = " per kilometer", .ps = "/km", .pn = "/km" },
    .{ .id = "kilometer-per-hour", .l1 = " kilometer per hour", .lo = " kilometers per hour", .s1 = " km/h", .so = " km/h", .n1 = "km/h", .no = "km/h", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilopascal", .l1 = " kilopascal", .lo = " kilopascals", .s1 = " kPa", .so = " kPa", .n1 = "kPa", .no = "kPa", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilowatt", .l1 = " kilowatt", .lo = " kilowatts", .s1 = " kW", .so = " kW", .n1 = "kW", .no = "kW", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilowatt-hour", .l1 = " kilowatt hour", .lo = " kilowatt-hours", .s1 = " kWh", .so = " kWh", .n1 = "kWh", .no = "kWh", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kilowatt-hour-per-100-kilometer", .l1 = " kilowatt-hour per 100 kilometers", .lo = " kilowatt-hours per 100 kilometers", .s1 = " kWh/100km", .so = " kWh/100km", .n1 = "kWh/100km", .no = "kWh/100km", .pl = "", .ps = "", .pn = "" },
    .{ .id = "knot", .l1 = " knot", .lo = " knots", .s1 = " kn", .so = " kn", .n1 = "kn", .no = "kn", .pl = "", .ps = "", .pn = "" },
    .{ .id = "koku", .l1 = " koku [JP]", .lo = " koku [JP]", .s1 = " koku [JP]", .so = " koku [JP]", .n1 = " koku [JP]", .no = " koku [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "kosaji", .l1 = " kosaji [JP]", .lo = " kosaji [JP]", .s1 = " kosaji [JP]", .so = " kosaji [JP]", .n1 = " kosaji [JP]", .no = " kosaji [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "light-speed", .l1 = " light", .lo = " light", .s1 = " light", .so = " light", .n1 = "light", .no = "light", .pl = "", .ps = "", .pn = "" },
    .{ .id = "light-year", .l1 = " light year", .lo = " light years", .s1 = " ly", .so = " ly", .n1 = "ly", .no = "ly", .pl = "", .ps = "", .pn = "" },
    .{ .id = "liter", .l1 = " liter", .lo = " liters", .s1 = " L", .so = " L", .n1 = "L", .no = "L", .pl = " per liter", .ps = "/L", .pn = "/L" },
    .{ .id = "liter-per-100-kilometer", .l1 = " liter per 100 kilometers", .lo = " liters per 100 kilometers", .s1 = " L/100 km", .so = " L/100 km", .n1 = "L/100km", .no = "L/100km", .pl = "", .ps = "", .pn = "" },
    .{ .id = "liter-per-kilometer", .l1 = " liter per kilometer", .lo = " liters per kilometer", .s1 = " L/km", .so = " L/km", .n1 = "L/km", .no = "L/km", .pl = "", .ps = "", .pn = "" },
    .{ .id = "lumen", .l1 = " lumen", .lo = " lumen", .s1 = " lm", .so = " lm", .n1 = "lm", .no = "lm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "lux", .l1 = " lux", .lo = " lux", .s1 = " lx", .so = " lx", .n1 = "lx", .no = "lx", .pl = "", .ps = "", .pn = "" },
    .{ .id = "megabit", .l1 = " megabit", .lo = " megabits", .s1 = " Mb", .so = " Mb", .n1 = "Mb", .no = "Mb", .pl = "", .ps = "", .pn = "" },
    .{ .id = "megabyte", .l1 = " megabyte", .lo = " megabytes", .s1 = " MB", .so = " MB", .n1 = "MB", .no = "MB", .pl = "", .ps = "", .pn = "" },
    .{ .id = "megahertz", .l1 = " megahertz", .lo = " megahertz", .s1 = " MHz", .so = " MHz", .n1 = "MHz", .no = "MHz", .pl = "", .ps = "", .pn = "" },
    .{ .id = "megaliter", .l1 = " megaliter", .lo = " megaliters", .s1 = " ML", .so = " ML", .n1 = "ML", .no = "ML", .pl = "", .ps = "", .pn = "" },
    .{ .id = "megapascal", .l1 = " megapascal", .lo = " megapascals", .s1 = " MPa", .so = " MPa", .n1 = "MPa", .no = "MPa", .pl = "", .ps = "", .pn = "" },
    .{ .id = "megapixel", .l1 = " megapixel", .lo = " megapixels", .s1 = " MP", .so = " MP", .n1 = "MP", .no = "MP", .pl = "", .ps = "", .pn = "" },
    .{ .id = "megawatt", .l1 = " megawatt", .lo = " megawatts", .s1 = " MW", .so = " MW", .n1 = "MW", .no = "MW", .pl = "", .ps = "", .pn = "" },
    .{ .id = "meter", .l1 = " meter", .lo = " meters", .s1 = " m", .so = " m", .n1 = "m", .no = "m", .pl = " per meter", .ps = "/m", .pn = "/m" },
    .{ .id = "meter-per-second", .l1 = " meter per second", .lo = " meters per second", .s1 = " m/s", .so = " m/s", .n1 = "m/s", .no = "m/s", .pl = "", .ps = "", .pn = "" },
    .{ .id = "meter-per-square-second", .l1 = " meter per second squared", .lo = " meters per second squared", .s1 = " m/s²", .so = " m/s²", .n1 = "m/s²", .no = "m/s²", .pl = "", .ps = "", .pn = "" },
    .{ .id = "microgram", .l1 = " microgram", .lo = " micrograms", .s1 = " μg", .so = " μg", .n1 = "μg", .no = "μg", .pl = "", .ps = "", .pn = "" },
    .{ .id = "micrometer", .l1 = " micrometer", .lo = " micrometers", .s1 = " μm", .so = " μm", .n1 = "μm", .no = "μm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "microsecond", .l1 = " microsecond", .lo = " microseconds", .s1 = " μs", .so = " μs", .n1 = "μs", .no = "μs", .pl = "", .ps = "", .pn = "" },
    .{ .id = "mile", .l1 = " mile", .lo = " miles", .s1 = " mi", .so = " mi", .n1 = "mi", .no = "mi", .pl = "", .ps = "", .pn = "" },
    .{ .id = "mile-per-gallon", .l1 = " mile per gallon", .lo = " miles per gallon", .s1 = " mpg", .so = " mpg", .n1 = "mpg", .no = "mpg", .pl = "", .ps = "", .pn = "" },
    .{ .id = "mile-per-gallon-imperial", .l1 = " mile per Imp. gallon", .lo = " miles per Imp. gallon", .s1 = " mpg Imp.", .so = " mpg Imp.", .n1 = "m/gUK", .no = "m/gUK", .pl = "", .ps = "", .pn = "" },
    .{ .id = "mile-per-hour", .l1 = " mile per hour", .lo = " miles per hour", .s1 = " mph", .so = " mph", .n1 = "mph", .no = "mph", .pl = "", .ps = "", .pn = "" },
    .{ .id = "mile-scandinavian", .l1 = " mile-scandinavian", .lo = " miles-scandinavian", .s1 = " smi", .so = " smi", .n1 = "smi", .no = "smi", .pl = "", .ps = "", .pn = "" },
    .{ .id = "milliampere", .l1 = " milliampere", .lo = " milliamperes", .s1 = " mA", .so = " mA", .n1 = "mA", .no = "mA", .pl = "", .ps = "", .pn = "" },
    .{ .id = "millibar", .l1 = " millibar", .lo = " millibars", .s1 = " mbar", .so = " mbar", .n1 = "mb", .no = "mb", .pl = "", .ps = "", .pn = "" },
    .{ .id = "milligram", .l1 = " milligram", .lo = " milligrams", .s1 = " mg", .so = " mg", .n1 = "mg", .no = "mg", .pl = "", .ps = "", .pn = "" },
    .{ .id = "milligram-ofglucose-per-deciliter", .l1 = " milligram per deciliter", .lo = " milligrams per deciliter", .s1 = " mg/dL", .so = " mg/dL", .n1 = "mg/dL", .no = "mg/dL", .pl = "", .ps = "", .pn = "" },
    .{ .id = "milliliter", .l1 = " milliliter", .lo = " milliliters", .s1 = " mL", .so = " mL", .n1 = "mL", .no = "mL", .pl = "", .ps = "", .pn = "" },
    .{ .id = "millimeter", .l1 = " millimeter", .lo = " millimeters", .s1 = " mm", .so = " mm", .n1 = "mm", .no = "mm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "millimeter-ofhg", .l1 = " millimeter of mercury", .lo = " millimeters of mercury", .s1 = " mmHg", .so = " mmHg", .n1 = "mmHg", .no = "mmHg", .pl = "", .ps = "", .pn = "" },
    .{ .id = "millimole-per-liter", .l1 = " millimole per liter", .lo = " millimoles per liter", .s1 = " mmol/L", .so = " mmol/L", .n1 = "mmol/L", .no = "mmol/L", .pl = "", .ps = "", .pn = "" },
    .{ .id = "millisecond", .l1 = " millisecond", .lo = " milliseconds", .s1 = " ms", .so = " ms", .n1 = "ms", .no = "ms", .pl = "", .ps = "", .pn = "" },
    .{ .id = "milliwatt", .l1 = " milliwatt", .lo = " milliwatts", .s1 = " mW", .so = " mW", .n1 = "mW", .no = "mW", .pl = "", .ps = "", .pn = "" },
    .{ .id = "minute", .l1 = " minute", .lo = " minutes", .s1 = " min", .so = " min", .n1 = "m", .no = "m", .pl = " per minute", .ps = "/min", .pn = "/min" },
    .{ .id = "mole", .l1 = " mole", .lo = " moles", .s1 = " mol", .so = " mol", .n1 = "mol", .no = "mol", .pl = "", .ps = "", .pn = "" },
    .{ .id = "month", .l1 = " month", .lo = " months", .s1 = " mth", .so = " mths", .n1 = "m", .no = "m", .pl = " per month", .ps = "/m", .pn = "/m" },
    .{ .id = "nanometer", .l1 = " nanometer", .lo = " nanometers", .s1 = " nm", .so = " nm", .n1 = "nm", .no = "nm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "nanosecond", .l1 = " nanosecond", .lo = " nanoseconds", .s1 = " ns", .so = " ns", .n1 = "ns", .no = "ns", .pl = "", .ps = "", .pn = "" },
    .{ .id = "nautical-mile", .l1 = " nautical mile", .lo = " nautical miles", .s1 = " nmi", .so = " nmi", .n1 = "nmi", .no = "nmi", .pl = "", .ps = "", .pn = "" },
    .{ .id = "newton", .l1 = " newton", .lo = " newtons", .s1 = " N", .so = " N", .n1 = "N", .no = "N", .pl = "", .ps = "", .pn = "" },
    .{ .id = "newton-meter", .l1 = " newton-meter", .lo = " newton-meters", .s1 = " N⋅m", .so = " N⋅m", .n1 = "N⋅m", .no = "N⋅m", .pl = "", .ps = "", .pn = "" },
    .{ .id = "night", .l1 = " night", .lo = " nights", .s1 = " night", .so = " nights", .n1 = "night", .no = "nights", .pl = " per night", .ps = "/night", .pn = "/night" },
    .{ .id = "ofglucose", .l1 = " of glucose", .lo = " of glucose", .s1 = " Glc", .so = " Glc", .n1 = " Glc", .no = " Glc", .pl = "", .ps = "", .pn = "" },
    .{ .id = "ofhg", .l1 = " of mercury", .lo = " of mercury", .s1 = " of Hg", .so = " of Hg", .n1 = " of Hg", .no = " of Hg", .pl = "", .ps = "", .pn = "" },
    .{ .id = "ohm", .l1 = " ohm", .lo = " ohms", .s1 = " Ω", .so = " Ω", .n1 = "Ω", .no = "Ω", .pl = "", .ps = "", .pn = "" },
    .{ .id = "osaji", .l1 = " osaji [JP]", .lo = " osaji [JP]", .s1 = " osaji [JP]", .so = " osaji [JP]", .n1 = " osaji [JP]", .no = " osaji [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "ounce", .l1 = " ounce", .lo = " ounces", .s1 = " oz", .so = " oz", .n1 = "oz", .no = "oz", .pl = " per ounce", .ps = "/oz", .pn = "/oz" },
    .{ .id = "ounce-troy", .l1 = " troy ounce", .lo = " troy ounces", .s1 = " oz t", .so = " oz t", .n1 = "oz t", .no = "oz t", .pl = "", .ps = "", .pn = "" },
    .{ .id = "parsec", .l1 = " parsec", .lo = " parsecs", .s1 = " pc", .so = " pc", .n1 = "pc", .no = "pc", .pl = "", .ps = "", .pn = "" },
    .{ .id = "part", .l1 = " part", .lo = " parts", .s1 = " part", .so = " part", .n1 = " part", .no = " part", .pl = "", .ps = "", .pn = "" },
    .{ .id = "part-per-1e6", .l1 = " part per million", .lo = " parts per million", .s1 = " ppm", .so = " ppm", .n1 = "ppm", .no = "ppm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "part-per-1e9", .l1 = " part per billion", .lo = " parts per billion", .s1 = " ppb", .so = " ppb", .n1 = "ppb", .no = "ppb", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pascal", .l1 = " pascal", .lo = " pascals", .s1 = " Pa", .so = " Pa", .n1 = "Pa", .no = "Pa", .pl = "", .ps = "", .pn = "" },
    .{ .id = "percent", .l1 = " percent", .lo = " percent", .s1 = "%", .so = "%", .n1 = "%", .no = "%", .pl = "", .ps = "", .pn = "" },
    .{ .id = "permille", .l1 = " permille", .lo = " permille", .s1 = "‰", .so = "‰", .n1 = "‰", .no = "‰", .pl = "", .ps = "", .pn = "" },
    .{ .id = "permyriad", .l1 = " permyriad", .lo = " permyriad", .s1 = "‱", .so = "‱", .n1 = "‱", .no = "‱", .pl = "", .ps = "", .pn = "" },
    .{ .id = "petabyte", .l1 = " petabyte", .lo = " petabytes", .s1 = " PB", .so = " PB", .n1 = "PB", .no = "PB", .pl = "", .ps = "", .pn = "" },
    .{ .id = "picometer", .l1 = " picometer", .lo = " picometers", .s1 = " pm", .so = " pm", .n1 = "pm", .no = "pm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pinch", .l1 = " pinch", .lo = " pinches", .s1 = " pn", .so = " pn", .n1 = "pn", .no = "pn", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pint", .l1 = " pint", .lo = " pints", .s1 = " pt", .so = " pt", .n1 = "pt", .no = "pt", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pint-imperial", .l1 = " pint Imperial", .lo = " pints Imperial", .s1 = " pt Imp.", .so = " pt Imp.", .n1 = " pt Imp.", .no = " pt Imp.", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pint-metric", .l1 = " metric pint", .lo = " metric pints", .s1 = " mpt", .so = " mpt", .n1 = "mpt", .no = "mpt", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pixel", .l1 = " pixel", .lo = " pixels", .s1 = " px", .so = " px", .n1 = "px", .no = "px", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pixel-per-centimeter", .l1 = " pixel per centimeter", .lo = " pixels per centimeter", .s1 = " ppcm", .so = " ppcm", .n1 = "ppcm", .no = "ppcm", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pixel-per-inch", .l1 = " pixel per inch", .lo = " pixels per inch", .s1 = " ppi", .so = " ppi", .n1 = "ppi", .no = "ppi", .pl = "", .ps = "", .pn = "" },
    .{ .id = "point", .l1 = " point", .lo = " points", .s1 = " pt", .so = " pt", .n1 = "pt", .no = "pt", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pound", .l1 = " pound", .lo = " pounds", .s1 = " lb", .so = " lb", .n1 = "#", .no = "#", .pl = " per pound", .ps = "/lb", .pn = "/lb" },
    .{ .id = "pound-force", .l1 = " pound of force", .lo = " pounds of force", .s1 = " lbf", .so = " lbf", .n1 = "lbf", .no = "lbf", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pound-force-foot", .l1 = " pound-force-foot", .lo = " pound-force-feet", .s1 = " lbf⋅ft", .so = " lbf⋅ft", .n1 = "lbf⋅ft", .no = "lbf⋅ft", .pl = "", .ps = "", .pn = "" },
    .{ .id = "pound-force-per-square-inch", .l1 = " pound-force per square inch", .lo = " pounds-force per square inch", .s1 = " psi", .so = " psi", .n1 = "psi", .no = "psi", .pl = "", .ps = "", .pn = "" },
    .{ .id = "quart", .l1 = " quart", .lo = " quarts", .s1 = " qt", .so = " qt", .n1 = "qt", .no = "qt", .pl = "", .ps = "", .pn = "" },
    .{ .id = "quart-imperial", .l1 = " Imp. quart", .lo = " Imp. quarts", .s1 = " qt-Imp.", .so = " qt-Imp.", .n1 = "qt-Imp.", .no = "qt-Imp.", .pl = "", .ps = "", .pn = "" },
    .{ .id = "quarter", .l1 = " quarter", .lo = " quarters", .s1 = " qtr", .so = " qtrs", .n1 = "q", .no = "q", .pl = "/q", .ps = "/q", .pn = "/q" },
    .{ .id = "radian", .l1 = " radian", .lo = " radians", .s1 = " rad", .so = " rad", .n1 = "rad", .no = "rad", .pl = "", .ps = "", .pn = "" },
    .{ .id = "rankine", .l1 = " rankine", .lo = " rankines", .s1 = " °R", .so = " °R", .n1 = " °R", .no = " °R", .pl = "", .ps = "", .pn = "" },
    .{ .id = "revolution", .l1 = " revolution", .lo = " revolutions", .s1 = " rev", .so = " rev", .n1 = "rev", .no = "rev", .pl = "", .ps = "", .pn = "" },
    .{ .id = "ri-jp", .l1 = " ri [JP]", .lo = " ri [JP]", .s1 = " ri [JP]", .so = " ri [JP]", .n1 = " ri [JP]", .no = " ri [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "rin", .l1 = " rin [JP]", .lo = " rin [JP]", .s1 = " rin [JP]", .so = " rin [JP]", .n1 = " rin [JP]", .no = " rin [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "rod", .l1 = " rod", .lo = " rods", .s1 = " rd", .so = " rd", .n1 = " rd", .no = " rd", .pl = "", .ps = "", .pn = "" },
    .{ .id = "sai", .l1 = " sai [JP]", .lo = " sai [JP]", .s1 = " sai [JP]", .so = " sai [JP]", .n1 = " sai [JP]", .no = " sai [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "se-jp", .l1 = " se [JP]", .lo = " se [JP]", .s1 = " se [JP]", .so = " se [JP]", .n1 = " se [JP]", .no = " se [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "second", .l1 = " second", .lo = " seconds", .s1 = " sec", .so = " sec", .n1 = "s", .no = "s", .pl = " per second", .ps = "/s", .pn = "/s" },
    .{ .id = "shaku", .l1 = " shaku [volume, JP]", .lo = " shaku [volume, JP]", .s1 = " shaku [vol, JP]", .so = " shaku [vol, JP]", .n1 = " shaku [vol, JP]", .no = " shaku [vol, JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "shaku-cloth", .l1 = " shaku [cloth, JP]", .lo = " shaku [cloth, JP]", .s1 = " shaku [cloth, JP]", .so = " shaku [cloth, JP]", .n1 = " shaku [cloth, JP]", .no = " shaku [cloth, JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "shaku-length", .l1 = " shaku [JP]", .lo = " shaku [JP]", .s1 = " shaku [JP]", .so = " shaku [JP]", .n1 = " shaku [JP]", .no = " shaku [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "siemens", .l1 = " siemens", .lo = " siemens", .s1 = " S", .so = " S", .n1 = " S", .no = " S", .pl = "", .ps = "", .pn = "" },
    .{ .id = "sievert", .l1 = " sievert", .lo = " sieverts", .s1 = " Sv", .so = " Sv", .n1 = " Sv", .no = " Sv", .pl = "", .ps = "", .pn = "" },
    .{ .id = "slug", .l1 = " slug", .lo = " slugs", .s1 = " slug", .so = " slug", .n1 = " slug", .no = " slug", .pl = "", .ps = "", .pn = "" },
    .{ .id = "solar-luminosity", .l1 = " solar luminosity", .lo = " solar luminosities", .s1 = " L☉", .so = " L☉", .n1 = "L☉", .no = "L☉", .pl = "", .ps = "", .pn = "" },
    .{ .id = "solar-mass", .l1 = " solar mass", .lo = " solar masses", .s1 = " M☉", .so = " M☉", .n1 = "M☉", .no = "M☉", .pl = "", .ps = "", .pn = "" },
    .{ .id = "solar-radius", .l1 = " solar radius", .lo = " solar radii", .s1 = " R☉", .so = " R☉", .n1 = "R☉", .no = "R☉", .pl = "", .ps = "", .pn = "" },
    .{ .id = "square-centimeter", .l1 = " square centimeter", .lo = " square centimeters", .s1 = " cm²", .so = " cm²", .n1 = "cm²", .no = "cm²", .pl = " per square centimeter", .ps = "/cm²", .pn = "/cm²" },
    .{ .id = "square-foot", .l1 = " square foot", .lo = " square feet", .s1 = " sq ft", .so = " sq ft", .n1 = "ft²", .no = "ft²", .pl = "", .ps = "", .pn = "" },
    .{ .id = "square-inch", .l1 = " square inch", .lo = " square inches", .s1 = " in²", .so = " in²", .n1 = "in²", .no = "in²", .pl = " per square inch", .ps = "/in²", .pn = "/in²" },
    .{ .id = "square-kilometer", .l1 = " square kilometer", .lo = " square kilometers", .s1 = " km²", .so = " km²", .n1 = "km²", .no = "km²", .pl = " per square kilometer", .ps = "/km²", .pn = "/km²" },
    .{ .id = "square-meter", .l1 = " square meter", .lo = " square meters", .s1 = " m²", .so = " m²", .n1 = "m²", .no = "m²", .pl = " per square meter", .ps = "/m²", .pn = "/m²" },
    .{ .id = "square-mile", .l1 = " square mile", .lo = " square miles", .s1 = " sq mi", .so = " sq mi", .n1 = "mi²", .no = "mi²", .pl = " per square mile", .ps = "/mi²", .pn = "/mi²" },
    .{ .id = "square-yard", .l1 = " square yard", .lo = " square yards", .s1 = " yd²", .so = " yd²", .n1 = "yd²", .no = "yd²", .pl = "", .ps = "", .pn = "" },
    .{ .id = "steradian", .l1 = " steradian", .lo = " steradians", .s1 = " sr", .so = " sr", .n1 = " sr", .no = " sr", .pl = "", .ps = "", .pn = "" },
    .{ .id = "stone", .l1 = " stone", .lo = " stones", .s1 = " st", .so = " st", .n1 = "st", .no = "st", .pl = "", .ps = "", .pn = "" },
    .{ .id = "sun", .l1 = " sun [JP]", .lo = " sun [JP]", .s1 = " sun [JP]", .so = " sun [JP]", .n1 = " sun [JP]", .no = " sun [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "tablespoon", .l1 = " tablespoon", .lo = " tablespoons", .s1 = " tbsp", .so = " tbsp", .n1 = "tbsp", .no = "tbsp", .pl = "", .ps = "", .pn = "" },
    .{ .id = "teaspoon", .l1 = " teaspoon", .lo = " teaspoons", .s1 = " tsp", .so = " tsp", .n1 = "tsp", .no = "tsp", .pl = "", .ps = "", .pn = "" },
    .{ .id = "terabit", .l1 = " terabit", .lo = " terabits", .s1 = " Tb", .so = " Tb", .n1 = "Tb", .no = "Tb", .pl = "", .ps = "", .pn = "" },
    .{ .id = "terabyte", .l1 = " terabyte", .lo = " terabytes", .s1 = " TB", .so = " TB", .n1 = "TB", .no = "TB", .pl = "", .ps = "", .pn = "" },
    .{ .id = "tesla", .l1 = " tesla", .lo = " teslas", .s1 = " T", .so = " T", .n1 = " T", .no = " T", .pl = "", .ps = "", .pn = "" },
    .{ .id = "therm-us", .l1 = " US therm", .lo = " US therms", .s1 = " US therm", .so = " US therms", .n1 = "US therm", .no = "US therms", .pl = "", .ps = "", .pn = "" },
    .{ .id = "to-jp", .l1 = " to [JP]", .lo = " to [JP]", .s1 = " to [JP]", .so = " to [JP]", .n1 = " to [JP]", .no = " to [JP]", .pl = "", .ps = "", .pn = "" },
    .{ .id = "ton", .l1 = " ton", .lo = " tons", .s1 = " tn", .so = " tn", .n1 = "tn", .no = "tn", .pl = "", .ps = "", .pn = "" },
    .{ .id = "tonne", .l1 = " metric ton", .lo = " metric tons", .s1 = " t", .so = " t", .n1 = "t", .no = "t", .pl = "", .ps = "", .pn = "" },
    .{ .id = "volt", .l1 = " volt", .lo = " volts", .s1 = " V", .so = " V", .n1 = "V", .no = "V", .pl = "", .ps = "", .pn = "" },
    .{ .id = "watt", .l1 = " watt", .lo = " watts", .s1 = " W", .so = " W", .n1 = "W", .no = "W", .pl = "", .ps = "", .pn = "" },
    .{ .id = "weber", .l1 = " weber", .lo = " webers", .s1 = " Wb", .so = " Wb", .n1 = " Wb", .no = " Wb", .pl = "", .ps = "", .pn = "" },
    .{ .id = "week", .l1 = " week", .lo = " weeks", .s1 = " wk", .so = " wks", .n1 = "w", .no = "w", .pl = " per week", .ps = "/w", .pn = "/w" },
    .{ .id = "yard", .l1 = " yard", .lo = " yards", .s1 = " yd", .so = " yd", .n1 = "yd", .no = "yd", .pl = "", .ps = "", .pn = "" },
    .{ .id = "year", .l1 = " year", .lo = " years", .s1 = " yr", .so = " yrs", .n1 = "y", .no = "y", .pl = " per year", .ps = "/y", .pn = "/y" },
};

pub const compound_long = "{0} per {1}";
pub const compound_short = "{0}/{1}";
pub const compound_narrow = "{0}/{1}";
