//! GENERATED from CLDR supplemental weekData.json (tools/gen_weekdata.py).
//! Per-region first day of week and weekend days for Intl.Locale.getWeekInfo.

pub const First = struct { region: []const u8, day: u8 };
pub const Weekend = struct { region: []const u8, days: []const u8 };

pub const default_first_day: u8 = 1;
pub const default_weekend = [_]u8{ 6, 7 };

pub const first_day = [_]First{
    .{ .region = "AF", .day = 6 },
    .{ .region = "AG", .day = 7 },
    .{ .region = "AS", .day = 7 },
    .{ .region = "BD", .day = 7 },
    .{ .region = "BH", .day = 6 },
    .{ .region = "BR", .day = 7 },
    .{ .region = "BS", .day = 7 },
    .{ .region = "BT", .day = 7 },
    .{ .region = "BW", .day = 7 },
    .{ .region = "BZ", .day = 7 },
    .{ .region = "CA", .day = 7 },
    .{ .region = "CO", .day = 7 },
    .{ .region = "DJ", .day = 6 },
    .{ .region = "DM", .day = 7 },
    .{ .region = "DO", .day = 7 },
    .{ .region = "DZ", .day = 6 },
    .{ .region = "EG", .day = 6 },
    .{ .region = "ET", .day = 7 },
    .{ .region = "GT", .day = 7 },
    .{ .region = "GU", .day = 7 },
    .{ .region = "HK", .day = 7 },
    .{ .region = "HN", .day = 7 },
    .{ .region = "ID", .day = 7 },
    .{ .region = "IL", .day = 7 },
    .{ .region = "IN", .day = 7 },
    .{ .region = "IQ", .day = 6 },
    .{ .region = "IR", .day = 6 },
    .{ .region = "IS", .day = 7 },
    .{ .region = "JM", .day = 7 },
    .{ .region = "JO", .day = 6 },
    .{ .region = "JP", .day = 7 },
    .{ .region = "KE", .day = 7 },
    .{ .region = "KH", .day = 7 },
    .{ .region = "KR", .day = 7 },
    .{ .region = "KW", .day = 6 },
    .{ .region = "LA", .day = 7 },
    .{ .region = "LY", .day = 6 },
    .{ .region = "MH", .day = 7 },
    .{ .region = "MM", .day = 7 },
    .{ .region = "MO", .day = 7 },
    .{ .region = "MT", .day = 7 },
    .{ .region = "MV", .day = 5 },
    .{ .region = "MX", .day = 7 },
    .{ .region = "MZ", .day = 7 },
    .{ .region = "NI", .day = 7 },
    .{ .region = "NP", .day = 7 },
    .{ .region = "OM", .day = 6 },
    .{ .region = "PA", .day = 7 },
    .{ .region = "PE", .day = 7 },
    .{ .region = "PH", .day = 7 },
    .{ .region = "PK", .day = 7 },
    .{ .region = "PR", .day = 7 },
    .{ .region = "PT", .day = 7 },
    .{ .region = "PY", .day = 7 },
    .{ .region = "QA", .day = 6 },
    .{ .region = "SA", .day = 7 },
    .{ .region = "SD", .day = 6 },
    .{ .region = "SG", .day = 7 },
    .{ .region = "SV", .day = 7 },
    .{ .region = "SY", .day = 6 },
    .{ .region = "TH", .day = 7 },
    .{ .region = "TT", .day = 7 },
    .{ .region = "TW", .day = 7 },
    .{ .region = "UM", .day = 7 },
    .{ .region = "US", .day = 7 },
    .{ .region = "VE", .day = 7 },
    .{ .region = "VI", .day = 7 },
    .{ .region = "WS", .day = 7 },
    .{ .region = "YE", .day = 7 },
    .{ .region = "ZA", .day = 7 },
    .{ .region = "ZW", .day = 7 },
};

pub const weekends = [_]Weekend{
    .{ .region = "AF", .days = &.{ 4, 5 } },
    .{ .region = "BH", .days = &.{ 5, 6 } },
    .{ .region = "DZ", .days = &.{ 5, 6 } },
    .{ .region = "EG", .days = &.{ 5, 6 } },
    .{ .region = "IL", .days = &.{ 5, 6 } },
    .{ .region = "IN", .days = &.{ 7 } },
    .{ .region = "IQ", .days = &.{ 5, 6 } },
    .{ .region = "IR", .days = &.{ 5 } },
    .{ .region = "JO", .days = &.{ 5, 6 } },
    .{ .region = "KW", .days = &.{ 5, 6 } },
    .{ .region = "LY", .days = &.{ 5, 6 } },
    .{ .region = "OM", .days = &.{ 5, 6 } },
    .{ .region = "QA", .days = &.{ 5, 6 } },
    .{ .region = "SA", .days = &.{ 5, 6 } },
    .{ .region = "SD", .days = &.{ 5, 6 } },
    .{ .region = "SY", .days = &.{ 5, 6 } },
    .{ .region = "UG", .days = &.{ 7 } },
    .{ .region = "YE", .days = &.{ 5, 6 } },
};
