//! Versioned executable-memory contract shared by native code generators.
//!
//! This module owns allocation, the sole writable-to-executable transition,
//! instruction-cache synchronization, and retirement. ISA emitters receive a
//! writable slice only before `publish`; generated bytes are immutable after
//! publication. Native-tier availability remains a separate decision: being
//! able to allocate executable memory does not advertise a code generator.

const std = @import("std");
const builtin = @import("builtin");

pub const contract_version: u16 = 1;

pub const TargetOs = enum(u8) {
    macos = 1,
    linux = 2,
};

pub const Architecture = enum(u8) {
    aarch64 = 1,
    x86_64 = 2,
};

pub const Backend = enum(u8) {
    /// Darwin hardened-runtime mapping. The VMA uses MAP_JIT while per-thread
    /// `pthread_jit_write_protect_np` selects either its writable or executable
    /// view; publication permanently returns the compiling thread to execute.
    darwin_map_jit = 0,
    /// Anonymous POSIX pages begin RW and make one process-wide transition to
    /// RX through mprotect. They are never mapped or published RWX.
    posix_mprotect = 1,
};

pub const CacheSynchronization = enum(u8) {
    coherent = 0,
    darwin_icache_invalidate = 1,
    compiler_rt_clear_cache = 2,
};

pub const WriteProtection = enum(u8) {
    thread_scoped_jit = 0,
    process_page_transition = 1,
};

pub const Patching = enum(u8) {
    immutable_after_publish = 0,
};

/// Deterministic target contract. Runtime mapping addresses are intentionally
/// absent so identical target/options inputs select identical field values.
pub const Profile = struct {
    version: u16 = contract_version,
    os: TargetOs,
    arch: Architecture,
    backend: Backend,
    cache_synchronization: CacheSynchronization,
    write_protection: WriteProtection,
    patching: Patching = .immutable_after_publish,

    pub fn verify(self: Profile) error{InvalidExecutableMemoryProfile}!void {
        if (self.version != contract_version or self.patching != .immutable_after_publish)
            return error.InvalidExecutableMemoryProfile;
        switch (self.backend) {
            .darwin_map_jit => {
                if (self.os != .macos or self.arch != .aarch64 or
                    self.write_protection != .thread_scoped_jit)
                    return error.InvalidExecutableMemoryProfile;
                if (self.cache_synchronization != .darwin_icache_invalidate)
                    return error.InvalidExecutableMemoryProfile;
            },
            .posix_mprotect => {
                if (self.os != .linux or
                    (self.arch != .aarch64 and self.arch != .x86_64) or
                    self.write_protection != .process_page_transition)
                    return error.InvalidExecutableMemoryProfile;
                const expected_cache: CacheSynchronization = if (self.arch == .aarch64)
                    .compiler_rt_clear_cache
                else
                    .coherent;
                if (self.cache_synchronization != expected_cache)
                    return error.InvalidExecutableMemoryProfile;
            },
        }
    }

    /// Stable contract encoding used by inventories and future artifact keys.
    /// It never serializes Zig's target-enum ordinals or a runtime address.
    pub fn encode(self: Profile) error{InvalidExecutableMemoryProfile}![8]u8 {
        try self.verify();
        var bytes: [8]u8 = undefined;
        std.mem.writeInt(u16, bytes[0..2], self.version, .little);
        bytes[2] = @backingInt(self.os);
        bytes[3] = @backingInt(self.arch);
        bytes[4] = @backingInt(self.backend);
        bytes[5] = @backingInt(self.cache_synchronization);
        bytes[6] = @backingInt(self.write_protection);
        bytes[7] = @backingInt(self.patching);
        return bytes;
    }
};

pub fn profileFor(os: std.Target.Os.Tag, arch: std.Target.Cpu.Arch) ?Profile {
    if (os == .macos and arch == .aarch64) return .{
        .os = .macos,
        .arch = .aarch64,
        .backend = .darwin_map_jit,
        .cache_synchronization = .darwin_icache_invalidate,
        .write_protection = .thread_scoped_jit,
    };
    if (os == .linux and (arch == .aarch64 or arch == .x86_64)) return .{
        .os = .linux,
        .arch = if (arch == .aarch64) .aarch64 else .x86_64,
        .backend = .posix_mprotect,
        .cache_synchronization = if (arch == .aarch64) .compiler_rt_clear_cache else .coherent,
        .write_protection = .process_page_transition,
    };
    return null;
}

pub const host_profile = profileFor(builtin.os.tag, builtin.cpu.arch);
pub const supported = host_profile != null;

pub const State = enum(u8) { writable, executable };

/// One mapping with exactly one successful publication transition.
///
/// Allocation and publication stay on the compilation-claiming thread. Owner
/// publication establishes release/acquire visibility only after `publish`
/// returns, and Owner retirement unmaps only after the final execution reader.
pub const Memory = struct {
    mapping: []align(std.heap.page_size_min) u8,
    used: usize = 0,
    state: State = .writable,

    pub const InitError = std.posix.MMapError || error{ UnsupportedTarget, InvalidCapacity };
    pub const PublishError = std.process.ProtectMemoryError || error{InvalidCodeSize};

    pub fn init(min_capacity: usize) InitError!Memory {
        const selected = comptime host_profile orelse return error.UnsupportedTarget;
        selected.verify() catch unreachable;
        const capacity = alignedCapacity(min_capacity) catch return error.InvalidCapacity;
        const mapping = switch (comptime selected.backend) {
            .darwin_map_jit => blk: {
                const protection: std.posix.PROT = .{ .READ = true, .WRITE = true, .EXEC = true };
                var flags: std.posix.MAP = .{ .TYPE = .PRIVATE, .ANONYMOUS = true };
                flags.JIT = true;
                const result = try std.posix.mmap(null, capacity, protection, flags, -1, 0);
                // MAP_JIT write protection is thread-local. The compiling
                // thread alone receives the writable view until publication.
                pthread_jit_write_protect_np(0);
                break :blk result;
            },
            .posix_mprotect => try std.posix.mmap(
                null,
                capacity,
                .{ .READ = true, .WRITE = true },
                .{ .TYPE = .PRIVATE, .ANONYMOUS = true },
                -1,
                0,
            ),
        };
        return .{ .mapping = mapping };
    }

    pub fn deinit(self: *Memory) void {
        // `init` refuses unsupported targets, so no Memory can exist here and
        // the trap can never fire at runtime - but it must BE a runtime trap.
        // The previous `comptime host_profile orelse unreachable` folded
        // during analysis, so merely cross-compiling a consumer for a
        // profileless target (x86_64-windows, darwin-x86_64) failed the whole
        // build even though this code was dead there.
        if (comptime host_profile) |selected| {
            if (comptime selected.backend == .darwin_map_jit) {
                if (self.state == .writable) pthread_jit_write_protect_np(1);
            }
            std.posix.munmap(self.mapping);
            self.* = undefined;
        } else unreachable;
    }

    /// Ephemeral emitter view. Retaining and writing through this slice after
    /// `publish` violates the backend contract and is rejected by OS W^X.
    pub fn writableBytes(self: *Memory) []u8 {
        std.debug.assert(self.state == .writable);
        return self.mapping;
    }

    /// Flush emitted instructions, remove write access, and expose the exact
    /// used prefix as immutable executable bytes. Failure leaves the mapping
    /// writable and unpublished so the compiler can retire it transactionally.
    pub fn publish(self: *Memory, used: usize) PublishError!void {
        if (used == 0 or used > self.mapping.len) return error.InvalidCodeSize;
        std.debug.assert(self.state == .writable);
        // Runtime trap, not a comptime fold - see deinit.
        if (comptime host_profile) |selected| {
            synchronizeInstructionCache(self.mapping.ptr, used);
            switch (comptime selected.backend) {
                .darwin_map_jit => pthread_jit_write_protect_np(1),
                .posix_mprotect => try std.process.protectMemory(self.mapping, .{
                    .read = true,
                    .execute = true,
                }),
            }
            self.used = used;
            self.state = .executable;
        } else unreachable;
    }

    pub fn executableBytes(self: *const Memory) []const u8 {
        std.debug.assert(self.state == .executable);
        return self.mapping[0..self.used];
    }
};

fn alignedCapacity(min_capacity: usize) error{InvalidCapacity}!usize {
    if (min_capacity == 0) return error.InvalidCapacity;
    const page_size = std.heap.pageSize();
    const with_padding = std.math.add(usize, min_capacity, page_size - 1) catch
        return error.InvalidCapacity;
    return with_padding & ~(page_size - 1);
}

fn synchronizeInstructionCache(start: [*]u8, len: usize) void {
    // Runtime trap, not a comptime fold - see Memory.deinit.
    if (comptime host_profile) |selected| {
        switch (comptime selected.cache_synchronization) {
            .coherent => {},
            .darwin_icache_invalidate => sys_icache_invalidate(start, len),
            .compiler_rt_clear_cache => __clear_cache(@intFromPtr(start), @intFromPtr(start) + len),
        }
    } else unreachable;
}

extern "c" fn pthread_jit_write_protect_np(enabled: c_int) callconv(.c) void;
extern "c" fn sys_icache_invalidate(start: *anyopaque, len: usize) callconv(.c) void;
// Zig's compiler-rt provides this symbol for Linux AArch64. It is deliberately
// not declared from libc so freestanding embedders do not acquire a libc edge.
extern fn __clear_cache(start: usize, end: usize) callconv(.c) void;

test "executable memory target matrix separates mapping from tier support" {
    const mac_arm = profileFor(.macos, .aarch64).?;
    try mac_arm.verify();
    try std.testing.expectEqual(Backend.darwin_map_jit, mac_arm.backend);
    try std.testing.expectEqual(CacheSynchronization.darwin_icache_invalidate, mac_arm.cache_synchronization);
    try std.testing.expect(profileFor(.macos, .x86_64) == null);
    const linux_arm = profileFor(.linux, .aarch64).?;
    try linux_arm.verify();
    try std.testing.expectEqual(Backend.posix_mprotect, linux_arm.backend);
    try std.testing.expectEqual(CacheSynchronization.compiler_rt_clear_cache, linux_arm.cache_synchronization);
    try std.testing.expectEqualSlices(u8, &.{ 1, 0, 2, 1, 1, 2, 1, 0 }, &(try linux_arm.encode()));
    const linux_x64 = profileFor(.linux, .x86_64).?;
    try linux_x64.verify();
    try std.testing.expectEqual(CacheSynchronization.coherent, linux_x64.cache_synchronization);
    try std.testing.expect(profileFor(.ios, .aarch64) == null);
    try std.testing.expect(profileFor(.windows, .x86_64) == null);
    try std.testing.expect(profileFor(.linux, .wasm32) == null);
    try std.testing.expectEqualSlices(u8, &.{ 1, 0, 1, 1, 0, 1, 0, 0 }, &(try mac_arm.encode()));
    try std.testing.expectEqualSlices(u8, &.{ 1, 0, 2, 2, 1, 0, 1, 0 }, &(try linux_x64.encode()));
}

test "executable memory profile verifier rejects mismatched policy" {
    var profile = profileFor(.linux, .aarch64).?;
    profile.version += 1;
    try std.testing.expectError(error.InvalidExecutableMemoryProfile, profile.verify());
    profile = profileFor(.linux, .aarch64).?;
    profile.cache_synchronization = .coherent;
    try std.testing.expectError(error.InvalidExecutableMemoryProfile, profile.verify());
    profile = profileFor(.macos, .aarch64).?;
    profile.write_protection = .process_page_transition;
    try std.testing.expectError(error.InvalidExecutableMemoryProfile, profile.verify());
}

test "executable memory capacity rejects zero and overflow" {
    try std.testing.expectError(error.InvalidCapacity, alignedCapacity(0));
    try std.testing.expectError(error.InvalidCapacity, alignedCapacity(std.math.maxInt(usize)));
    try std.testing.expectEqual(std.heap.pageSize(), try alignedCapacity(1));
    try std.testing.expectEqual(std.heap.pageSize(), try alignedCapacity(std.heap.pageSize()));
}

test "executable memory publishes one exact immutable prefix" {
    if (!supported) return error.SkipZigTest;
    var memory = try Memory.init(17);
    defer memory.deinit();
    try std.testing.expectEqual(State.writable, memory.state);
    try std.testing.expectEqual(@as(usize, 0), memory.used);
    memory.writableBytes()[0..3].* = .{ 1, 2, 3 };
    try std.testing.expectError(error.InvalidCodeSize, memory.publish(0));
    try std.testing.expectEqual(State.writable, memory.state);
    try std.testing.expectError(error.InvalidCodeSize, memory.publish(memory.mapping.len + 1));
    try std.testing.expectEqual(State.writable, memory.state);
    try memory.publish(3);
    try std.testing.expectEqual(State.executable, memory.state);
    try std.testing.expectEqualSlices(u8, &.{ 1, 2, 3 }, memory.executableBytes());
}
